### ISSUE TITLE
GCE firewall instructions assume a given IP address range

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/calico-containers#1001]
The GCE.md instructions include a line explaining how to open the firewall for IP in IP traffic.  They assume the network provided by GCE is 10.240.0.0/16.  However, I don't believe this is guaranteed (i.e. I've seen different ones in other GCE projects) - in fact, it looks like this is the "legacy" default for GCE, but they've now moved to use 10.128.0.0/9 for new instances.

Either way the docs probably need something to tell the user to use _their_ value here.

**Comment by robbrockbank** [comment]
Fixed by #1002
