### ISSUE TITLE
Allow calicoctl --libnetwork with docker to not detach?

### ISSUE THREAD

**Issue by wrouesnel** [projectcalico/calico-containers#1003]
Setting up `calicoctl` with libnetwork should properly support the use case of running it as a systemd unit (i.e. a non-detaching, logs to stdout/stderr binary).

This seems like it could be supported by having calicoctl stay attached to the docker containers, and attach as a threaded log forwarded for both.

**Comment by robbrockbank** [comment]
When you are using `calicoctl node` in libnetwork mode, calicoctl spins up two separate docker containers - one for the Calico node and one for the libnetwork plugin.  If you want to run this in systemd you'll need to run both containers as separate systemd processes.

Have a look at this document for details:  https://github.com/projectcalico/calico-containers/blob/master/docs/CalicoAsService.md

**Comment by robbrockbank** [comment]
Hi @wrouesnel - did the above solve your problem?  OK to close?

**Comment by wrouesnel** [comment]
Yes and no : manually creating the containers works fine, but it does seem like calicoctl should support this natively. Would a patch which adds this be accepted?

**Comment by tomdee** [comment]
Yes a PR would be great if this think this is a useful/important feature.

**Comment by matthewdupre** [comment]
`calicoctl node --libnetwork` won't be able to not detach, because there's 2 containers.

We don't want to go down the road of trying to merge calico-libnetwork into calico-node (node is used for other orchestrators), so we're stuck with 2 containers.

I think the only way we can fix this via calicoctl is by adding an option to only start the libnetwork container.  @wrouesnel do you think that would be worthwhile?

**Comment by wrouesnel** [comment]
That is pretty much the solution I'm mimicking at the moment (i.e. I extracted the options and made up a service file for it at the moment).

An observation is that calico-libnetwork does in fact start and run just fine without _needing_ the node container to be running before it is.

**Comment by matthewdupre** [comment]
This is being worked on in https://github.com/projectcalico/libnetwork-plugin/pull/64

**Comment by caseydavenport** [comment]
As of calico/node v0.23.0, the libnetwork plugin should run within the `calico/node` container, and `--detach=false` should work as expected.
