### ISSUE TITLE
how can i use calico with mesos decision my ip with env

### ISSUE THREAD

**Issue by 245347881** [projectcalico/calico-containers#1004]
i see the docs Mesos with Calico networking, but i don't understand it,when i complete Calico with Docker Containerizer - Manual Install Guide，it tell me Key = net
Value = <network name>  but how can i designated a ip address?

**Comment by robbrockbank** [comment]
If you have created a Calico Docker network, e.g. "net1" then you specify key=net, value=net1 to use that network.  You can also specify a key=ip value=<ip address> to select a particular IP address from a Calico pool.

**Comment by robbrockbank** [comment]
Hi @245347881 - did the above sort out the issue - or did I misunderstand what you were asking?

**Comment by 245347881** [comment]
hi, @robbrockbank  thank you very much ,i Success
