### ISSUE TITLE
TypeError from etcd client destructor

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#1005]
User was running calicoctl from the repo, rather than the packaged binary and they hit the attached error.  I believe it's a benign error from the etcd Client's destructor but it'd be good to shut it down propery so that we avoid this.

<img width="793" alt="screen shot 2016-06-01 at 14 20 56" src="https://cloud.githubusercontent.com/assets/469264/15710994/1e496a24-2804-11e6-8471-e52c59097b47.png">

**Comment by matthewdupre** [comment]
Closing this, since it shouldn't affect the forthcoming calicoctl anyway.)

**Comment by caseydavenport** [comment]
Fixed in v1.0.0-beta
