### ISSUE TITLE
Calico-Libnetwork should fail on unusable opts

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-containers#1017]
Docker network creation supports passing `--opt` [(as we explain in our documentation)](https://github.com/projectcalico/calico-containers/blob/e249061188ed35d04b7d1ccd839ed920c7e81c4a/docs/calico-with-docker/docker-network-plugin/README.md#d-networking-using-default-ipam-in-a-cloud-environment). We accept `--opt ipip` and `--opt nat-outgoing` as possible options, but they are only used [if not using calico-ipam](https://github.com/projectcalico/libnetwork-plugin/blob/85335c32e63215f41f78d19065813dea2671a616/libnetwork/driver_plugin.py#L329). 

From the user's perspective, they might create a network using calico-ipam and pass those two parameters, but Calico will never modify the pool to use them.

Two possible solutions for this issue:
1. Fail with an error if they use default ipam and still pass one of those two options
2. Actually apply those options to the pool when they are using Calico IPAM.

We may also want to widen the scope of this issue to fail on all unknown/unused opts passed during creation.

**Comment by tomdee** [comment]
This bug is probably better tracked on the libnetwork-plugin repo

**Comment by djosborne** [comment]
This issue was moved to projectcalico/libnetwork-plugin#65
