### ISSUE TITLE
Document use of link-local address as gateway

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#1023]
We set up the following routes within a container to get traffic out to the host:

```
default via 169.254.1.1 dev eth0
168.254.1.1 dev eth0
```

We should document this so that it isn't confusing / surprising to users.

**Comment by caseydavenport** [comment]
@djosborne giving this one to you as one to consider as part of your docs work.

**Comment by djosborne** [comment]
This issue was moved to projectcalico/calico#66
