### ISSUE TITLE
Mesos dns doesn't resolve the container host to calico assigned ip 

### ISSUE THREAD

**Issue by rajholla** [projectcalico/calico-containers#1027]
Mesos dns resolves to slave ip instead of calico ipam assigned ip for the container. 
Here is my mesos-dns config

{
"zk": "zk://127.0.0.1:2181/mesos",
"refreshSeconds": 30,
"ttl": 60,
"domain": "mesos",
"port": 53,
"resolvers": ["144.202.8.11", "144.202.8.12", "144.202.54.10"],
"timeout": 5,
"listener": "0.0.0.0",
"email": "root.mesos-dns.mesos",
"IPSources": ["netinfo", "host"]
}

dig backend-calico-stars.marathon.mesos

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.3 <<>> backend-calico-stars.marathon.mesos
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29482
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;backend-calico-stars.marathon.mesos. IN        A

;; ANSWER SECTION:
backend-calico-stars.marathon.mesos. 60 IN A    10.146.27.75

;; Query time: 1 msec
;; SERVER: 10.146.27.65#53(10.146.27.65)
;; WHEN: Sat Jun 25 20:06:09 CDT 2016
;; MSG SIZE  rcvd: 69

Resolved ip 10.146.27.75 is the ip of the slave where backend-calico-stars is running.

**Comment by caseydavenport** [comment]
@rajholla - I believe there is a config option that must be set to tell Mesos DNS to use the Calico IP.  @djosborne should be able to help you further.

**Comment by djosborne** [comment]
Hmm seems you've correctly set the mesos configuration to return calico IPs. Which version of Marathon and Mesos are you using? And is this the Docker Containerizer?

**Comment by rajholla** [comment]
Hello @djosborne @caseydavenport 
We Docker Containerizer
Marathon 0.15.1
mesos version 0.27
Basically using mesosphere orchestrator(1.6.1)

**Comment by djosborne** [comment]
You'll need to upgrade to Mesos 0.28.0.

Unfortunately, Mesos 0.27.0 does not include the functionality to read the IP address assigned to a docker container running on a user-defined network.

Before Docker introduced user-defined networks, the IP address of a task was reported by Docker Engine in `NetworkSettings.IPAddress`. But a task launched on a UDN will have a blank `NetworkSettings.IPAddress`, and the IP will be stored in `NetworkSettings.Networks.<netname>.IPAddress`. 

Mesos 0.28.0 includes [JIRA-4370](https://issues.apache.org/jira/browse/MESOS-4370) which tells the  Docker Containerizer to check which network a container is attached to, and then extract the container IP from the new field.

Upgrading to 0.28.0 should resolve your issue.

**Comment by rajholla** [comment]
@djosborne Thank you for the information. I will close the thread now.
