### ISSUE TITLE
Unable to connect a single container to two calico networks with libnetwork

### ISSUE THREAD

**Issue by sdurrheimer** [projectcalico/calico-containers#1031]
Hi there, using calico as docker libnetwork plugin, is it possible to connect a single container to multiple calico network ? 

When following the [introduction](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md), if I add the `workload-A` container (`net1`) to the `net2` network (with the `docker network connect` command) I get the following error :
```
Error response from daemon: failed to add interface tmpfbd5398a51d to sandbox: error setting interface "tmpfbd5398a51d" routes to ["169.254.1.1/32"]: file exists
```

**Comment by tomdee** [comment]
This looks like a bug. We'll investigate and fix int he next release

**Comment by sdurrheimer** [comment]
Do we have a estimate date for the `v0.21` ? This bug is kinda blocking my plan of deploying Calico for a project.

**Comment by robbrockbank** [comment]
@sdurrheimer - unfortunately it's a limitation of our libnetwork plugin that you can't attach multiple calico networks to a container (see note in our docs: https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/AdvancedPolicy.md#multiple-networks )

For Calico networks, we want to add the same route in the container for each network - Calico does not require separate subnets/interfaces to handle separate networks.  Unfortunately the libnetwork interface does not allow this - so the upshot is you can only have a single Calico network on a container.

**Comment by robbrockbank** [comment]
@sdurrheimer - I'm going to close this issue as it is an unfortunate limitation due to the libnetwork API.
