### ISSUE TITLE
How to reslove the problem when create network

### ISSUE THREAD

**Issue by jaminlai** [projectcalico/calico-containers#1032]
Hi:

  I create the docker network via such command:

`docker network create --driver calico --ipam-driver calico net1`

However, it caught error response as below:
`Error response from daemon: failed to update store for object type *libnetwork.network: client: etcd cluster is unavailable or misconfigured`

How can I do with it, thanks.

**Comment by djosborne** [comment]
Have you [set up docker to use a cluster store](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/ManualSetup.md#docker) and [succesfully launched the calico-node and calico-libnetwork containers](https://github.com/projectcalico/calico-containers/tree/master/docs/calico-with-docker/docker-network-plugin#2-starting-calico-services)?

**Comment by djosborne** [comment]
@jaminlai Can  you also post which version of docker, libnetwork, and calico-node, and calicoctl you are using?

**Comment by jaminlai** [comment]
I have resolve the problem, thank you very much.

Because the etcd cluster bind on 127.0.0.1:2379，but my calico require the real ip, so that I change the etcd's bind ip

**Comment by laurencechan** [comment]
Hey @jaminlai I've just encoutered the same error as you did. Could you tell me more details about how you solve this problem ? Thanks so much!!
