### ISSUE TITLE
calicoctl doesn't provide a way to release orphan endpoints in a Kubernetes cluster

### ISSUE THREAD

**Issue by DreadPirateShawn** [projectcalico/calico-containers#1034]
There are situations where Calico endpoints aren't properly torn down (for instance, catastrophic node failure). As it stands today, even though such endpoints can be manually identified, calicoctl provides no way to remove such endpoints.

**Versions:** calico-node container 0.18.0, kubernetes calico cni 1.1.0 (​**not**​ using calico libnetwork)

**Repro:**

```
MINIONS="kube-minion1 kube-minion2"

for node in $MINIONS; do
    # Delete the node, to make sure K8s master scheduler notices
    kubectl.sh delete node $node

    # Kill kubelet on the node and restart docker daemon
    ssh $node "sudo pkill -9 hyperkube"
    ssh $node "sudo service docker restart"
done

# Then restart your minions, your script may vary.
```

**This basically results in:**
1. podA is on hostA, and has calico endpointA
2. hostA suffers upgrade / reboot / crash / whatever — podA goes away abruptly
3. endpointA remains
4. new pod is rescheduled on hostA, which came back up minutes later — now we have podB on hostA, with calico endpointB

...but endpointA still remains.

**Considered but not viable:**
1) `calicoctl node remove --remove-endpoints --hostname={h}` -- This doesn't work because the nodes need to stay active -- hostA has both valid / active endpoints, along with the orphans.
2) `calicoctl container remove` -- This doesn't apply in a Kubernetes + Calico cluster.

**Workaround:**

As it stands, the only way to clean up such orphan endpoints is via direct etcd modification, which is inherently a Bad Idea.

See the [calico-endpoint-cleanup.sh.txt](https://github.com/projectcalico/calico-containers/files/344173/calico-endpoint-cleanup.sh.txt) for a sample implementation, but the gist is:
- get a list of pods
- get a list of calico endpoints
- check for any calico endpoints that do not correspond to a pod -- these are the orphans
- for each orphan endpoint's workflow id and ip:
  - `etcdctl ls --recursive | grep calico | grep "/${workload_id}$" | grep -v ipam | xargs etcdctl rm --recursive`
  - if no error from the former, then `calicoctl ipam release $ip`

**Feature Request:**

There should be a calicoctl command to remove known-invalid endpoints, eg:

`calicoctl endpoint remove <endpoint_id>`

**Comment by DreadPirateShawn** [comment]
Tagging @caseydavenport per request, via Slack discussion of this scenario.

**Comment by DreadPirateShawn** [comment]
[calico-endpoint-cleanup.sh.txt](https://github.com/projectcalico/calico-containers/files/344173/calico-endpoint-cleanup.sh.txt)

**Comment by caseydavenport** [comment]
Pulling in @robbrockbank since I think he's most familiar with `calicoctl`.

I feel like we've considered something like this in the past, but can't recall why we did go ahead with it.  This isn't the first time we've had trouble with lingering endpoints that are hard to remove, and it feels to me like we should have a way to get rid of them via calicoctl.

**Comment by DreadPirateShawn** [comment]
I found several tickets which touched on the same themes, but all of them seemed to ultimately resolve to fixing a root cause that *led* to orphan endpoints, or supporting ipam release, etc... all of which are certainly great fixes, but I think my situation is one of the cleanest "yank the rug out with no chance for Calico / Kubernetes to cleanup" repros.

**Comment by caseydavenport** [comment]
As per https://github.com/tigera/libcalico-go/issues/67

We plan on adding this sort of feature to `calicoctl` in the Go release.

**Comment by caseydavenport** [comment]
Adding to v1.0 milestone for re-test against the new Go calicoctl.
