### ISSUE TITLE
How to connect calico node inside the external network(non-calico assigned ip)

### ISSUE THREAD

**Issue by jaminlai** [projectcalico/calico-containers#1036]
Hi:

Now I practiced calico and have success communicated each other between two docker container in calico node.

However, I have deploy haproxy on another physical host(non-calico assigned ip,ip address such as 172.16.xx.xx), and I expected the haproxy could find the docker container(ip address such as 192.168.xx.xx) in calico node, but on the 172.16.xx.xx I cound not ping success to 192.168.xx.xx.

please help me, thank you!

**Comment by djosborne** [comment]
@jaminlai Your haproxy service is going to need two things in place to connect to 192.168.x.x

#### 1. A route to the Calico IP
- If you are planning on running calico workloads on the same box haproxy is running on, simply run `calico/node` on that box. Calico-node will then populate its routing table with routes to the calico workloads on other boxes. This is a quick and easy way to populate the routing table.
- If you are **not** running calico workloads alongside haproxy, then it is more correct to configure the  router that haproxy's host is currently using as its gateway to peer with the virtual calico network.

#### 2. A `allow` rule in the ACL assigned to the calico-networked docker workload
Calico's default ACL allows only incoming requests from other calico-networked containers in the same profile. You will need to modify this rule to also accept traffic incoming from your haproxy box. You can use calicoctl to make that profile modification: `calicoctl profile <prof-name> rule add inbound allow tcp from cidr <ip-of-haproxy-host>/32 to ports <port-of-service>`

If you have more questions, we typically handle deployment troubleshooting on our slack. I'd encourage you to message us there, as its easier to go back and forth: https://slack.projectcalico.org/
