### ISSUE TITLE
Create calico/cni container

### ISSUE THREAD

**Issue by mattymo** [projectcalico/calico-containers#1037]
It would be very useful to distribute a calico/cni Docker container that could be consumed by Kubernetes hyperkube. Here is how workflow would change:
Old method:
wget -N -P /opt/cni/bin/ https://github.com/projectcalico/calico-cni/releases/download/v1.3.1/calico
wget -N -P /opt/cni/bin/ https://github.com/projectcalico/calico-cni/releases/download/v1.3.1/calico-ipam
docker run -d gcr.io/google_containers/hyperkube-amd64:v1.3.0 $OPTS

Proposed new method:
docker start --name calico-cni calico/cni:v1.3.1
docker run -d --volumes-from calico-cni gcr.io/google_containers/hyperkube-amd64:v1.3.0  $OPTS

The main objective in running Kubernetes hyperkube single binary is to reduce the amount of downloaded content on the host and stop downloading individual files that are quite hard to track and manage versions. Calico has this for calicoctl and calico-node already, but not for the CNI plugins.

**Comment by caseydavenport** [comment]
@tomdee what do you think?  

We've wanted to move away from the "wget" distribution method to something containerized for a while now.  The CoreOS hyperkube images come with Calico CNI binaries, but as far as I know there isn't a way to specify which version to use.  The suggestion seems like a good way to do this to me.

**Comment by tomdee** [comment]
Sounds like a good idea to me

**Comment by caseydavenport** [comment]
@mattymo Looks like we're in agreement :)

Would you be willing to contribute the Dockerfile for this to https://github.com/projectcalico/calico-cni?

**Comment by mattymo** [comment]
@caseydavenport My hands are full at the moment, but I'm hoping we can find a volunteer. If not, I'll contribute one in about two weeks.

**Comment by bogdando** [comment]
This https://github.com/projectcalico/calico-cni/pull/114

**Comment by bogdando** [comment]
Also note, it might make sens to run dockerized components as a kublet's static pods.
If some cannot be put there, we have to think who will manage them, like systemd nspawn f.e.

**Comment by bogdando** [comment]
We have the image now, so this may continue

**Comment by mattymo** [comment]
Bogdan, kubelet requires calico-node to be running as far as I can tell. I think that precludes the possibility of running calico-node as a static pod

**Comment by caseydavenport** [comment]
@mattymo  @bogdando - Closing this since the PR has been merged.  Will publish an image with the next release.

I've opened https://github.com/projectcalico/calico-containers/issues/1061 to continue discussion on running calico/node under kubernetes.

**Comment by mattymo** [comment]
Sorry to reopen this, but can this get built and hosted now? https://quay.io/organization/calico doesn't show cni container.

**Comment by caseydavenport** [comment]
@mattymo - sorry, was planning on doing this with the next calico-cni release (which hasn't happened yet).

I've pushed an image to `quay.io/calico/cni:latest` which includes the calico CNI binaries built from master.  We'll start doing versioned tags with the next release.
