### ISSUE TITLE
calicoctl doesn't pass through error causes from python-etcd

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico-containers#1043]
It's common for python-etcd to return errors when setting up certificate verification on the connection.

python-etcd now logs causes for these errors, but we don't display them in calicoctl output.  It would be helpful if we did.

**Comment by matthewdupre** [comment]
(Rob to check against new version and close this if it's fixed there.)

**Comment by caseydavenport** [comment]
calicoctl isn't written in Python anymore.
