### ISSUE TITLE
Vagrant-coreos: trying to recreate existing namespace in skydns yaml

### ISSUE THREAD

**Issue by zefciu** [projectcalico/calico-containers#1054]
When trying to run the vagrant-coreos example and running the ``skydns.yaml`` file you get ``namespace already exists`` error. Indeed the ``skydns.yaml`` contains redefinition of ``kube-system``. What is the reason for this? Does some other example require this redefinition or can it be removed from this file to make vagrant-coreos example work out of the box?

**Comment by ae6rt** [comment]
I have related experience with this.  I assume the system namespace exists out of the box on on new k8s cluster, which makes explicitly defining the kube-system namespace unnecessary.  One had to create the  namespace manually in k8s 1.2, but no longer:

https://github.com/kubernetes/kubernetes/pull/25196

**Comment by caseydavenport** [comment]
Yep, that k8s issue is the culprit.

If you look at the latest master, that manifest no longer configures the kube-system namespace: https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/manifests/skydns.yaml
