### ISSUE TITLE
There should be a simpler demo than the stars demo

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico-containers#1056]
There should be a demo of NetworkPolicy that has minimal moving parts.  This could be good for making the basic idea really clear, and for providing a simple use case for debugging and bug reports.

**Comment by caseydavenport** [comment]
This is actually done now - see https://github.com/projectcalico/calico-containers/tree/master/docs/cni/kubernetes/simple-policy-demo
