### ISSUE TITLE
Ability to run `calico/node` as a static pod / DaemonSet in Kubernetes

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#1061]
Opening this issue to track discussion of running `calico/node` on Kubernetes.

This is something we've considered for a while and should be possible, potentially needing some minor tweaks in Kubernetes / Calico to make it work.

Relevant issues / PRs
- Better IP auto-detection https://github.com/projectcalico/calico-containers/issues/873
- kube-up: https://github.com/kubernetes/kubernetes/pull/30598

**Comment by matthewdupre** [comment]
@caseydavenport: In what kubernetes specific situations is the IP detection a problem?

I ask because the IP detection is never going to be perfect, so unless there's a concrete case that someone's actually that doesn't work (i.e. a set of interfaces and addresses on them that breaks), we should probably just close this.

**Comment by caseydavenport** [comment]
@matthewdupre This issue is not solely about the IP detection (as per the title).

The case here is running Calico as a DaemonSet, where a single copy of calico/node is run as a pod under kubernetes on each node.  In this case, we don't yet have a way of telling `calico/node` what the host's IP address it should use is.

Our auto-detection fails most commonly when there is more than one interface with an IP address on it.  This is a pretty common scenario.  While we probably can't get "perfect" auto-detection like you say, we should be able to provide the right set of parameters that the auto-detection gets it right pretty much all of the time (e.g by specifying either an interface or a CIDR to which the IP must belong) - but that's really a comment for the linked issue (not this one).

**Comment by caseydavenport** [comment]
This PR attempts to do this in kube-up: https://github.com/kubernetes/kubernetes/pull/30598

**Comment by caseydavenport** [comment]
Docs in this repo now do this.
