### ISSUE TITLE
KubernetesIntegration.md is not pinned to specific versions

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico-containers#1062]
https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md tells me to use `http://www.projectcalico.org/builds/calicoctl` rather than a specific version, and tells me to use `https://raw.githubusercontent.com/projectcalico/k8s-policy/master/examples/policy-controller.yaml`, which calls for the `latest` policy controller image.

**Comment by MikeSpreitzer** [comment]
CC @caseydavenport

**Comment by caseydavenport** [comment]
Thanks for spotting these.  I definitely want to pin down all the places we reference master builds and make sure they're stuck to a specific version.

**Comment by caseydavenport** [comment]
@robbrockbank what is the position on pinning version in the docs?  I thought master docs were meant to use the latest versions, whereas releases are supposed to pin these.

**Comment by caseydavenport** [comment]
This doc has moved to the main Calico repo / docs: http://docs.projectcalico.org/v1.5/getting-started/kubernetes/installation/

Versions are pinned by this guy: https://github.com/projectcalico/calico/pull/104
