### ISSUE TITLE
whether the --ip parameter can use?

### ISSUE THREAD

**Issue by 245347881** [projectcalico/calico-containers#1074]
when i run a container like this : docker run --net applications --name my_workload --ip 192.168.100.253 -tid busybox ,it tell me flag provided but not defined: --ip,

**Comment by matthewdupre** [comment]
Interesting - that command works for me (admittedly I'm running a very recent Docker: 1.12 rc4).

What version are you using?

**Comment by 245347881** [comment]
@matthewdupre my docker version is  Docker version 1.9.1, build ab77bde/1.9.1,thanks you

**Comment by matthewdupre** [comment]
@245347881 Docker 1.9.1 doesn't support specifying IPs: you need at least 1.10.

See https://github.com/docker/docker/pull/19001 for the PR that merged it.

**Comment by 245347881** [comment]
thank you
