### ISSUE TITLE
calico/ctl container v0.20.0 is actually 0.19.0

### ISSUE THREAD

**Issue by mattymo** [projectcalico/calico-containers#1081]
$ docker run calico/ctl:v0.20.0 version
0.19.0-dev

This could be introducing issues for people who want it to behave like v0.20.0 version.

**Comment by matthewdupre** [comment]
OK; I've built a new v0.20.0 that should be correctly versioned.  If you've been using the '0.19.0-dev' version, I wouldn't worry too much: it's very much closer to 0.20.0 than 0.19.0.
