### ISSUE TITLE
calicoctl should check rp_filter

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-containers#1082]
On a system where `net.ipv4.conf.all.rp_filter` is set to 2, calicoctl will successfully launch calico-node, but Felix will stack trace with the following error:
```
2016-07-28 18:19:24,684 [CRITICAL][307/4] calico.felix.devices 70: Kernel's RPF check is set to 'loose'.  This would allow endpoints to spoof their IP address.  Calico requires net.ipv4.conf.all.rp_filter to be set to 0 or 1.
2016-07-28 18:19:24,684 [ERROR][307/4] calico.felix.felix 259: Exception killing main greenlet
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/felix.py", line 79, in _main_greenlet
    devices.configure_global_kernel_config()
  File "/usr/lib/python2.7/site-packages/calico/felix/devices.py", line 74, in configure_global_kernel_config
    raise BadKernelConfig("net.ipv4.conf.all.rp_filter set to 'loose'")
BadKernelConfig: net.ipv4.conf.all.rp_filter set to 'loose'
```

Either Calicoctl should be checking this and refusing to launch node, or calicoctl should simply correct it itself.

**Comment by neiljerram** [comment]
I was going to say that if calicoctl was going to enforce rp_filter, would it make better sense for Felix to do that instead (rather than just checking).

However, if you're now thinking that calicoctl should only check and warn, that thought no longer applies.

**Comment by djosborne** [comment]
To further complicate things, seems DC/OS is intentionally setting `rp_filter=2` at launch. I spotted this in the slave logs:
```
Jul 28 10:15:41 a1.dcos bootstrap[5875]: [INFO] Zookeeper connection established, state: CONNECTED
Jul 28 10:15:41 a1.dcos bootstrap[5875]: [DEBUG] bootstrapping dcos-mesos-slave
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/all/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/default/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/docker0/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/dummy0/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/enp0s3/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/enp0s8/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/lo/rp_filter: 2
Jul 28 10:15:41 a1.dcos bash[5881]: /proc/sys/net/ipv4/conf/spartan/rp_filter: 2
Jul 28 10:15:41 a1.dcos systemd[1]: Started Mesos Agent: DC/OS Mesos Agent Service.
```

This vague DC/OS issue seems to suggest this is intentional: https://dcosjira.atlassian.net/browse/DCOS-230

Can we modify Felix so that it is compatible with loose mode?
```
rp_filter - INTEGER
	0 - No source validation.
	1 - Strict mode as defined in RFC3704 Strict Reverse Path
	    Each incoming packet is tested against the FIB and if the interface
	    is not the best reverse path the packet check will fail.
	    By default failed packets are discarded.
	2 - Loose mode as defined in RFC3704 Loose Reverse Path
	    Each incoming packet's source address is also tested against the FIB
	    and if the source address is not reachable via any interface
	    the packet check will fail.

	Current recommended practice in RFC3704 is to enable strict mode
	to prevent IP spoofing from DDos attacks. If using asymmetric routing
	or other complicated routing, then loose mode is recommended.

	The max value from conf/{all,interface}/rp_filter is used
	when doing source validation on the {interface}.

	Default value is 0. Note that some distributions enable it
	in startup scripts.
```

**Comment by neiljerram** [comment]
There's a comment in the relevant Felix code (devices.py) that seems pretty clear about the situation:

    # For IPv4, we rely on the kernel's reverse path filtering to prevent
    # workloads from spoofing their IP addresses.
    #
    # The RPF check for a particular interface is controlled by several
    # sysctls:
    #
    # - ipv4.conf.all.rp_filter is a global override
    # - ipv4.conf.default.rp_filter controls the value that is set on a newly
    #   created interface
    # - ipv4.conf.<interface>.rp_filter controls a particular interface.
    #
    # The algorithm for combining the global override and per-interface values
    # is to take the *numeric* maximum between the two.  The values are:
    # 0=off, 1=strict, 2=loose.  "loose" is not suitable for Calico since it
    # would allow workloads to spoof packets from other workloads on the same
    # host.  Hence, we need the global override to be <=1 or it would override
    # the per-interface setting to "strict" that we require.
    #
    # We bail out rather than simply setting it because setting 2, "loose",
    # is unusual and it is likely to have been set deliberately.

'Making Felix compatible with loose mode' could perhaps be done by implementing source address checks ourselves in iptables.  But ISTR there's some reason why it's much better for us to let rp_filter do it.  (As well obviously being less code for us to maintain.)  @fasaxc does this ring any bells?

**Comment by matthewdupre** [comment]
One more thing: strictly speaking, unprivileged containers can't spoof IPs anyway.

I'd probably want to figure out why Mesos needs (or thinks it needs) loose.

**Comment by djosborne** [comment]
Matt and I just finished digging, seems there's a very specific scenario that requires `rp_filter=2` in DC/OS. However, they enable it across **all** interfaces, when it really only needs to be enabled on one particular VTEP on each host. I'm going open a issue with DC/OS to make that change.

**Comment by fasaxc** [comment]
Damn, I forget the details for why it's hard to get an RPF check right in iptables but we did get it wrong when we implemented it that way and we made the switch to using the kernel's version because it's more comprehensive and earlier in the pipeline.

For IPv6, RPF checks are implemented as a dedicated iptables filter rather than a global option (so presumably we could have selective iptables rules that execute the RPF check only on the interfaces we need it).  If the iptables module supports IPv4 too, maybe that'd be an option.  OTOH, that would require a more recent kernel than we currently support.  That RPF check module isn't in the CentOS 6.5 kernel.

**Comment by djosborne** [comment]
@fasaxc so that being said, implementing RPF checks ourselves sounds like something we should continue to avoid. The correct solution to the larger problem is to dial down DC/OS' overreaching configuration of rp_filter=2 to just the relevant interfaces. However, I'm also concerned that we won't have enough time to do that before DC/OS 1.8 is released, meaning calico would not be compatible with at all with the new release.
So, I'd propose the following:

- Make the enforcement of rp_filter configurable in Felix, so that we could work in Loose mode. Obviously this is not the ideal solution, but it would at least serve to allow people to trial Calico in DC/OS while we work on the underlying issue.
- Improve calicoctl's handling when rp_filter=2 on the host. Enhance it to refuse to launch `calico/node` when rp_filter=2, but also add some way to bypass that (`--ignore-rpfilter`) and launch node with felix configured to ignore the `rp_filter=2`
- Submit patch to DC/OS so rp_filter is only set on the relevent interfaces, circumventing the previous two points.

**Comment by djosborne** [comment]
I've opened https://dcosjira.atlassian.net/browse/DCOS-265 and submitted a PR to DC/OS

**Comment by fasaxc** [comment]
@djosborne Agreed, I think DC/OS should be fixed.

However, I'm not talking about rolling our own (which is what we used to do).  The kernel has two types of RPF check.  One type is controlled by the flag that we've been discussing, and only applies to IPv4.  The other type is a dedicated iptables match rule:
```
   rpfilter
       Performs a reverse path filter test on a packet.  If a reply to the packet would be sent via the same interface that the packet arrived on, the packet will  match.   Note  that,  unlike  the  in-kernel
       rp_filter,  packets  protected  by  IPSec are not treated specially.  Combine this match with the policy match if you want this.  Also, packets arriving via the loopback interface are always permitted.
       This match can only be used in the PREROUTING chain of the raw or mangle table.
  ...
```
for IPv6, you have to use the latter type so that's what we do.  What I'm wondering is, could we use that for IPv4 as well?  If we did that, I don't think it would be bypassed by the global "loose" setting.  the advantage is, we can have a condition on that rule so we say "if interface-name starts with cali and it fails the RPF check, DROP it" so we shouldn't interfere with DC/OS's requirement for loose on the interface it cases about.

**Comment by djosborne** [comment]
Update on the DC/OS PR - the fix isn't as easily implementable in DC/OS as we thought. There are three different components of DC/OS which create a new virtual interface which all need rp_filter=2 to function properly. Currently, none of those components actually set rp_filter themselves, but instead rely on the kernel being configured with rp_filter=2 for `default` interfaces, so that when an interface is created, it automatically has rp_filter=2. The correct fix is probably to remove that from the default setting and have each component be responsible for setting rp_filter on the interface it just created.

However, it is highly unlikely we will have this implemented across all components in time for the DC/OS 1.8 release, or at all for that matter, as the DC/OS team is not interested in implementing it themselves, for the following reason:

In order for a container to spoof its IP, it would need to be run in privileged mode so that it can open a raw socket with CAP_NET_ADMIN and CAP_SYS_ADMIN. Then, if rp_filter was disabled, it would be able to spoof traffic. But arguably, a container with the privileged access to do this can do much worse than just spoofing traffic. So having rp_filter set to prevent traffic spoofing would be the least of your worries.

Though we can (and probably will) make this change across the necessary DC/OS components, we should assume we won't be able to complete it all in time for 1.8, and should instead allow Calico to run with loose rp_filter.  Additionally, I don't believe we need to go so far as to implement the rp_filter checks in a dedicated iptables match rule. Instead, we should do the necessary work to fix DC/OS before we add unnecessary features to felix.

@caseydavenport and @matthewdupre have agreed with this plan. @fasaxc does it sound agreeable to you?

**Comment by fasaxc** [comment]
If we're sure that containers can't spoof anyway then I'm happy to make the check configurable.

That said, the [manpage for raw sockets](http://man7.org/linux/man-pages/man7/raw.7.html) says you only need `CAP_NET_RAW`, which is a lot narrower than than `CAP_NET_ADMIN` and `CAP_SYS_ADMIN`.  Does that change the calculation?  I'm struggling to think of a reason to have `CAP_NET_RAW` if you're only sending form your own IP but maybe those exist; is there a good place to warn people not to give `CAP_NET_RAW`to a container if you don't want it to spoof?

**Comment by djosborne** [comment]
@fasaxc I was under the impression that Docker privileges were all or nothing, i.e. you gave a container full root access (`--privileged`), or you didn't.

But seems you can quite easily add a single privilege with `docker run --cap-add=NET_RAW`. I fear that there may be scenarios where users could have some reason to grant `NET_RAW` to a container, which would open them up to a spoof attack if rp_filter=loose.

Seems my original point that "If your container can open up a socket it, it must be root, and can do much worse than spoof traffic" is no longer true - you **can** only have permission to open NET_RAW without having full root access, and its quite easy to do this.

That being said, I think we still want this to be configurable as you've implemented - otherwise we're still incompatible with DC/OS 1.8, which looks bad on us. So we should definitely give proper warning to anyone who tampers with this setting, and anyone in DC/OS.

I've raised [#19](https://github.com/projectcalico/calico-dcos/issues/19) to ensure we warn this to users of Calico in DC/OS.

We could also improve the felix log to point out how easy it is to grant a container the ability to spoof its IP: `Should only be set to true if no workloads are run with CAP_NET_RAW. For docker, this means containers should not be run with the flag --cap-add=NET_RAW`.

**Comment by robbrockbank** [comment]
It is now possible to pass in a felix environment into the container to disable this check.  This is in the latest node image (0.21.0)

**Comment by robbrockbank** [comment]
@djosborne Dan - can we close this?

**Comment by djosborne** [comment]
There's still one piece of this left open - If `rp_filter=loose`, calicoctl node won't mention any failures, and felix will just continuously stack trace and restart once a container is launched. I think it'd be best to open a seperate issue at this point, as this one has been more of a diagnostic tracker.

**Comment by davison** [comment]
We just came across this and although I read most of the comments here, I missed the final one above :(

I'd just opened https://github.com/projectcalico/felix/issues/1190 for our problem as I thought from the discussion here that this issue wouldn't cause felix to restart.

I've worked around it by doing the following for now:
```
docker stop calico-node
sysctl -w net.ipv4.conf.all.rp_filter=0
docker start calico-node
sysctl -w net.ipv4.conf.all.rp_filter=2
```

this appears to allow felix to start and continue working after setting the value back to 2.

**Comment by djosborne** [comment]
@davison A configuration setting for Felix was added to degrade the error to just a warning, so that Felix and calico-node will function properly even when `rp_filter == loose`.

Instead of flipping rp_filter, set [IgnoreLooseRPF](https://github.com/projectcalico/felix/blob/ab8799eaea66627e5db7717e62fca61fd9c08646/python/calico/felix/config.py#L198) to True.

**Comment by davison** [comment]
@djosborne thanks, I'd seen that code diff but didn't realise it was already released tbh.  Took me a while to work out the actual name of the environment variable that should be used to add this to my docker strap, but I have it working now :)

**Comment by matthewdupre** [comment]
@djosborne is there anything we can do to the Mesos docs to tell people to set this option?

**Comment by djosborne** [comment]
Good call. Raised #278
