### ISSUE TITLE
Calico-Mesos-Docker guide should detail launching tasks for Marathon <v1.2.0

### ISSUE THREAD

**Issue by evilabandon** [projectcalico/calico-containers#1091]
hi,when i follow this link
https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/UsageGuideDockerContainerizer.md

the marathon give me {"message":"Invalid JSON","details":[{"path":"/container/docker/network","errors":["USER is not a valid network type"]}]} 
the marathon version is Name        : marathon
Version     : 1.1.2
Release     : 1.0.488.el7
Architecture: x86_64
Install Date: Tue 02 Aug 2016 03:04:27 PM CST
Group       : default
Size        : 74485386
License     : Apache-2.0
Signature   : RSA/SHA1, Fri 29 Jul 2016 09:55:06 PM CST, Key ID df7d54cbe56151bf
Source RPM  : marathon-1.1.2-1.0.488.el7.src.rpm
Build Date  : Fri 29 Jul 2016 09:53:40 PM CST
Build Host  : ip-172-27-31-77.ec2.internal
Relocations : / 
Packager    : Mesosphere Package Builder <support@mesosphere.io>
Vendor      : Mesosphere, Inc.
URL         : https://github.com/mesosphere/marathon
Summary     : Cluster-wide init and control system for services running on Apache Mesos
Description :
Cluster-wide init and control system for services running on Apache Mesos

**Comment by fasaxc** [comment]
One for @djosborne?

**Comment by djosborne** [comment]
Whoops! The instructions you followed are for Marathon v1.2.0+. That version of Marathon now supports the "USER" type for networks.

If you're on <1.2.0, you can still specify a network type. [this older version of that doc shows how](https://github.com/projectcalico/calico-containers/blob/e249061188ed35d04b7d1ccd839ed920c7e81c4a/docs/mesos/UsageGuideDockerContainerizer.md#launching-a-container-with-a-json-blob). 

I'll update this issue to make sure we explain that in our master docs, as it is easy for users to hit this.

**Comment by djosborne** [comment]
@evilabandon If this doesn't fix your original issue please reopen!
