### ISSUE TITLE
How calico work across K8S nodes isolated by physical firewall?

### ISSUE THREAD

**Issue by shouhong** [projectcalico/calico-containers#1092]
I want to deploy K8S+Calico to a group of machines which are isolated by physical firewall. What ports should I request the firewall team to open, so the pods on these K8S nodes can communicate with each other?

**Comment by fasaxc** [comment]
@shouhong that is dynamic and it depends on the particular pods that are running at any instant.  Calico implements a dynamic firewall, which adjusts to the currently active pods.  To my knowledge, there's no way to do that with a traditional firewall.  Your firewall team would have to open up every port that your pods could possible use.
