### ISSUE TITLE
Odd message about calico-node.service when running calicoctl node stop

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#1098]
calico@calico:~/code/calico-containers$ sudo dist/calicoctl node stop
Failed to stop calico-node.service: Unit calico-node.service not loaded.
Node stopped

**Comment by robbrockbank** [comment]
Running with current master

**Comment by matthewdupre** [comment]
Yet another "detect where/how Calico is running" problem.

**Comment by gunjan5** [comment]
@robbrockbank do you think we need to add a `calicoctl node stop` for Go calicoctl 2.0? 
CC @caseydavenport

**Comment by robbrockbank** [comment]
Not for 1.0.0

We do print the "stop" command for docker when running in an init system.  We probably just want to always print out the stop command.  And then we also need to consider different run times.
