### ISSUE TITLE
[DOC] Kubernetes 1.3.5 requires cni default plugins to be installed

### ISSUE THREAD

**Issue by hanikesn** [projectcalico/calico-containers#1115]
See https://github.com/kubernetes/kubernetes/issues/30681

The following documentation should be updated:
https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu-calico.md

The default plugins from https://github.com/containernetworking/cni/releases should be installed into /opt/cni/bin to fix the issue.

**Comment by ae6rt** [comment]
As a Calico CNI user, I don't understand the impact of this issue on me.  If I have installed the Calico CNI plugin before I start the k8s control plane, do I need to do more?

**Comment by caseydavenport** [comment]
Bah, that's annoying.

@ae6rt the impact here is that in addition to the Calico / IPAM CNI plugins, you'll need to install the `loopback` plugin from upstream CNI.

I don't think the `KubernetesIntegration.md` needs to be updated for this - If I understand correctly, it's a new Kubernetes requirement not a Calico requirement.

However, our guides that actually install Kubernetes should be updated to include the new binaries.

**Comment by caseydavenport** [comment]
The latest getting started guides install the upstream CNI plugins.
