### ISSUE TITLE
/etc/rc.local for the calico-node container has a sed bug

### ISSUE THREAD

**Issue by ae6rt** [projectcalico/calico-containers#1118]
This line 

```
    ETCD_ENDPOINTS_CONFD=`echo "-node=$ETCD_NODE" | sed -e 's/,/ -node=/'`
```
in https://github.com/projectcalico/calico-containers/blob/master/calico_node/filesystem/etc/rc.local#L34

should read

```
ETCD_ENDPOINTS_CONFD=`echo "-node=$ETCD_NODE" | sed -e 's/,/ -node=/g'`
```

so that the substitution works for more than two etcd nodes.

**Comment by caseydavenport** [comment]
I've got a patch for this here: https://github.com/projectcalico/calico-containers/pull/1119/files
