### ISSUE TITLE
How to configure calico to use a different subnet other than 192.168.0.0/16?

### ISSUE THREAD

**Issue by shouhong** [projectcalico/calico-containers#1128]
By default calico use 192.168.0.0/16 subnet to assign IPs to K8S Pods. How to configure it to use a customized subnet for a K8S cluster?

**Comment by ae6rt** [comment]
Like this 

```
$ sudo ETCD_CA_CERT_FILE=/etc/ssl/certs/cacert.pem ETCD_ENDPOINTS=https://etcd01:2379,https://etcd02:2379,https://etcd03:2379 /opt/xoom/apps/calico/bin/calicoctl pool remove 192.168.0.0/16
$ sudo ETCD_CA_CERT_FILE=/etc/ssl/certs/cacert.pem ETCD_ENDPOINTS=https://etcd01:2379,https://etcd02:2379,https://etcd03:2379 /opt/xoom/apps/calico/bin/calicoctl pool add 10.131.0.0/16 --nat-outgoing
```

Depending on your server side networking, you may not need the *--nat-outgoing*.

**Comment by shouhong** [comment]
@ae6rt Thanks! After this change the new created Pods will get the IP in the new subnet. But I already have some pods been assigned 192.168.X.X IPs. How to make this change update the existing Pod's IP addresses immediately?

**Comment by caseydavenport** [comment]
@shouhong - you need to delete and re-recreate those pods via kubernetes.  Currently, there is no mechanism to re-assign a new IP address to an existing pod.

The recommended way of configuring a different default pool is to do as @ae6rt said above _before_ starting any `calico/node` containers. Then, make sure you start `calico/node` with `NO_DEFAULT_POOLS=true` to prevent it from trying to create the `192.168.0.0/16` pool.
