### ISSUE TITLE
Unable to get Calico to assign IPs to Kubernetes pods

### ISSUE THREAD

**Issue by highlyunavailable** [projectcalico/calico-containers#1132]
I'm not quite sure what I'm doing wrong but I'm following along [the docs](http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/) of how to set up a "bare metal" (it's actually 9 Vagrant VMs on a local box) Kubernetes/Calico cluster and I'm unable to get Calico to assign an IP to a pod, but only on the Kubernetes side.

If I set kubelet to use `--network-provider=kubenet` I get this and dashboard works:

```
root@kubemaster0:/home/ubuntu# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP           NODE
default       busybox                                 1/1       Running   3          5h        <none>       kubeworker1
kube-system   calico-policy-controller-dg9nb          1/1       Running   1          34m       10.3.0.32    kubeworker2
kube-system   kubernetes-dashboard-3726078781-29oij   1/1       Running   0          4m        10.200.2.3   kubeworker1
```

If I set it to use `--network-provider=cni` and the calico.conf file in /etc/cni/net.d, an IP is not assigned to the pod but an endpoint is successfully created on the calico side:

```
root@kubemaster0:/home/ubuntu# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP          NODE
default       busybox                                 1/1       Running   3          5h        <none>      kubeworker1
kube-system   calico-policy-controller-dg9nb          1/1       Running   1          35m       10.3.0.32   kubeworker2
kube-system   kubernetes-dashboard-3726078781-jrykk   1/1       Running   0          6s        <none>      kubeworker1
```

`calicoctl status` reports everything is up:

```
root@kubemaster0:/home/ubuntu# calicoctl  status
calico-node container is running. Status: Up About an hour
Running felix version 1.4.0

IPv4 BGP status
IP: 10.3.0.20    AS Number: 64511 (inherited)
+--------------+-------------------+-------+----------+-------------+
| Peer address |     Peer type     | State |  Since   |     Info    |
+--------------+-------------------+-------+----------+-------------+
|  10.3.0.21   | node-to-node mesh |   up  | 06:18:12 | Established |
|  10.3.0.22   | node-to-node mesh |   up  | 06:18:12 | Established |
|  10.3.0.30   | node-to-node mesh |   up  | 07:38:03 | Established |
|  10.3.0.31   | node-to-node mesh |   up  | 07:46:54 | Established |
|  10.3.0.32   | node-to-node mesh |   up  | 07:46:34 | Established |
+--------------+-------------------+-------+----------+-------------+
```

and `calicoctl endpoint show --detailed` shows an endpoint:

```
| kubeworker1 |       k8s       | kube-system.kubernetes-dashboard-3726078781-jrykk | 1dbe60586b6311e6b8ca02ac55035bcb |   10.200.2.3/24    | de:8c:13:c4:23:ce | k8s_ns.kube-system | active |
```

I can even access it across the network (I created a pool of 10.200.0.0/16 to match my --podCIDR option):

```
root@kubemaster0:/home/ubuntu# curl http://10.200.2.3:9090
 <!doctype html> <html ng-app="kubernetesDashboard"> 
```

However, the health check keeps failing and the container doesn't have an IP according to Kubernetes, so I can't use it. I'm sure I'm missing something but I'm not sure where to start troubleshooting.

**Comment by highlyunavailable** [comment]
This was caused by setting the CNI_IFNAMES variable to something other than `eth0`.

**Comment by caseydavenport** [comment]
@highlyunavailable - How were you setting the CNI_IFNAME variable to something other than eth0?    Is there a reason you'd like to be able to do this (I think it's just a limitation in k8s right now, but correct me if I'm wrong)

**Comment by highlyunavailable** [comment]
I don't _need_ this to be anything other than eth0 but I was setting it to `enp0s8` match the host's interface on the mistaken reading of the docs that that variable controlled which interface CNI bound the container to, not the name of the container's internal interface.

It is indeed a limitation of k8s.

How was just passing it as an environment variable as part of the Kubelet's env variables (since the CNI plugin runs as a child of Kubelet and inherits its Environment) with `Environment=CNI_IFNAME=enp0s8`.
