### ISSUE TITLE
libnetwork doesn't simply invalidate cache of libcalico

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-containers#1143]
The calico-libnetwork build [installs the libcalico code on one line of the Dockerfile](https://github.com/projectcalico/libnetwork-plugin/blob/master/Dockerfile#L21), then adds the libnetwork source code on another. Since the first step is cached, it can be easy for a user to build an image of libnetwork that relies on new libcalico, but is built with an older cached version.

Consider the following:

```
git clone https://github.com/projectcalico/libnetwork-plugin.git -b v0.8.0
cd calico-libnetwork
make image
# Assume some time goes by between the last step and the next step, and changes have been made to upstream libcalico
git checkout v0.9.0
make image
```

This will produce a broken libnetwork image which relies on new libcalico functions that it doesn't have.

We should modify the build procedure to use the Docker `ADD` step, allowing Docker to download libcalico's source, and invalidate the cache if it notices changes.

**Comment by caseydavenport** [comment]
I don't think this is relevant anymore since the Go rewrite? But correct me if I'm wrong.
