### ISSUE TITLE
Fail to use calico in docker

### ISSUE THREAD

**Issue by kongbo1987** [projectcalico/calico-containers#1147]
Hi:

I create the docker network via such command:

docker network create --driver calico --ipam-driver calico net1

However, it caught error response as below:
Error response from daemon: failed to update store for object type *libnetwork.network: client: etcd cluster is unavailable or misconfigured

How can I do with it, thanks.

 docker 1.12 
 calico/node-libnetwork:latest 
 calico/node:latest
 calicoctl  0.22.0-dev

**Comment by erandu** [comment]
Hi,
It seems that you have a problem with etcd. Do you have configured etcd ?
Calico needs an external key/value cluster such as etcd to store data.

**Comment by kongbo1987** [comment]
Yes I  have configured a etcd cluster,  and it seems good for Calico if I use command
calicoctl pool add 192.168.0.0/16 
But not work with docker as a cluster store when use 
docker network create --driver calico --ipam-driver calico net1

**Comment by kongbo1987** [comment]
solved after  right config docker

**Comment by matthewdupre** [comment]
Glad you got it working @kongbo1987 :).

For anyone else reading this, I believe this is caused by the cluster-store option for the docker daemon not being set (properly).  (Please let us know if it was something else.)
