### ISSUE TITLE
How can I integrate calico with mesos?

### ISSUE THREAD

**Issue by kongbo1987** [projectcalico/calico-containers#1152]
As calico can create a  profile by calicoctl and attach it to container,  how can I use this when I use mesos to create container?  This page https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/ManualInstallCalicoUnifiedContainerizer.md  has introduced net-modules, how it works, I am now confused.
Anyone give a help?

Thanks.

**Comment by djosborne** [comment]
Hi @kongbo1987 the [Calico Mesos Integration Information](https://github.com/projectcalico/calico-containers/tree/master/docs/mesos#calico-networking-for-mesos) page has information on how calico Integrates with Mesos.

Net-modules is a 3rd party networking module for Mesos that is now deprecated. Calico has a plugin which is no longer supported for net-modules. Instead, we recommend using the Calico-CNI plugin with Mesos CNI.

Does that information help?

**Comment by djosborne** [comment]
@kongbo1987 I haven't heard back from you so I am going to close this issue. Reopen or [contact us on slack](https://slack.projectcalico.org/) if you need more assistance.
