### ISSUE TITLE
Include libnetwork to calico/node container

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico-containers#1154]
- [ ] make libnetwork-plugin pip install-able
- [ ] check if `--libnetwork` flag is passed (for backwards compatiblity) 
- [ ] check for `CALICO_LIBNETWORK_ENABLED` env var

**Comment by tomdee** [comment]
Are we sure that we need to check the `--libnetwork` flag at all?
Isn't `CALICO_LIBNETWORK_ENABLED` an environment variable?

**Comment by gunjan5** [comment]
@tomdee yes, `CALICO_LIBNETWORK_ENABLED` is env var, fixed the description

For checking the `--libnetwork`, do we honor the flag or keep it for backwards compatibility but ignore it? CC @robbrockbank

**Comment by matthewdupre** [comment]
Duplicate of #1003

**Comment by gunjan5** [comment]
Fix in #1180
