### ISSUE TITLE
Makefile target 'setup-env' fails 

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico-containers#1156]
The build process explained in `docs/Building.md` doesn't work anymore because the `requirements.txt` doesn't exist in `calicoctl/` anymore.

https://github.com/projectcalico/calico-containers/blob/master/docs/Building.md#virtual-environment-build

```bash
venv/bin/pip install --upgrade -r calicoctl/requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'calicoctl/requirements.txt'
```

If the process has changed then we need to change `Makefile` and `docs/Building.md`

**Comment by tomdee** [comment]
Fixed by #1197
