### ISSUE TITLE
The cni 1.4.1 download binary is from something old, please check and fix it.

### ISSUE THREAD

**Issue by tizhou86** [projectcalico/calico-containers#1166]
Hi the cni download version for 1.4.1 is broken, it's actually built from some 1.3.0+ version, since I can see the debug logs before 1.4.0, like "Querying Kubernetes API for Pod"... it takes me a day to figure it out, please fix it:-)

**Comment by tizhou86** [comment]
Sorry, leave it to calico-cni project.

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/calico-cni/issues/181
