### ISSUE TITLE
calicoctl node restarts the container even when running via systemd

### ISSUE THREAD

**Issue by klynch** [projectcalico/calico-containers#1167]
I have configured calico using the `cailco-node.service` configuration outlined in the [Kubernetes Integration](https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md) docs. However, everytime I run `calicoctl node` the container is restarted.

This issue appears similar to #1098 in that calicoctl should detect how it is started and not attempt to override the control of the process.

**Comment by matthewdupre** [comment]
Why do you need to run `calicoctl node` when there's a systemd unit managing it?

I don't see how calicoctl could skip this step anyway (given the systemd unit itself calls `calicoctl node`).

**Comment by klynch** [comment]
The problem is a usability issue. `calicoctl node` has many sub commands for information gathering and other actions. An administrator will assume that the raw `node` command will display information or present the valid subcommands since many other programs behave that way.

Since my `calico-node` container is configured in the systemd unit file with a specific BGP AS number corresponding to the appropriate top of rack, running `calico node` will unintentionally restart the container with the defaults.

I propose that to maintain bacwards compatibility, `calicoctl node` can check for a container and start it if it is not present, but on subsequent runs `calicoctl node start --force` should start the command.

**Comment by matthewdupre** [comment]
Ahh, I understand.

We've got a substantial rewrite of calicoctl in progress, which won't behave like this (our current plan is to not do any docker running, instead having commands that produce a systemd unit or `docker run` line).

I expect we'll switch over in the next month or two.

**Comment by klynch** [comment]
Will this rewrite be available in a branch anytime soon?

**Comment by caseydavenport** [comment]
> calicoctl node has many sub commands for information gathering and other actions

Yep, the new calicoctl node command will just print help text.. there's a calicoctl node run command for that now.  It also produces the correct docker run cmds for you.

The code has been released as a beta and will be GA very soon.
