### ISSUE TITLE
SSL error on calico-policy when not using default domain

### ISSUE THREAD

**Issue by TaiSHiNet** [projectcalico/calico-containers#1168]
If K8S_API URL is not changed and your API certificates do not have 'kubernetes.default' SAN, calico-policy will fail (although it wont restart).
Out of this there are a few things to note:
- calico-policy-controller is not 'health checked'
- SSL could be disabled (or not)
- Update documentation to note that K8S_API should be set to a proper value

Describe pod calico-policy-controller:
```
Conditions:
  Type		Status
  Initialized 	True
  Ready 	True
  PodScheduled 	True
```

Related config:
```
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://kubernetes.default:443"
            # Since we're running in the host namespace and might not have KubeDNS
            # access, configure the container's /etc/hosts to resolve
            # kubernetes.default to the correct service clusterIP.
```

Related error:
```
2016-09-26 17:21:39,326 5 ERROR Connection error querying: NetworkPolicy
Traceback (most recent call last):
  File "<string>", line 295, in _manage_resource
  File "<string>", line 381, in _sync_resources
  File "<string>", line 433, in _api_get
  File "site-packages/requests/sessions.py", line 480, in get
  File "site-packages/requests/sessions.py", line 468, in request
  File "site-packages/requests/sessions.py", line 576, in send
  File "site-packages/requests/adapters.py", line 447, in send
SSLError: hostname 'kubernetes.default' doesn't match either of 'domain.used.in.ssl.cert'
2016-09-26 17:21:39,326 5 WARNING Re-starting watch on resource: NetworkPolicy
```

**Comment by caseydavenport** [comment]
Yes, this could certainly be documented better.  Basically, the policy controller uses a cert that is mounted into the Pod by the kubelet which expects `kubernetes.default`.

One option would be to document mounting of other API access certs into the container.

We could also add an option to disable SSL verification (which is done by default when the cert is present)

**Comment by TaiSHiNet** [comment]
I managed to get it working by explicitly specifying a CA file
```
"k8s_certificate_authority": "/etc/kubernetes/ssl/ca.crt"
```
But yes, usually clusters are not signed with a 'known' CA.
Feel free to close/rename at will

Bests

**Comment by caseydavenport** [comment]
> calico-policy-controller is not 'health checked'

This is probably a separate issue.  I've raised this guy: https://github.com/projectcalico/k8s-policy/issues/44
