### ISSUE TITLE
etcd_endpoints in calico-configmap.yaml

### ISSUE THREAD

**Issue by TaiSHiNet** [projectcalico/calico-containers#1169]
calico-configmap.yaml defaults etcd endpoints to 127.0.0.1, which will end up failing if there isn't a proxy running on every node.
Documentation could be updated to reflected this and/or only a 'master' node (running in the controller) could have interaction with etcd directly

**Comment by caseydavenport** [comment]
I believe the docs already cover this: https://github.com/projectcalico/calico-containers/tree/master/docs/cni/kubernetes/manifests#etcd_endpoints
