### ISSUE TITLE
How can I get a new calicoctl file

### ISSUE THREAD

**Issue by pandasumm** [projectcalico/calico-containers#1175]
Hi,
Because of the special network setting of my development environment, I've modified some files in
`calico-containers-master\calicoctl\calico_ctl` and
`libcalico-master\calico_containers\pycalico`.
I wonder if I can get a new  executable `calicoctl` to take place of the download file "http://www.projectcalico.org/builds/calicoctl".

 Or are there some related docs I can refer to?

thanks a lot

**Comment by matthewdupre** [comment]
From libcalico: `make build-container`
From calico-containers: `make binary`, and your binaries should be in dist/.

**Comment by matthewdupre** [comment]
Closing this for now: feel free to reopen or ask on Slack (slack.projectcalico.org) if you have any trouble.

**Comment by pandasumm** [comment]
thanks for help.
And sorry for responding so late. When you answered me, I'm during my holiday vacation.

Now I have a new question, I have edit some code in /calico (now it's called /felix). From my study, I need to build a new docker image called 'node', and 'felix' is running in this container. So I have read the dockerfile in /felix, if I just run the script 'docker_build_and_run.sh' in /felix, I will get a image called 'calico/felix', it seems different from the image 'node'.

so I'd like to know how can I use my edited code to build the image 'node'.
