### ISSUE TITLE
DefaultEndpointToHostAction option become overwritten after node rebooting

### ISSUE THREAD

**Issue by aleks-v-k** [projectcalico/calico-containers#1190]
I run calico-node in docker container via `calicoctl node --ip=node ip` and it turns out that etcd key `/calico/v1/host/<node hostname>/config/DefaultEndpointToHostAction` is set to 'RETURN'. If I change it to 'DROP' it works until rebooting the VM. After rebooting it is set to 'RETURN' again.
What is the reason for such behavior? In my opinion, the desirable way is to not overwrite the setting if it is already set.

**Comment by matthewdupre** [comment]
Quick question: is this OpenStack or containers?

**Comment by aleks-v-k** [comment]
@matthewdupre It is containers - kubernetes.

**Comment by aleks-v-k** [comment]
@matthewdupre Thanks!
