### ISSUE TITLE
Automatically get the injected Service Account token for Kubernetes

### ISSUE THREAD

**Issue by micahhausler** [projectcalico/calico-containers#1191]
Currently to use with Kubernetes, [you have to specify a `k8s_auth_token`,](https://github.com/projectcalico/calico-containers/blob/698d55bfdb891db18be1c6ec3a3aa8bcf1b37bd3/docs/cni/kubernetes/manifests/README.md) but Kubernetes injects a token at [`/var/run/secrets/kubernetes.io/serviceaccount/token`](http://kubernetes.io/docs/user-guide/service-accounts/)

It would help a lot in terms of automation for calico to read the token from that file location

**Comment by caseydavenport** [comment]
@micahhausler The latest `calico/cni` container actually does do this if you're using it with a self-hosted installation.

See here: https://github.com/projectcalico/calico-containers/tree/master/docs/cni/kubernetes/manifests#cni_network_config

Are you thinking of this in another context?

Also note that k8s_auth_token isn't required - you can also use certificate based API authentication.

**Comment by micahhausler** [comment]
I thought that `__SERVICEACCOUNT_TOKEN__` was a placeholder for the operator to fill in, I didn't realize that there was a script `sed`ing a replacement for `__SERVICEACCOUNT_TOKEN__`
