### ISSUE TITLE
Cannot remove dead node from k8s cluster

### ISSUE THREAD

**Issue by micahhausler** [projectcalico/calico-containers#1194]
I'm running calico on a kubernetes cluster, and noticed that there are multiple dead nodes listed when I run `calicoctl status`:

```
$ sudo calicoctl status
calico-node container is running. Status: Up 38 minutes
Running felix version 1.4.0

IPv4 BGP status
IP: 172.31.46.76    AS Number: 64511 (inherited)
+---------------+-------------------+-------+----------+-------------------------------------------+
|  Peer address |     Peer type     | State |  Since   |                    Info                   |
+---------------+-------------------+-------+----------+-------------------------------------------+
| 172.31.13.217 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
|  172.31.13.78 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
| 172.31.14.231 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
|  172.31.18.68 | node-to-node mesh |   up  | 20:51:02 |                Established                |
| 172.31.24.159 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
| 172.31.25.219 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
|  172.31.26.3  | node-to-node mesh | start | 20:50:58 |                  Connect                  |
| 172.31.27.109 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
|  172.31.31.58 | node-to-node mesh |   up  | 20:51:01 |                Established                |
| 172.31.34.168 | node-to-node mesh | start | 20:50:58 | Active        Socket: Host is unreachable |
| 172.31.36.143 | node-to-node mesh | start | 20:50:58 | Active        Socket: Host is unreachable |
|  172.31.38.22 | node-to-node mesh |   up  | 20:51:02 |                Established                |
|  172.31.4.85  | node-to-node mesh |   up  | 20:51:01 |                Established                |
| 172.31.40.104 | node-to-node mesh | start | 20:50:58 | Active        Socket: Host is unreachable |
|  172.31.41.48 | node-to-node mesh | start | 20:50:58 | Active        Socket: Host is unreachable |
|  172.31.6.63  | node-to-node mesh |   up  | 20:51:01 |                Established                |
|  172.31.8.232 | node-to-node mesh | start | 20:50:58 |                  Connect                  |
+---------------+-------------------+-------+----------+-------------------------------------------+

IPv6 BGP status
No IPv6 address configured.
```

When I go to remove the dead nodes (any without the INFO of "Established"), I get the error

```
$ calicoctl node remove --hostname ip-172-31-8-232.us-west-2.compute.internal
KeyError: 'affinity'

Traceback (most recent call last):
  File "<string>", line 144, in <module>
  File "calico_ctl/node.py", line 190, in node
  File "calico_ctl/node.py", line 669, in node_remove
  File "site-packages/pycalico/datastore.py", line 130, in wrapped
  File "site-packages/pycalico/ipam.py", line 1308, in remove_ipam_host
  File "site-packages/pycalico/datastore.py", line 130, in wrapped
  File "site-packages/pycalico/ipam.py", line 1262, in release_host_affinities
  File "site-packages/pycalico/ipam.py", line 264, in _release_block_affinity
  File "site-packages/pycalico/ipam.py", line 74, in _read_block
  File "site-packages/pycalico/block.py", line 150, in from_etcd_result
KeyError: 'affinity'
```

**Comment by micahhausler** [comment]
As a workaround, I removed all the dead hosts records from `/calico/ipam/v2/host/{host}` in etcd, and then had no problem deleting each node with `calicoctl node remove --hostname {host}`

**Comment by matthewdupre** [comment]
Were there any containers left on those nodes?

**Comment by micahhausler** [comment]
They had running containers when they were killed off

**Comment by caseydavenport** [comment]
@micahhausler what version of the CNI plugin were you running?

A quick investigation leads me to believe that the v1.4.x CNI IPAM plugin, which uses Go libcalico is writing data to etcd in a way that the python libcalico doesn't like.

Specifically, the two representations of an allocation block seem to differ:

Python: https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/block.py#L150
Go: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/model/block.go#L84

I think this is a fairly crass Go libcalico bug, so I've raised this over there:

**Comment by caseydavenport** [comment]
I will continue discussion of a fix in projectcalico/libcalico-go#226.

For now, your workaround involving the deletion of the block allocations for the host before `calicoctl node remove` should work.  Once the above issue is fixed and propagated to a CNI release, then you won't have to manually remove the block allocations anymore and `calicoctl node remove` should just work.

**Comment by caseydavenport** [comment]
This should be addressed in the v1.0.0-beta version of `calicoctl`, which now attempts to respect both representations of affinity (though prefers the `affinity: host=blah` form).

@CaoShuFeng has a PR up for the Python library. https://github.com/projectcalico/libcalico/pull/166

**Comment by gunjan5** [comment]
@caseydavenport small correction, it's `affinity: host:blah` where `host:blah` is the value

**Comment by caseydavenport** [comment]
@micahhausler this should work in the v1.0.0-beta release.  

LMK if you get a chance to try it out with the new version.

**Comment by caseydavenport** [comment]
Closing. Let me know if this actually isn't fixed.
