### ISSUE TITLE
Calico with docker : can not ping from one container to other container in diffenrent host but same net.

### ISSUE THREAD

**Issue by ZhenyangZhao** [projectcalico/calico-containers#1205]
There are my environment
docker: 1.12.1
calicoctl: 0.21.0
calico/node:v0.21.0
calico/node-libnetwork:v0.9.0

I do according to the document : http://docs.projectcalico.org/master/getting-started/docker/tutorials/basic but it doesn't works.

i use calico ipam driver in none cloud env.

when i check this i found it doesn't work.

```
workload-A in calico01 & net1
workload-E in calico02 & net1

docker exec workload-A ping -c 4 workload-E.net1
```

![image](https://cloud.githubusercontent.com/assets/7477708/19237681/c0ef70dc-8f30-11e6-8c28-21bca2a84fb1.png)

route on calico01
![image](https://cloud.githubusercontent.com/assets/7477708/19238093/7408b1c8-8f32-11e6-95cf-a599cf845a46.png)

route on clico02
![image](https://cloud.githubusercontent.com/assets/7477708/19238099/7f13c47c-8f32-11e6-9240-9510df672a40.png)

**Comment by matthewdupre** [comment]
Could you please test between two containers on the same host?
- If that doesn't work, please could you attach the diagnostics (`calicoctl diags`)
- If it does it's possible that the switch is dropping the packets: could you run a `tcpdump -i eth0 -vvv icmp` on both hosts while trying the ping to confirm if this is happening.  If they are being dropped in transit (packets appear on the source but not the destination), then you'll need to either reconfigure the switch, or use IPIP.

One other thing is you should (maybe later) reconfigure the Calico pool to not overlap with your physical hosts.  In this case, it will not be causing the above problem, but there's a chance that the 192.168.0.0/24 block gets reused for Calico containers as it stands.  `calicoctl pool remove 192.168.0.0/16 && calicoctl pool add <something else>` should do it.

**Comment by ZhenyangZhao** [comment]
@matthewdupre  I will try it as you say. Thanks a lot.

**Comment by ZhenyangZhao** [comment]
@matthewdupre 
i try to ping two containers on the same host.it works.
i run the command calicoctl pool remove 192.168.0.0/16 && calicoctl pool add 172.18.0.0/16
it can not ping from one container to other container in diffenrent host but same net
i chanage to mode ipip nat-outgoing also can not ping too.

my host is openstack vm(ovs network)

this is i use ipip & nat-outgoing
docker exec workload-A ping -c 4 workload-E.net1

![image](https://cloud.githubusercontent.com/assets/7477708/19382327/468c0bb6-9232-11e6-8953-c710d9274524.png)

![image](https://cloud.githubusercontent.com/assets/7477708/19382297/27352810-9232-11e6-91e2-1b3d6b99808f.png)

**Comment by zouyee** [comment]
@ZhenyangZhao  how to resolve this problem?tahnk you for your response!

**Comment by ZhenyangZhao** [comment]
@zouyee i'm not resolve this problem, if i have any idea i will notify you.
@matthewdupre  
my environment is : using docker in openstack vxlan network.
act1: use local Oracle vBox running with docker & calico, the container can ping other container in different host.
act2: same configuration using docker&calico in openstack vxlan network not works. calicoctl status shows everything ok(established)

**Comment by ZhenyangZhao** [comment]
@zouyee i resolve this promblem by using ipip and natoutgoing
`calicoctl pool add 192.168.10.192/26 --ipip --nat-outgoing` 
@matthewdupre  thanks for help.my mistake.:)
