### ISSUE TITLE
Docs skip the fact that kubeconfig is required

### ISSUE THREAD

**Issue by bobrik** [projectcalico/calico-containers#1212]
- http://docs.projectcalico.org/v1.5/getting-started/kubernetes/installation/

```
mkdir -p /etc/cni/net.d
cat >/etc/cni/net.d/10-calico.conf <<EOF
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "http://<ETCD_IP>:<ETCD_PORT>",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
        "type": "k8s"
    }
}
EOF
```

This fails because there is no `kubernetes` key here, error coming out of calico cni:

``` json
{
    "code": 100,
    "msg": "invalid configuration: no configuration has been provided"
}
```

`calico/cni` repo mentions the key:
- https://github.com/projectcalico/calico-cni/blob/master/configuration.md#kubernetes-specific

It's also not very clear from the error what kind of config is required.

**Comment by caseydavenport** [comment]
I think this changed in v1.4, as there are no longer default values for `k8s_api_root`, etc.

**Comment by opskumu** [comment]
@caseydavenport Thanks, if the CNI plugin v1.4.0`+`, CNI Configuration must add `k8s_api_root` option, otherwise kubelet error:

```
E1108 15:46:09.966758    8232 cni.go:255] Error adding network: invalid configuration: no configuration has been provided
E1108 15:46:09.966796    8232 cni.go:209] Error while adding to cni network: invalid configuration: no configuration has been provided
```

cni configuration like:

```
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "http://192.168.0.10:4001,http://192.168.0.11:4001,http://192.168.0.12:4001",
    "log_level": "info",
    "kubernetes": {
        "k8s_api_root": "http://192.168.0.10:8080"
    },
    "ipam": {
        "type": "calico-ipam"
    }
}
```

**Comment by caseydavenport** [comment]
This doc indicates the need to specify k8s API access details: http://docs.projectcalico.org/v2.0/reference/cni-plugin/configuration#kubernetes-specific
