### ISSUE TITLE
Can't ping pod IP from node with --register-schedulable=false

### ISSUE THREAD

**Issue by dkoshkin** [projectcalico/calico-containers#1220]
Versions:
- calico-node - `v0.22`
- calico-cni - `v1.4.2`
- k8s - `v1.4.0`
- etcd - `v2.3.7`

Centos7 on packet.net

```
#conf file
{
    "name": "calico-k8s-network",
    "type": "calico",
    "etcd_endpoints": "{{ etcd_networking_cluster_ip_list }}",
    "etcd_cert_file": "{{ kubernetes_certificates_cert_path }}",
    "etcd_key_file": "{{ kubernetes_certificates_key_path }}",
    "etcd_ca_cert_file": "{{ kubernetes_certificates_ca_path }}",
    "kubernetes": {
      "kubeconfig": "{{ kubernetes_kubeconfig_path }}"
    },
    "ipam": {
      "type": "calico-ipam",
      "subnet": "usePodCidr"
    },
    "log_level": "info"
}
```

```
#commands to start calico
calicoctl node --ip=${INTERNAL_IP} 
calicoctl pool add ${PODS_CIDR} --nat-outgoing --ipip
calicoctl pool add ${SERVICE_CIDR} --nat-outgoing --ipip
```

```
$ calicoctl status
calico-node container is running. Status: Up 3 hours
Running felix version 1.4.0

IPv4 BGP status
IP: 10.99.224.137    AS Number: 64511 (inherited)
+---------------+-------------------+-------+----------+-------------+
|  Peer address |     Peer type     | State |  Since   |     Info    |
+---------------+-------------------+-------+----------+-------------+
| 10.99.224.135 | node-to-node mesh |   up  | 14:52:47 | Established |
| 10.99.224.131 | node-to-node mesh |   up  | 14:52:44 | Established |
| 10.99.224.129 | node-to-node mesh |   up  | 14:52:44 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 address configured.
```

```
$ calicoctl node show
+----------+---------------+-----------+-------------------+--------------+--------------+
| Hostname |   Bird IPv4   | Bird IPv6 |       AS Num      | BGP Peers v4 | BGP Peers v6 |
+----------+---------------+-----------+-------------------+--------------+--------------+
|  node01  | 10.99.224.137 |           | 64511 (inherited) |              |              |
|  node02  | 10.99.224.135 |           | 64511 (inherited) |              |              |
|  node03  | 10.99.224.131 |           | 64511 (inherited) |              |              |
|  node04  | 10.99.224.129 |           | 64511 (inherited) |              |              |
+----------+---------------+-----------+-------------------+--------------+--------------+
```
---

I have 4 nodes in the cluster
- 1 as a "master"(`node01`) : running kubelet with `--register-schedulable=false`, kube-proxy, kube-controller, kube-apiserver, and kube-scheduler, along with calico-node 
- 2nd as a "master" and a "worker"(`node02`) : running kubelet but with `--register-schedulable=true` , kube-proxy, kube-controller, kube-apiserver, and kube-scheduler, along with calico-node 
- and 2 other ones with just kubelet, kube-proxy and calico-node

I've deployed 3 Nginx pods (1 running on each "worker") and a busybox pod. All the nginx pod IPs are accessible from any of the worker nodes and the busybox pod, **but this does not work from the "master" node**

Running `kubectl uncordon $MASTER` and restarting calico-node fixes the issue, the pod IPs are resolvable from the master node.

I've tried debugging this and it looks like the firewall is not being configured properly with the master node.
- Master diags: https://transfer.sh/cVpsV/diags-181016-175111.tar.gz
- Worker diags: https://transfer.sh/DBLdd/diags-181016-175145.tar.gz
- Master diags after `kubectl uncordon` and restarting calico-node https://transfer.sh/HPvib/diags-181016-182811.tar.gz

This breaks `NodePort` in k8s when trying to access using the "master" IP

**Comment by dkoshkin** [comment]
New findings, looks like its unrelated to `--register-schedulable=false` and to Calico, looking at the `kube-proxy` logs of the broken node I see that the service is being restarted and there is an a message `missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended`
```
Oct 18 19:08:36 node1 systemd[1]: Stopped Kubernetes Proxy.
Oct 18 19:08:36 node1 systemd[1]: Started Kubernetes Proxy.
Oct 18 19:08:36 node1 systemd[1]: Starting Kubernetes Proxy...
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.514942    7584 server.go:156] setting OOM scores is unsupported in this build
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.520338    7584 server.go:203] Using iptables Proxier.
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.597334    7584 proxier.go:215] missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.597403    7584 server.go:215] Tearing down userspace rules.
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.598013    7584 healthcheck.go:119] Initializing kube-proxy health checker
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.618542    7584 conntrack.go:40] Setting nf_conntrack_max to 131072
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.619424    7584 conntrack.go:57] Setting conntrack hashsize to 32768
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.620960    7584 conntrack.go:62] Setting nf_conntrack_tcp_timeout_established to 86400
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.629218    7584 proxier.go:431] Adding new service "default/kubernetes:https" at 172.17.0.1:443/TCP
Oct 18 19:08:36 node1 kube-proxy[7584]: I1018 19:08:36.629639    7584 proxier.go:755] Not syncing iptables until Services and Endpoints have been received from master
Oct 18 19:08:39 node1 kube-proxy[7584]: I1018 19:08:39.782413    7584 proxier.go:431] Adding new service "kube-system/kubernetes-dashboard:" at 172.17.88.67:80/TCP
Oct 18 19:08:39 node1 kube-proxy[7584]: I1018 19:08:39.806523    7584 proxier.go:1318] Opened local port "nodePort for kube-system/kubernetes-dashboard:" (:32122/tcp)
Oct 18 19:08:42 node1 kube-proxy[7584]: I1018 19:08:42.363753    7584 proxier.go:431] Adding new service "kube-system/kube-dns:dns" at 172.17.0.2:53/UDP
Oct 18 19:08:42 node1 kube-proxy[7584]: I1018 19:08:42.363926    7584 proxier.go:431] Adding new service "kube-system/kube-dns:dns-tcp" at 172.17.0.2:53/TCP
Oct 18 19:09:20 node1 kube-proxy[7584]: I1018 19:09:20.044281    7584 proxier.go:431] Adding new service "default/my-nginx:" at 172.17.255.188:80/TCP
Oct 18 19:09:20 node1 kube-proxy[7584]: I1018 19:09:20.066986    7584 proxier.go:1318] Opened local port "nodePort for default/my-nginx:" (:30863/tcp)
``` 

Restarting the `kube-proxy` fixed the issue. Will post an update if I find anything about why this happens.

**Comment by caseydavenport** [comment]
> missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended

I think this is a red-herring.  When using Calico, that module isn't required. Calico doesn't use a bridge, and so all traffic is sent through iptables without that module installed.

I also noticed you're running `calicoctl pool add ${SERVICE_CIDR} --nat-outgoing --ipip`.  I can't say for sure if this is related to the issue you're seeing, but in general you shouldn't add the Service CIDR as a Calico pool.  Services are entirely handled by the kube-proxy, and I'm not sure what all of the consequences might be if Calico tried to own that pool.

I'll take a look at those diags bundles and see if I find anything out of the ordinary.

**Comment by dkoshkin** [comment]
My mistake I looked through the code again and we aren't actually doing `calicoctl pool add ${SERVICE_CIDR} --nat-outgoing --ipip`

**Comment by caseydavenport** [comment]
@dkoshkin any news on this? I'm inclined to close this as a kube-proxy issue, unless there is evidence pointing to Calico.

**Comment by dkoshkin** [comment]
I will report back if this is still happening with the newer versions of both calico and k8s.
