### ISSUE TITLE
All canal container  CrashLoopBackOff with default kubeadm initialize

### ISSUE THREAD

**Issue by kharisj** [projectcalico/calico-containers#1222]
I'm new for kubernetes and I choose canal for my kubernetes network.
I struck with this error for a week and I cannot bring kube-dns up. For more information I try to compare with weave network. in my kubernetes with weave was succesful and I hope canal will be more powerful than weave. error as following

```
[root@master ~]# kubectl get po --all-namespaces
NAMESPACE     NAME                                   READY     STATUS              RESTARTS   AGE
kube-system   calico-etcd-2r5k6                      0/1       CrashLoopBackOff    5          3m
kube-system   calico-node-nbad7                      1/2       Error               4          3m
kube-system   calico-node-sj2z5                      1/2       Error               2          3m
kube-system   calico-policy-controller-snp8a         0/1       CrashLoopBackOff    3          3m
kube-system   configure-calico-jqp0m                 0/1       CrashLoopBackOff    2          3m
kube-system   etcd-master.local                      1/1       Running             0          6m
kube-system   kube-apiserver-master.local            1/1       Running             0          6m
kube-system   kube-controller-manager-master.local   1/1       Running             0          8m
kube-system   kube-discovery-982812725-dhbby         1/1       Running             0          8m
kube-system   kube-dns-2247936740-89ob1              0/3       ContainerCreating   0          7m
kube-system   kube-proxy-amd64-ib9ct                 1/1       Running             0          7m
kube-system   kube-proxy-amd64-rn4r9                 1/1       Running             0          7m
kube-system   kube-scheduler-master.local            1/1       Running             0          7m
```

[canal.txt](https://github.com/projectcalico/calico-containers/files/538674/canal.txt)

**Comment by caseydavenport** [comment]
@kharisj It looks like etcd is failing to start, and is likely causing the other components to fail to start as well.

Could you take a look at the logs for the etcd pod and see why it is crashing?

**Comment by caseydavenport** [comment]
@kharisj were you able to get the etcd logs (e.g `kubectl logs calico-etcd-2r5k6 --namespace=kube-system`)?

**Comment by gunjan5** [comment]
@kharisj any update on this? Let us know if you are still seeing this issue

**Comment by Stealthii** [comment]
I reckon this might be a permissions error. Similar example:
```
[root@kubernetes1 ~]# kubectl logs calico-etcd-a0tn4 --namespace=kube-system
2016-11-24 16:38:22.222269 I | etcdmain: etcd Version: 2.2.1
2016-11-24 16:38:22.222313 I | etcdmain: Git SHA: 75f8282
2016-11-24 16:38:22.222320 I | etcdmain: Go Version: go1.5.1
2016-11-24 16:38:22.222325 I | etcdmain: Go OS/Arch: linux/amd64
2016-11-24 16:38:22.222331 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-11-24 16:38:22.222690 I | etcdmain: listening for peers on http://0.0.0.0:6667
2016-11-24 16:38:22.222769 I | etcdmain: listening for client requests on http://0.0.0.0:6666
2016-11-24 16:38:22.222879 I | etcdmain: stopping listening for client requests on http://0.0.0.0:6666
2016-11-24 16:38:22.222901 I | etcdmain: stopping listening for peers on http://0.0.0.0:6667
2016-11-24 16:38:22.222914 C | etcdmain: mkdir /var/etcd/calico-data: permission denied
```

**Comment by Stealthii** [comment]
Repeating these steps with SElinux rules properly set (or disabled completely) leads to better success. `configure-calico` still gets stuck in a crash loop, with the following:
```
[root@kubernetes1 ~]# kubectl logs configure-calico-msay9 --namespace=kube-system
Unknown command: "pool"
Usage:
  calicoctl [options] <command> [<args>...]
...etc, etc.
```

**Comment by Stealthii** [comment]
It seems the version of calicoctl image (v0.23.0) comes with version `v1.0.0-beta-13-g463cc95`, which no longer provides pool or other subcommands. Let me know if I should open a new issue on this, or if it's relevant to the same issue listed here.

**Comment by caseydavenport** [comment]
@Stealthii could you raise another issue? That's a pretty urgent bug.

**Comment by Stealthii** [comment]
calicoctl being a separate issue - @kharisj the likely issue here is a misconfigured SELinux environment. If you can't configure this correctly, follow instructions to disable SELinux on your host OS fully, and you should have no permission issues as expected from your example.

**Comment by xiaochunyn** [comment]
@kharisj Disabling SELinux by running "setenforce 0" is required in order to allow containers to access the host filesystem.
