### ISSUE TITLE
Unable to start calico/node services

### ISSUE THREAD

**Issue by onyxet** [projectcalico/calico-containers#1244]
Following this guide http://docs.projectcalico.org/v1.5/getting-started/kubernetes/installation/hosted/  I have next messages in calico/node log

> > rm: can't remove '/etc/service/bird/log': Directory not empty
> rm: can't remove '/etc/service/bird6/log': Directory not empty
> rm: can't remove '/etc/service/confd/log': Directory not empty
> rm: can't remove '/etc/service/felix/log': Directory not empty
> Calico node started successfully
> runsv felix: fatal: unable to start log/./run: file does not exist
> runsv bird6: fatal: unable to start log/./run: file does not exist
> runsv confd: fatal: unable to start log/./run: file does not exist

When I try reproduce this outside my k8s cluster - everything looks ok (I tried run only calico/node container with conf environments)
I saw similar issue 

> https://github.com/projectcalico/calico-containers/issues/1120

but how resolve this I don`t know.

My env is 

> Docker:
> Client:
>  Version:      1.12.3
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   6b644ec
>  Built:        
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.12.3
>  API version:  1.24
>  Go version:   go1.6.3
>  Git commit:   6b644ec
>  Built:        
>  OS/Arch:      linux/amd64
> 
> OS:
> Linux 3.10.0-327.36.3.el7.x86_64 x86_64
> 
> I tried run calico/node v0.22.0 and v0.23.0

And I have some issue, I cant ping containers on different hosts, as I understood this problem it`s because calico/node doesn`t work properly. Thanks for help
@caseydavenport

**Comment by matthewdupre** [comment]
Could you please try `docker exec -it calico-node /bin/sh`ing into the calico/node container, and then send us `ls -Ra` from /etc/service?

**Comment by onyxet** [comment]
Yes, here is

> / # ls -Ra /etc/service
> /etc/service:
> .      ..     bird   bird6  confd  felix
> 
> /etc/service/bird:
> .          ..         log        run        supervise
> 
> /etc/service/bird/log:
> ls: /etc/service/bird/log/run: No such file or directory
> .          ..         supervise
> 
> /etc/service/bird/log/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/bird/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/bird6:
> .          ..         log        run        supervise
> 
> /etc/service/bird6/log:
> ls: /etc/service/bird6/log/run: No such file or directory
> .          ..         supervise
> 
> /etc/service/bird6/log/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/bird6/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/confd:
> .          ..         log        run        supervise
> 
> /etc/service/confd/log:
> ls: /etc/service/confd/log/run: No such file or directory
> .          ..         supervise
> 
> /etc/service/confd/log/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/confd/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/felix:
> .          ..         log        run        supervise
> 
> /etc/service/felix/log:
> ls: /etc/service/felix/log/run: No such file or directory
> .          ..         supervise
> 
> /etc/service/felix/log/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
> /etc/service/felix/supervise:
> .        ..       control  lock     ok       pid      stat     status
> 
Actually I dont understand why I have this issue only at my master node now. k8s nodes has very similar conf with master. Thanks for help @matthewdupre

**Comment by onyxet** [comment]
I think I know where is my issue. On my master node I have overlay storage driver and when I changed it to devicemapper and repull image calico/node from my private registry bird and other services started properly. I need some time in docs about docker storage-drivers. Thanks for support

**Comment by chenzhiwei** [comment]
@onyxet Why closed this issue since calico/node can't work properly with overlayfs, I think it's a bug.

@matthewdupre What do you think?
