### ISSUE TITLE
--nat-outgoing doesn't work in my virtual machine environment

### ISSUE THREAD

**Issue by CaoShuFeng** [projectcalico/calico-containers#1249]
I take the following steps in my local virtual machine:
1. sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl  node
2. sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl  pool remove 192.168.0.0/16
3. sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl  pool add 172.168.0.0/16 --nat-outgoing
4. sudo docker run --net=none --name workload-A -tid busybox
5. sudo sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl container add workload-A 172.168.0.9
6. sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl profile add pf1
7. sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl container workload-A profile append pf1

When I use docker's own network, I can access the internet. But I can't access the internet with the previous 7 steps.

environment info:
$ docker --version
Docker version 1.12.1, build 23cf638
$ uname -a
Linux calico-03 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ sudo docker images calico/node
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
calico/node         latest              a81e0f7bf1bd        30 hours ago        186.3 MB

This is my iptable:
http://paste.openstack.org/show/587721/

**Comment by CaoShuFeng** [comment]
It still doesn't work when I run such command:
# sudo iptables -t nat -A felix-FIP-SNAT -s 172.168.0.9  -j MASQUERADE

**Comment by CaoShuFeng** [comment]
@caseydavenport 
Can you help me? Thanks very much.
I think it maybe a bug. Because I have passed --nat-outing  when creating pool.
Also I test this in local virtual machine.

**Comment by CaoShuFeng** [comment]
It still can't work when I pass --ipip to create the pool.
This is my iptable when --ipip is passed to create the pool:
http://paste.openstack.org/show/587723/

**Comment by fasaxc** [comment]
@CaoShuFeng Felix will remove any changes made to its `felix-XXX` chains.  Setting `--nat-outgoing` on the pool should be what you need.

I don't see the MASQ rule that felix should be putting in place with `--nat-outgoing` set on the pool.  Please can you verify the setting with `calicoctl pool show`?

**Comment by CaoShuFeng** [comment]
Hi, @fasaxc, I have set it. The output is this:
$ sudo ETCD_ENDPOINTS=http://192.168.122.183:2379 ./calicoctl pool show
+----------------+--------------+
|   IPv4 CIDR    |   Options    |
+----------------+--------------+
| 172.168.0.0/16 | nat-outgoing |
+----------------+--------------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+
This is the diags bundle: https://transfer.sh/13lP18/diags-031116-083126.tar.gz

**Comment by matthewdupre** [comment]
So I can repro this as follows (with latest calico-node as of time of writing):

- Given a fresh etcd, flushed iptables (including nat table) and no ipsets, run calico-node
- Create a container --net=none, calicoctl container add it
- Assign it a profile
- Ping 8.8.8.8: fails, ping other containers etc.: succeeds
- calicoctl pool add 192.168.0.0/16 --nat-outgoing
- Ping 8.8.8.8 still fails

In this state:
- iptables -L -t nat doesn't include the MASQUERADE rule
- ipset list doesn't include the -all-pools and -masq-pools sets
- the pool does have masquerade: true in etcd

I've set a P2 because of the support impact of debugging issues that depend on order of operations.

**Comment by CaoShuFeng** [comment]
Hi, matthewdupre, thanks for reproduceing this.
>>I've set a P2 because of the support impact of debugging issues that depend on order of operations.
So this issue depends on the order of operations?
In which order of operations can I avoid this?
Thanks

**Comment by matthewdupre** [comment]
I'm still checking now: I first thought it might depend on whether the pool was configured before starting the calico-nodes, but now I'm not sure.  Can you confirm your calico-node version please?

**Comment by CaoShuFeng** [comment]
I can reproduce this with calico pulled several minutes ago.
$ sudo docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
calico/node                            latest              f804946e09de        7 hours ago         180.6 MB

**Comment by matthewdupre** [comment]
OK got it, definitely just a bug in :latest.

While we work on it, please use the latest release calico/node:v0.23.0 instead: that works for me (and shout if that doesn't work either for you!).

**Comment by CaoShuFeng** [comment]
calico/node:v0.23.0 works for me.
Thanks very much.
