### ISSUE TITLE
GoBGP is missing from calicoctl status command (go version)

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-containers#1258]

**Comment by caseydavenport** [comment]
@gunjan5 we'd still like to do this if we can for v1.0.0, but it's low priority.

We'll need an ST for it.

**Comment by caseydavenport** [comment]
Removing this from v1.0.0 to v1.0.1

**Comment by gunjan5** [comment]
@caseydavenport  why is this moved to 1.0.1? This was merged with STs, I forgot to close it :)

**Comment by caseydavenport** [comment]
@gunjan5 Ah! Should have closed this issue then :)
