### ISSUE TITLE
calicoctl doesn't show global default ASN.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#1271]
```
macncheese:calico-containers casey$ ./dist/calicoctl get nodes -o wide
NAME          ASN     IPV4            IPV6
k8s-master    <nil>   172.18.18.101   <nil>
k8s-node-01   <nil>   172.18.18.102   <nil>
k8s-node-02   <nil>   172.18.18.103   <nil>
```

It should populate ASN with the global default rather than <nil> when none is specified for a node.

**Comment by caseydavenport** [comment]
CC @robbrockbank

**Comment by caseydavenport** [comment]
repurposed this issue just for the ASN bug (now that the nil stuff is fixed by #1283)

**Comment by robbrockbank** [comment]
I think this will be fixed as part of a larger rework of how we display inherited per-node configuration.

**Comment by robbrockbank** [comment]
First iteration, print "using global value"    rather than blank
(maybe) Update node status to display effective value.
