### ISSUE TITLE
calicoctl node should be able to mount certificates dir

### ISSUE THREAD

**Issue by mattymo** [projectcalico/calico-containers#1286]
``calicoctl node`` is the preferred way to start calico-node container, but it does not include options for mounting any volumes. As a result, you can't use it for secure etcd communication. What you get as a result is:

```
Traceback (most recent call last):
  File "startup.py", line 333, in <module>
    client = IPAMClient()
  File "/usr/lib/python2.7/site-packages/pycalico/datastore.py", line 223, in __init__
    ETCD_CERT_FILE_ENV, etcd_cert))
pycalico.datastore_errors.DataStoreError: Cannot read ETCD_KEY_FILE and/or ETCD_CERT_FILE. Both must be readable file paths. Values provided: ETCD_KEY_FILE=/etc/calico/certs/key.pem, ETCD_CERT_FILE=/etc/calico/certs/cert.crt
Calico node failed to start
```

**Comment by caseydavenport** [comment]
@mattymo 

I’d recommend running directly through docker (or as a Kubernetes pod).  Both will lets you mount in whatever volumes you like.

`calicoctl` should print out the command that it is running under the covers, IIRC.  The latest v1.0.0-beta includes a `--dry-run` option.  Should just be a matter of adding in the docker args to mount the volumes.

**Comment by mattymo** [comment]
I am going to close this because calico-node already mounts the following three files:
/etc/calico/certs/ca_cert.crt
/etc/calico/certs/cert.crt
/etc/calico/certs/key.pem

I will work around the problem that way.
