### ISSUE TITLE
Calicoctl should allow configuration of all Felix global and per-node configuration

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#1293]
In particular the Host Protection docs discuss global Felix configuration and refer to the configuration guide (Which is etcd specific).   We need to remove the etcd requirement.

**Comment by caseydavenport** [comment]
@robbrockbank what else is left to do for this? I'm going to put this in the v1.0.0 milestone, but shout if you think that is wrong.

**Comment by robbrockbank** [comment]
We need to re-instate the configure arbitrary config option ability .... this brings us back in alignment with the old calicoctl.

**Comment by robbrockbank** [comment]
Fixed by #1320
