### ISSUE TITLE
`calicoctl delete` doing weird stuff

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#1297]
```
macncheese:client casey$ calicoctl get nodes
NAME

macncheese:client casey$ calicoctl delete node
Successfully deleted 1 'node' resource(s)
```

I'd expect the second command to be an error, but it returns successfully!

**Comment by caseydavenport** [comment]
Note: This was performed with DATASTORE_TYPE=kubernetes.

 Note sure how it behaves with etcdv2

**Comment by robbrockbank** [comment]
I think if the command is misbehaving this should be a P1 no?

**Comment by gunjan5** [comment]
This is what I see with my setup (etcd backend):
```
vagrant@calico-01:~$ calicoctl delete node
Failed to delete 'node' resource: insufficient identifiers, missing 'node'
```

**Comment by caseydavenport** [comment]
@gunjan5 I think this is a bug in the k8s backend code, since it doesn't handle the node resource.

It should be returning an error for any delete commands, I think.

**Comment by gunjan5** [comment]
@caseydavenport 
> It should be returning an error for any delete commands, I think.
then how would anyone delete an `ipPool` for example? 

Seems like any delete command is being ignored for k8s backend right now:
```go
// Delete an entry in the datastore. This is a no-op when using the k8s backend.
func (c *KubeClient) Delete(d *model.KVPair) error {
	log.Warn("Attempt to 'Delete' using kubernetes backend is not supported.")
	return nil
}
```

**Comment by caseydavenport** [comment]
@gunjan5 d'oh, yeah I forgot about that.

That's the right behavior for it right now.  I think we want to pull out the ipPool support in the backend anyway for now - it's not done correctly.

**Comment by caseydavenport** [comment]
Fixed.
