### ISSUE TITLE
`calicoctl node` should accept both `--detach=false` and `--libnetwork`

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-containers#1322]
`calicoctl node --libnetwork` used to spawn two containers, so we did not allow `--detach=false`, as we could not easily bind to two running containers.

However, libnetwork now runs in the calico-node container. so `calicoctl node --libnetwork` always spawns 1 container. We should allow `--detach=false` in this case.

**Comment by caseydavenport** [comment]
How does this look in a post 2.0 world?

**Comment by djosborne** [comment]
I hadn't realized `--detach=false` was not implemented for v2.0. I'm assuming this was intentional, as now there is only one way to bind to a running calico/node, and that's by using the recommended way of launching `calico/node` with `docker run`?

**Comment by robbrockbank** [comment]
@djosborne 

The `calicoctl node run` command accepts the following options:

```
--dryrun
--init-system
--disable-docker-networking
```

So, logic is a little different from before.

For an init-system I'd recommend that you run with `--dryrun` and `--initsystem` and that will print out the command that you need to run to put the command in an init system, it will also write out the `docker stop` command too.

**Comment by djosborne** [comment]
Ok, I appreciate that we now have one official way to bind `calico/node` to an init-system. Our systemd documentation already shows this, so I can't identify any actions from here, so closing
