### ISSUE TITLE
Documenatation unclear for calicoctl command and calico node defaults (ETCD_ENDPOINTS)

### ISSUE THREAD

**Issue by javaboyuk** [projectcalico/calico-containers#1324]
Background (my first git hub issue I need to find out how to layout better!)
1. Installed a new etcd (v3.0.14) (3 nodes) seperate from the node I will start calico node on!
2. Trying to get calicoctl v0.23.0 to start on a single node
3. i am NOT using any security (as I am learning and thought this would add more moving parts for me to get wrong :-)) and the example in the calico doc shows an example using http NOT https **so I assume this should work?

### more calico-node.service 

```
[Unit]
Description=calicoctl node
After=docker.service
Requires=docker.service
[Service]
User=root
Environment=ETCD_ENDPOINTS=http://192.168.0.31:2379,http://192.168.0.32:2379,http://192.168.0.33:2379
PermissionsStartOnly=true
ExecStart=/usr/local/bin/calicoctl node --ip=192.168.0.21 --detach=false
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```

### calicoctl status

> calico-node container is running. Status: Up About a minute
> Error connecting to etcd.  Ensure ETCD_ENDPOINTS or ETCD_AUTHORITY is set properly.
> 
> IPv4 BGP status
> IP: unknown    AS Number: unknown
> +--------------+-------------------+-------+----------+------------------------------------------+
> | Peer address |     Peer type     | State |  Since   |                   Info                   |
> +--------------+-------------------+-------+----------+------------------------------------------+
> | 192.168.0.22 | node-to-node mesh | start | 10:24:36 | Active        Socket: Connection refused |
> +--------------+-------------------+-------+----------+------------------------------------------+
> 
> IPv6 BGP status
> IP: unknown    AS Number: unknown
> +--------------+-----------+-------+-------+------+
> | Peer address | Peer type | State | Since | Info |
> +--------------+-----------+-------+-------+------+
> +--------------+-----------+-------+-------+------+

====================================================
from the felix log file you can see ETCD_ENDPOINTS is seen BUT also 
EtcdAddr (Address and port for etcd) has value '**127.0.0.1:2379**' read from Environment variable FELIX_ETCDADDR

### grep -i etc felix.log 
> 2016-11-22 10:24:37,366 [INFO][90/1] calico.felix.config 521: Reading config from /etc/calico/felix.cfg
> 2016-11-22 10:24:37,649 [INFO][90/2] calico.felix.config 502: Parameter InterfacePrefix (Interface name prefix) has value ['cali'] read from Global etcd configuration
> 2016-11-22 10:24:37,649 [INFO][90/2] calico.felix.config 502: Parameter EtcdAddr (Address and port for etcd) has value '127.0.0.1:2379' read from Environment variable FELIX_ETCDADDR
> 2016-11-22 10:24:37,650 [INFO][90/2] calico.felix.config 502: Parameter ReportingIntervalSecs (Status reporting interval in seconds) has value 0 read from Global etcd configuration
> 2016-11-22 10:24:37,650 [INFO][90/2] calico.felix.config 502: Parameter EtcdDriverLogFilePath (Path to log file for etcd driver) has value '/var/log/calico/felix-etcd.log' read from None
> 2016-11-22 10:24:37,650 [INFO][90/2] calico.felix.config 502: Parameter EtcdCaFile (Path to etcd CA certificate file) has value '' read from Environment variable FELIX_ETCDCAFILE
> 2016-11-22 10:24:37,650 [INFO][90/2] calico.felix.config 502: Parameter IpInIpEnabled (IP-in-IP device support enabled) has value False read from Global etcd configuration
> 2016-11-22 10:24:37,650 [INFO][90/2] calico.felix.config 502: Parameter LogSeverityFile (Log severity for logging to file) has value 'None' read from Configuration file /etc/calico/felix.cfg
> 2016-11-22 10:24:37,650 [INFO][90/2] calico.felix.config 502: Parameter MetadataAddr (Metadata IP address or hostname) has value 'None' read from Configuration file /etc/calico/felix.cfg
> 2016-11-22 10:24:37,651 [INFO][90/2] calico.felix.config 502: Parameter LogSeverityScreen (Log severity for logging to screen) has value 'info' read from Global etcd configuration
> 2016-11-22 10:24:37,651 [INFO][90/2] calico.felix.config 502: Parameter DefaultEndpointToHostAction (Action to take for packets that arrive froman endpoint to the host.) has value 'RETURN' read from Host specific etcd configuration
> 2016-11-22 10:24:37,651 [INFO][90/2] calico.felix.config 502: Parameter EtcdKeyFile (Path to etcd key file) has value '' read from Environment variable FELIX_ETCDKEYFILE
> 2016-11-22 10:24:37,651 [INFO][90/2] calico.felix.config 502: Parameter FailsafeOutboundHostPorts (Comma-separated list of numeric TCP ports to allow traffic to from all host endpoints.  Useful to avoid accidentally cutting off, for example, access to etcd.  The default value allows connectivity to etcd's default ports 2379,2380,4001 and 7001.) has value [2379, 2380, 4001, 7001] read from None
> 2016-11-22 10:24:37,652 [INFO][90/2] calico.felix.config 502: Parameter ClusterGUID (Unique cluster identifier) has value '19361d48d1424d069bff1de5cd78c527' read from Global etcd configuration
> 2016-11-22 10:24:37,652 [INFO][90/2] calico.felix.config 502: Parameter EtcdCertFile (Path to etcd certificate file) has value '' read from Environment variable FELIX_ETCDCERTFILE
> 2016-11-22 10:24:37,652 [INFO][90/2] calico.felix.config 502: Parameter EtcdScheme (Protocol type for http or https) has value 'http' read from Environment variable FELIX_ETCDSCHEME
> 2016-11-22 10:24:37,652 [INFO][90/2] calico.felix.config 502: Parameter EtcdDriverPrometheusMetricsPort (Port on which to export Prometheus metrics from the etcd driver process.) has value 9092 read from None
> 2016-11-22 10:24:37,652 [INFO][90/2] calico.felix.config 502: Parameter EndpointReportingEnabled (Whether Felix should report per-endpoint status into etcd) has value False read from None
> 2016-11-22 10:24:37,652 [INFO][90/2] calico.felix.config 502: Parameter EtcdEndpoints (Comma separated list of etcd endpoints, of the form scheme://address:port.  For example "https://1.2.3.4:2379,https://1.2.3.5:2379".  This option overrides EtcdScheme and EtcdAddr.) has value 'http://192.168.0.31:2379,http://192.168.0.32:2379,http://192.168.0.33:2379' read from Environment variable FELIX_ETCDENDPOINTS
> 2016-11-22 10:24:37,653 [INFO][90/2] calico.felix.config 502: Parameter LogFilePath (Path to log file) has value 'None' read from Configuration file /etc/calico/felix.cfg
> 2016-11-22 10:24:37,653 [INFO][90/3] calico.felix.fetcd 194: Interval is 0, status reporting disabled.
> 2016-11-22 10:24:37,653 [INFO][90/4] calico.felix.fetcd 166: Config loaded, resync interval 3600.
> 2016-11-22 10:24:37,656 [INFO][90/2] calico.felix.fetcd 594: etcd driver status changed to resync
> 2016-11-22 10:24:37,837 [INFO][90/5] calico.felix.felix 249: Starting polling for interface and etcd updates.
> 2016-11-22 10:24:37,844 [INFO][90/2] calico.felix.fetcd 594: etcd driver status changed to in-sync
>   File "site-packages/calico/felix/fetcd.py", line 363, in _periodically_usage_report
> 
===============================================

Any help really appreciated.

**Comment by javaboyuk** [comment]
Sorry  running on command line:
/usr/local/bin/calicoctl node --ip=192.168.0.22 --detach=false
Running Docker container with the following command:

docker run --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=master-2 -e IP=192.168.0.22 -e IP6= -e CALICO_NETWORKING_BACKEND=bird -e AS= -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=false -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -e ETCD_ENDPOINTS=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379 -v /var/log/calico:/var/log/calico -v /lib/modules:/lib/modules -v /var/run/calico:/var/run/calico calico/node:v0.23.0

Calico node is running with id: f12dcd8b29268c62a0aa0cd4e47a9661e2b512842d9f3028de1e2ec18e36156f
Waiting for successful startup
Waiting for etcd connection...
Calico node started successfully


WORKS!!   it must be in systemd sorry

**Comment by javaboyuk** [comment]
This was actual two newbie issues:

1. That the docs (well where I looked) did not state that the defaul calico network is 192.168.0.0/16 which just so happens to be the network I am using on the front end (I am currently trying to make this 10.3.0.0/16)
2. The calicoctl command talks to the etcd back-end directly and so you need to have an env variable ETCD_ENDPOINTS which points to your etcd service before your run calicoctl. The docs assume your on the same node as etcd and calico-node I think so the lookpback would work, but mine were separate (as according to best practice).

When I get this all going Ill put a pull in for the doc pages I used. But other new people to calico might find the above journey informative.

**Comment by caseydavenport** [comment]
@javaboyuk glad you figured it out, and sorry we've taken so long to chime in on this guy!

Would appreciate a docs PR to address the two points you raised if you can :)

I've raised https://github.com/projectcalico/calico/issues/357 and https://github.com/projectcalico/calico/issues/356 to track.
