### ISSUE TITLE
Felix syslog logging doesn't work in calico/node

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#1374]
I believe that's the issue behind https://github.com/projectcalico/felix/issues/1197.

Do we care?  Should we disable syslog in containerland (since it's not typically used)?

**Comment by fasaxc** [comment]
If we do want to fix, we probably need to forward the syslog port/named pipe into the container.

**Comment by caseydavenport** [comment]
Closing as wontfix.

Set `FELIX_LOGSEVERITYSYS` to get debug logs in calico/node.
