### ISSUE TITLE
Feature request: Make Calico use Kubernetes's etcd

### ISSUE THREAD

**Issue by TamalSaha** [projectcalico/calico-containers#1380]
Hi,
One of the difficult parts of using Calico with Kubernetes is that Calico requires a separate etcd server which is accessed by any nodes of a cluster. This introduces complexity in setup process because this etcd needs to be secured separately. So, I wonder will it be possible to use Kubernetes apiserver/3rd part objects as a replacement for etcd to store data for Calico. I saw that Flannel did something similar recently making it really easy to setup.

Thanks.

**Comment by caseydavenport** [comment]
@TamalSaha Yes, this is definitely in our road map.

We've already implemented a version of Calico that does this for policy only, but it doesn't yet support all of the Calico data model (e.g stuff required for BGP).

See here: http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend/

**Comment by TamalSaha** [comment]
Thank @caseydavenport . I am interested in the stuff required for BGP. Any tentative timeline for that?

**Comment by caseydavenport** [comment]
@TamalSaha really tentatively I'd say in the next couple of months, but no date set yet.

**Comment by TamalSaha** [comment]
@caseydavenport sounds great! We are looking forward to that.

**Comment by caseydavenport** [comment]
This issue touches on a lot of different components and has lots of work ahead of it. 

I've raised https://github.com/projectcalico/calico/issues/355 to track questions / feature progress.
