### ISSUE TITLE
calico/node v1.0.0-rc3: Unexpected command output Device "eth0" does not exist.

### ISSUE THREAD

**Issue by r0bj** [projectcalico/calico-containers#1407]
I have working k8s cluster with calico v0.23.0:
OS: ubuntu 14.04
kubernetes: 1.4.7
docker-engine: 1.12.1-0~trusty
etcd: 3.0.15
calico-containers: v0.23.0
calico-cni: 1.4.3

Everything works ok.

Then I'm trying to run new hosted version of calico:
http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/hosted
using yaml file:
http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/calico.yaml

I've edited yaml file changing fields: `etcd_endpoints`, `cidr` and version of the image `quay.io/calico/node` to `v1.0.0-rc3`:
https://gist.github.com/r0bj/e3773396b287e5378f893907a415cf02

After successful calico/node DeamonSet start, creating pods isn't possible due to error message from kubelet:

```
E1212 12:21:33.303277    1134 docker_manager.go:357] NetworkPlugin cni failed on the status hook for pod 'nginx-1691775941-t7f51' - Unexpected command output Device "eth0" does not exist.
 with error: exit status 1
```
Logs with more context:
https://gist.github.com/r0bj/5f4a32f68d628ebb8c4678d02682ff02
Logs with debug:
https://gist.github.com/r0bj/2f4546ef763e9def9b0951e9b2e8a789

`cali` interface isn't created on node.

My kubelet config:
```
 /usr/bin/kubelet \
    --node-labels=k8s-role=k8s-worker \
    --allow-privileged=true \
    --api-servers=https://dev.kubernetes-controller.service.consul:6443 \
    --cloud-provider= \
    --cluster-dns=10.223.0.10 \
    --cluster-domain=cluster.local \
    --container-runtime=docker \
    --docker=unix:///var/run/docker.sock \
    --network-plugin=cni \
    --network-plugin-dir=/etc/cni/net.d \
    --kubeconfig=/var/lib/kubelet/kubeconfig \
    --reconcile-cidr=true \
    --serialize-image-pulls=false \
    --tls-cert-file=/var/lib/kubernetes/kubelet-cert.pem \
    --tls-private-key-file=/var/lib/kubernetes/kubelet-key.pem \
    --v=2
```

**Comment by caseydavenport** [comment]
```
E1212 13:02:00.620467    1134 docker_manager.go:357] NetworkPlugin cni failed on the status hook for pod 'nginx-1691775941-fgoxx' - Unexpected command output Device "eth0" does not exist.
 with error: exit status 1
```

That error message is actually benign.  The kubelet has an async status check that, when it occurs before the CNI plugin is finished, emits that message.

Since the "Device "eth0" does not exist." is likely a red-herring, there is probably something else preventing the pods from starting.

This is the last log I see from Calico

```
INFO[0000] Populated endpoint                            Workload=default.nginx-1691775941-qifgx endpoint=&{{workloadEndpoint v1} {{} eth0 default.nginx-1691775941-qifgx k8s dev-k8s-worker-p3 map[]} {[10.203.27.245/32] [] <nil> <nil> [k8s_ns.default]  <nil>}}
```

but I'd expect some more logs to come after that.  Can you make sure that you're not missing some of the logs further down?

You can also check `kubectl describe pod X` on a pod that isn't coming up - it may provide more information.

**Comment by r0bj** [comment]
Thanks for help.
kube-proxy wasn't running on the node. So without communication with API there was not possible to create pod. I guess this is difference in comparison to previous version of calico.
I'm closing this issue then.
