### ISSUE TITLE
Break in connectivity while restarting calico/node

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico-containers#1419]
I create a kubernetes cluster with 2 nodes.  I create iperf server pods on it with:
`kubectl run iperf --image=phlak/iperf` until I have at least 1 on each node.  

I then get into one with `kubectl exec -it iperfb-3109788441-ag1vg sh` and run iperf: `iperf -c 192.168.177.128 -t 3600 -i 1`.

I then kill one of the calico-node instances running on a node:
`kubectl delete pod -n kube-system calico-node-3m0ug`

While the new pod is starting up, I notice a 2 second break in iperf traffic:
```
[  3] 915.0-916.0 sec   563 MBytes  4.72 Gbits/sec
[  3] 916.0-917.0 sec   673 MBytes  5.65 Gbits/sec
[  3] 917.0-918.0 sec   674 MBytes  5.65 Gbits/sec
[  3] 918.0-919.0 sec   518 MBytes  4.35 Gbits/sec
[  3] 919.0-920.0 sec   674 MBytes  5.65 Gbits/sec
[  3] 920.0-921.0 sec   536 MBytes  4.50 Gbits/sec
[  3] 921.0-922.0 sec   403 MBytes  3.38 Gbits/sec
[  3] 922.0-923.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 923.0-924.0 sec  0.00 Bytes  0.00 bits/sec
[  3] 924.0-925.0 sec   102 MBytes   860 Mbits/sec
[  3] 925.0-926.0 sec   627 MBytes  5.26 Gbits/sec
[  3] 926.0-927.0 sec   667 MBytes  5.59 Gbits/sec
[  3] 927.0-928.0 sec   651 MBytes  5.46 Gbits/sec
```

**Comment by caseydavenport** [comment]
So it sounds like either Felix and/or BIRD is not programming the data plane gracefully when it comes back up.

I think it would be worth grabbing the logs from both BIRD + Felix and we can take a look at what it's doing during the restart.

Might also be interesting to note if this happens on restart, or if it happens on upgrade from 1.6 -> 2.0 exclusively.

**Comment by caseydavenport** [comment]
CC @fasaxc for thoughts on what to look for in Felix.

**Comment by fasaxc** [comment]
To narrow it down, I'd start with 
- `sudo watch -d -n 0.1 "iptables-save | grep felix"` during a test and see if the rules glitch when Felix restarts.
- `sudo watch -d -n 0.1 "ip route"`and see if the routes glitch (either felix or bird ones).
If felix looks at fault, might need to drop to debug felix logs and worth through the iptables and ipsets updates.

**Comment by caseydavenport** [comment]
I've tried the following, using the steps @lwr20 mentions above:

#### 1.6 restart case (success)
- Deploy v1.6 + run iperf between two pods.
- Kill calico/node on one of the hosts with an iperf pod, wait for it to come back.

#### v1.6 -> v2.0 upgrade (success)
- Pull calico/node:v1.0.0-rc4 to the host.
- Apply new DaemonSet
- Delete the calico/node on the host and wait for it to restart

#### v2.0 restart (success)
- Kill calico/node on one of the hosts with an iperf pod, wait for it to come back.

I haven't seen any traffic loss during the above.

**Comment by lwr20** [comment]
OK - I'll attempt to repro and get the diags requested.

**Comment by lwr20** [comment]
There was indeed a very brief glitch at the point of the break.  Here's the `ip monitor` output at the point it glitched: 
```
Deleted 192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
Deleted 192.168.67.64/26 via 10.240.0.13 dev tunl0  proto bird onlink 
192.168.67.64/26 via 10.240.0.13 dev tunl0  proto bird onlink 
Deleted 192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
4: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default 
    link/ipip 0.0.0.0 brd 0.0.0.0
Deleted 4: tunl0    inet 192.168.151.0/32 scope global tunl0
       valid_lft forever preferred_lft forever
Deleted local 192.168.151.0 dev tunl0  table local  proto kernel  scope host  src 192.168.151.0 
Deleted 10.240.0.13 dev tunl0 lladdr 0.0.0.0 NOARP
4: tunl0    inet 192.168.151.0/32 scope global tunl0
       valid_lft forever preferred_lft forever
local 192.168.151.0 dev tunl0  table local  proto kernel  scope host  src 192.168.151.0 
192.168.67.64/26 via 10.240.0.13 dev tunl0  proto bird onlink 
192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
Deleted 192.168.67.64/26 via 10.240.0.13 dev tunl0  proto bird onlink 
192.168.67.64/26 via 10.240.0.13 dev tunl0  proto bird onlink 
Deleted 192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
192.168.95.0/26 via 10.240.0.12 dev tunl0  proto bird onlink 
```

**Comment by fasaxc** [comment]
As discussed, felix logs would be helpful.  I'd be on the lookout for a felix restart with different config.  Did Felix start up once thinking there was no tunnel address, then once with it or something like that?  Other ideas is that felix is removing then re-adding the IP, or that creating the tunnel isn't idempotent so, even thought we don't remove it.

**Comment by lwr20** [comment]
Felix debug logs over startup: https://gist.github.com/lwr20/fe8d3c11fb15f985f546b635649bbb5d

**Comment by fasaxc** [comment]
From the logs, looks like Felix *is* flapping the IP address on the tunnel interface:
```
2016-12-15 11:07:26,126 [DEBUG][113/2] calico.felix.devices 128: Interface tunl0 has IPv4 IPs ['192.168.151.0']
2016-12-15 11:07:26,126 [INFO][113/2] calico.felix.devices 181: Removing IP 192.168.151.0 from interface tunl0
2016-12-15 11:07:26,126 [DEBUG][113/2] calico.felix.futils 340: Calling out to system: ['ip', 'addr', 'del', '192.168.151.0', 'dev', 'tunl0'].  0/32 concurrent calls
2016-12-15 11:07:26,130 [DEBUG][113/2] calico.felix.futils 352: Process finished with RC=0: ['ip', 'addr', 'del', '192.168.151.0', 'dev', 'tunl0'].
2016-12-15 11:07:26,130 [INFO][113/2] calico.felix.devices 184: Adding IP 192.168.151.0 to interface tunl0
2016-12-15 11:07:26,130 [DEBUG][113/2] calico.felix.futils 340: Calling out to system: ['ip', 'addr', 'add', '192.168.151.0', 'dev', 'tunl0'].  0/32 concurrent calls
2016-12-15 11:07:26,133 [DEBUG][113/2] calico.felix.futils 352: Process finished with RC=0: ['ip', 'addr', 'add', '192.168.151.0', 'dev', 'tunl0'].
```
While it's reading the correct IPs, it's then removing them all and re-adding them rather than spotting that the IP is already in place.

**Comment by lwr20** [comment]
Looks much better with the fix.

**Comment by bcreane** [comment]
@lwr20 - looks like instantiating multiple replicas of phlak ensures distribution across nodes (maybe):
`kubectl run iperf --image=phlak/iperf --replicas=2`
