### ISSUE TITLE
Package calicoctl into a calico/ctl docker image

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-containers#309]
This may or may not support the commands that interact with docker (e.g. starting a node and adding networking to container). Maybe they would only work if the docker sock is mapped into the container...

**Comment by Symmetric** [comment]
Just had a wee think about this -- I like this approach, and it has some significant advantages.

It would allow us to bundle e.g. nsenter with our calicoctl, which would simplify our netns.py code significantly.

I like the idea of a two-layered approach; you can do `docker run -v ... --privileged calico/ctl node ...`, but we should also have a wrapper to preserve the original `calicoctl node ...` syntax. That would just be a call through to the docker command (could even be a shell script). This would mean that if you don't want to download the wrapper binary, you can just run the full docker incantation - and it would be portable to anywhere that has a docker daemon.

**Comment by Symmetric** [comment]
Also note that this isn't crazy; Weave do something very similar for their weavetools image.

**Comment by tomdee** [comment]
A first pass at this is on my repo
https://github.com/projectcalico/calico-docker/compare/master...tomdee:calico/ctl?expand=1
