### ISSUE TITLE
Hard to find endpoint by container name

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#437]
When debugging, I often have the name of a container to hand but calicoctl doesn't have an option to search by container name.  Instead, I have to:

* use `docker ps` to get the workload ID of the container
* feed that into calicoctl.

calicoctl also doesn't list the container name in its output, which means to go in reverse I have to go from workload or endpoint ID and grep docker's output for that.

**Comment by robbrockbank** [comment]
There is the `calicoctl container <CONTAINER_ID> endpoint-id show` command which returns the endpoint ID given the container name or ID.  Does that give you what you need?

**Comment by tomdee** [comment]
@fasaxc Don't grep docker output, use `docker inspect`. 

Also, this bug is related to #398

**Comment by fasaxc** [comment]
I guess I'm saying it's pretty repetative/tedious to continually have to map back and forth between the (very long) IDs when I had the name in hand.  Could we copy the name to etcd, just so we can search on it?

**Comment by lxpollitt** [comment]
Worth thinking about Spike's new IPAM stuff here in case that helps.

**Comment by tomdee** [comment]
This should at least be partially fixed by #450 (see also #398)

**Comment by tomdee** [comment]
The name isn't unique cluster wide, so it's not nearly as useful in etcd as a UUID.

**Comment by fasaxc** [comment]
Even if it showed me a lit of containers with a particular name, that'd be useful, I think.  Then it's up to me whether I use unique names or not.

**Comment by tomdee** [comment]
Given that the current data model doesn't provide for storing container/workload names I can't see us fixing this any time soon.
