### ISSUE TITLE
caliicoctl diags failing at scale

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#470]
Seen in the scale testing.  With 101 containers on an GCE 2-core instance running CoreOS, I can't run calicoctl diags:

```
$ ./calicoctl diags
Collecting diags
Using temp dir: /tmp/tmpj7gvlK
Dumping netstat output
Unexpected error executing command.

Traceback (most recent call last):
  File "<string>", line 92, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.diags", line 48, in diags
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.diags", line 77, in save_diags
  File "/code/build/calicoctl/out00-PYZ.pyz/sh", line 1021, in __call__
  File "/code/build/calicoctl/out00-PYZ.pyz/sh", line 483, in __init__
  File "/code/build/calicoctl/out00-PYZ.pyz/sh", line 1190, in __init__
  File "/code/build/calicoctl/out00-PYZ.pyz/pty", line 29, in openpty
  File "/code/build/calicoctl/out00-PYZ.pyz/pty", line 70, in _open_terminal
OSError: out of pty devices
```

I looked in /dev/pts/, which I think is where pty devices live but there were only about 120 in there and the system limit was 4096.  I suppose they may have been hidden in my containers!

This was a large-scale test so I had to tear it down before I could investigate further.

**Comment by fasaxc** [comment]
Hmm, hit the same issue again today and tried increasing the number of ptys to no avail.  However, running as root did work around the issue.  Maybe that was the issue and we should error out and recommend running as root?

**Comment by tomdee** [comment]
We need to understand this issue better before we can fix it. A simple(r) repro would really help...

**Comment by robbrockbank** [comment]
The diagnostic gather should be a lot more robust now - so that if there is a problem running a command we won't bail out but instead write the problem to the log file.  This will certainly look better but doesn't get to the bottom of the issue.

Another thing we might want to do is switch using the "Sh" library and just use the subprocess library.  Perhaps there is something odd about that library.

**Comment by fasaxc** [comment]
Running as root seemed to be a workaround, should we simply recommend that?

**Comment by matthewdupre** [comment]
I'd second running as root.  "Dumping ipset" doesn't work as non-root anyway (prints "Error gathering diagnostics", so we have a reason for doing this anyway.

**Comment by robbrockbank** [comment]
Yup sounds like a plan!
