### ISSUE TITLE
pools with ranges don't work well with IPAM

### ISSUE THREAD

**Issue by spikecurtis** [projectcalico/calico-containers#505]
`calicoctl pool range add ...` creates a bunch of small pools that add up to the range identified.  This is a problem if Calico IPAM is used, since we use a fixed-size block, so it will ignore any pools smaller than the block size (64-addresses in latest version).

In the worst case, if no pools are the block size or larger, we will completely fail to allocate addresses.

c.f. error logs in Kubernetes: http://pastebin.com/PGMe67Ws

**Comment by tomdee** [comment]
@spikecurtis Any thoughts on how we should tackle this? Is it a choice between 
1) requiring that `calicoctl pool` is aligned on IPAM-block-sized boundaries; or
2) making calico ipam support multiple block sizes?

Or is there a third way? 

Given those options, 1) seems like the best way forwards, do you agree?

**Comment by spikecurtis** [comment]
@tomdee I'd suggest a variation on 1).  

This needs some thought on how it interacts with the routes BIRD exports, but:

Modify the `calicoctl pool range add ...` command to be aware of IPAM block sizes, and never create a pool smaller than a single block.  Instead, create the pool spanning at least an entire block, then mark all addresses outside the given range as unavailable in the block, perhaps with a special attribute so it can be later modified by `calicoctl pool` commands.

**Comment by robbrockbank** [comment]
Tim, let's just prevent users from configuring pools smaller than the limit dictated by our IPAM module.

This limit should either be inforced in calicoctl - and possible also in the IPAM client.

If enforcing in the IPAM client we should remove the restriction if the pool is not allowed to be used for calico IPAM since our IPAM client won't allocate from the block anyways.

**Comment by TrimBiggs** [comment]
Wait until #800 is merged
