### ISSUE TITLE
Standardize Kubernetes plugin install location

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#554]
Currently, `calicoctl node --kubernetes` installs the Kubernetes plugin to `/usr/libexec/...` on most distros, but installs it to `/etc/kubelet-plugins/calico` on CoreOS (since `/usr` is read-only).

This is unnecessarily confusing.  Post Kubernetes v1.1 (when the --network-plugin-dir option is released) we should update this behavior so the plugin is always installed to the same location.  This will help us standardize our guides and tutorials.

**Comment by robbrockbank** [comment]
Marking as blocked (pending Kubernetes v1.1)

**Comment by wienczny** [comment]
Has this been superseded by CNI?

**Comment by caseydavenport** [comment]
Yep, this isn't relevant with CNI.
