### ISSUE TITLE
Orchestrator.md document needs reinstating with valid instructions

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-containers#569]
Orchestrators.md still refers to Powerstrip.

It should be updated to be relevant to the current Calico deployments and should include links to the repos and docs for existing Calico orchestrator plugins.

**Comment by robbrockbank** [comment]
The Orchestrators.md file will be removed as part of removing references to Powerstrip.  Updated the name of this issue to re-instate this document with up to date instructions.

https://github.com/projectcalico/calico-docker/pull/585

**Comment by robbrockbank** [comment]
Make sure to update the link on the projectcalico.org website.

**Comment by matthewdupre** [comment]
Powerstrip is long gone.  As is this doc.
