### ISSUE TITLE
MTU within container not set to be equal to tunnel MTU

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-containers#610]
From titilambert:

Hello, I got a problem with MTU. MTU of container cali interface should be less or equal to the MTU of tunl0 interface. (I think the default is 1440)
Also, It should be cool, to be able to define the MTU when we create docker interface.
```
docker network create --driver=calico --opt nat-outgoing=true --opt ipip=true --mtu=1440 --subnet=192.168.1.0/24
```
Thanks !

**Comment by tomdee** [comment]
I don't think `--mtu` is an existing option on `docker network create`. Maybe that part of the bug would be better raised against docker or libnetwork.

**Comment by titilambert** [comment]
@tomdee the calico interface in the container is created by calico-node or by docker ?
Here (https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/netns.py#L79) we can see the command to create an interface. I don't know if it's the good one.

**Comment by TrimBiggs** [comment]
I think there is an easy fix for this when using calico with docker default networking.  I'll take a look at this and put up a PR if so.

I don't think this will fix Calico with libnetwork.  We should raise an issue with docker or libnetwork as @tomdee mentioned.

**Comment by TrimBiggs** [comment]
Hi @titilambert,

I have a couple of questions about this issue.  We had run some tests previously where having a container with higher MTU than the tunnel does not cause packet loss.  It is normal to see the ICMP response that you posted in IRC (`192.168.0.10: ICMP 192.168.0.8 unreachable - need to frag (mtu 1440), length 556`).  Path MTU discovery should see these responses and modify packet size to fit the path.  The Path MTU will check every so often to set the correct MTU for the path.

Is this a problem that you are continuously seeing?  Do your REST call(s) fail or succeed when you see this message?

**Comment by TrimBiggs** [comment]
@titilambert, did you see my message just above?

**Comment by titilambert** [comment]
Hello!
Indeed, when I just ping I don't get any error. If I try with a larger packet I get the frag error.
I get the error with only one of my calls, which I don't have a lot a information. But all other calls are fine.
But I think the problem could come with is a streaming requests.
Also, I'm working on Digital Ocean. Maybe there is something on their network ?

**Comment by ccl0326** [comment]
hi guys, any progress about this issue?

**Comment by caseydavenport** [comment]
Consolidating with this issue: https://github.com/projectcalico/calico-containers/issues/488

Please carry on any conversation there :)
