### ISSUE TITLE
How to specify IP Address when using libnetwork?

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calico-containers#652]
When using powerstrip, we can run containers with  ``` -e CALICO_IP=xxx ``` , now how can we do that?

**Comment by robbrockbank** [comment]
@frostynova 

If you use the "default docker networking" approach, you can specify the IP address when you add the container to the Calico network.  (e.g. ```sudo calicoctl container add workload-A 192.168.0.1```)

If you are using the new libnetwork based approach, we don't currently support IP selection per container.  IP addresses are assigned automatically from the configured IP Pools.

The libnetwork configuration is a work in progress, so any input on why/what level of configuration you need is useful at this stage.

**Comment by frostynova** [comment]
@robbrockbank yep, we need libnetwork+calico  with ip address specified 

Imaging this:

When upgrading a container ( stop  & pull_new & start ), if the ip changed, dns record must be updated too. But there is often a time lag. 

And since clients may hold their own dns cache, we have to restart all clients which need request this container to force them access the new ip address

**Comment by robbrockbank** [comment]
Hi @frostynova.  I wrote a response to this a while back and looks like i didn't hit comment.  Apologies.

As far as I'm aware the native Docker API doesn't currently support a mechanism for specifying a container IP, so I'm not sure this is possible using the libnetwork approach.  Is it possible for you to use the non-libnetwork approach for networking with Calico?

**Comment by frostynova** [comment]
@robbrockbank Thanks for the answer

That's why we still use ver 0.4.9
Without libnetwork, the main problem is when containers start, the network is actually not ready. Some applications which depend on a reachable network will fail.
And the problem of the  default network solution in current version is, we need to deploy a daemon on each host, which will monitor the running containers and add them to correct profile. In 0.4.9, this can be done by passing the CALICO_PROFILE environment.

**Comment by robbrockbank** [comment]
Docker docker issue https://github.com/docker/docker/issues/6743 is currently tracking this.

**Comment by frostynova** [comment]
@robbrockbank Thanks, now we can only wait for the new version released.

**Comment by frostynova** [comment]
seems docker 1.10 has been released and support custom ip feature

**Comment by robbrockbank** [comment]
Indeed!  I was just installing a new VM since my current dev machine is 15.10 which is not supported by docker 1.10.0 at the moment.

With any luck, it may just work out of the tin provided the libnetwork interface has not changed.

**Comment by robbrockbank** [comment]
I've tested with Docker 1.10.  Unfortunately there was a bug in the libnetwork plugin which did not allow the IP to be specified.  I have fixed the bug, so if you use the latest version of the libnetwork plugin (which you can explicitly specify on the `calicoctl node` command using `--libnetwork-image=calico/node-libnetwork:latest` then it should work.  The 0.17 release of calico-containers should include this natively.

There is a Docker restriction using this feature.  When specifying an IP address using `--ip` or `--ip6`, the network has to be created for a specific subnet (or pair of subnets if you are using v4 and v6).

I'll keep this issue open to update calico-containers documentation.

**Comment by robbrockbank** [comment]
The latest of calicoctl includes the fixed libnetwork plugin that allows the --ip flag to be used.
