### ISSUE TITLE
Kubernetes vagrant instructions are wrong/out of date

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-containers#657]
Multiple problems with the docs at
https://github.com/projectcalico/calico-docker/blob/master/docs/kubernetes/VagrantProvisioner.md

Mainly the text just feels out of date - the biggest problem is that it's using a pre-1.0 fork of Kubernetes.

It's also not great in that the magic is hidden in a script making it hard for users to know what's going on.

**Comment by alexhersh** [comment]
When we cleanup and merge https://github.com/kubernetes/kubernetes/pull/7245 we will be able to point to kubernetes:master

**Comment by tomdee** [comment]
@caseydavenport Can this just be closed?

**Comment by caseydavenport** [comment]
Yep.
