### ISSUE TITLE
Kubernetes client certificate KUBE_API_ROOT

### ISSUE THREAD

**Issue by euprogramador** [projectcalico/calico-containers#668]
kubernetes supports multiple ways to protect your api, the best is client certificate, where api kubernetes is protected with a client certificate and only those who have this certificate is doing operations in api, calico node does not support certificate-based authentication, today decided making a nginx proxy site and pointing to localhost KUBE_API_ROOT however this leaves a gap in communication, please add support kubernetes running ssl client certificate authentication.

**Comment by caseydavenport** [comment]
@euprogramador - The `calico/node` container itself doesn't currently access the Kubernetes API, but the calico-kubernetes plugin does.  The calico-kubernetes plugin currently supports token authentication using the KUBE_AUTH_TOKEN variable.  Is there a reason that token auth is not sufficient for your use case?

**Comment by euprogramador** [comment]
@caseydavenport for safer use authentication via client certificate, so the security is enhanced since ssl use the ssl server and the client to identify a closing cross pair. for each client that uses the api I generate a client certificate, and kubernetes does not accept other authentication mechanism, auth token refers not autentication authorization, would be good for calico-kubernetes have a way to configure certificate keys for authentication ssl

**Comment by matthewdupre** [comment]
@caseydavenport is this issue still relevant?

**Comment by caseydavenport** [comment]
The latest CNI plugin supports this, so we can close this issue.
