### ISSUE TITLE
Upgrade calicoctl Python version for improved security when using Etcd with SSL

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-containers#682]
When running calicoctl with etcd, urllib3 prints a warning to the screen:
```
InsecurePlatformWarning: A true SSLContext object is not available. This prevents 
urllib3 from configuring SSL appropriately and may cause certain SSL connections 
to fail. For more information, see 
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
```

We can fix this by:
1) Upgrading the version of python being used to create the calicoctl binary (currently 2.7.3, upgrade to 2.7.9+).  This involves something like changing the Dockerfile to use `debian:jessie` instead of `debian:wheezy`.  The Kubernetes plugin (and potentially others) also uses `debian:wheezy` and requires some thought

2) Modifying urllib3 to use OpenSSL as its backend ssl module, as described in the URL in the warning above

**Comment by robbrockbank** [comment]
@TrimBiggs 

I assume we supress the warning now, so can the title of this issue be adjusted to reflect that we need to upgrade the calicoctl python version for improved security when using etcd.

**Comment by TrimBiggs** [comment]
Yes, just updated.

**Comment by tomdee** [comment]
This issue should not be closed until the TODO is removed from the code.

It will be fixed by https://github.com/projectcalico/libcalico/pull/89

**Comment by caseydavenport** [comment]
I've got a branch in libcalico which includes an update to the Python version in the build container to 2.7.9 in order to fix this.

See here: https://github.com/projectcalico/libcalico/pull/89/files
