### ISSUE TITLE
Make calico/node container work in rkt

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#689]
This issue tracks what's needed to make calico/node work in rkt.  

The calico/node container doesn't currently work in rkt because rkt seems to have no way to run a container with the privileges that we need.  In particular, we know of these issues:

* rkt mounts /proc/sys as read-only but we need to modify it to configure the kernel.  I was able to work around this by using `rkt enter` to enter the container as "real" root and remount it read-write.
* rkt runs Felix without the capabilities it needs to execute iptables commands.  (Confusingly, Felix is running as root but its privileges seem to be curtailed.)

There may be more issues hiding behind those.

The rkt team are in the process of adding a new `rkt fly` command which would execute an image in the host namespace(s) (or some selection thereof).  This would be ideal.

With rkt 0.13.0, this command launches the container (but hits the privilege issues above):
```
sudo ./rkt run --insecure-options=all docker://calico/node:latest --set-env=HOSTNAME=<hostname> --set-env=IP=<ip> --set-env=CALICO_NETWORKING=true --set-env=IP6= --set-env=ETCD_AUTHORITY=localhost:4001 --net=host
```

**Comment by fasaxc** [comment]
https://github.com/coreos/rkt/pull/1833 introduces a new rkt stage1, which implements the `rkt fly` behaviour.  It's not yet finished but I was able to get calico/node running in that mode if I made a couple of tweaks.

Building rkt from source using  https://github.com/steveeJ/rkt/commit/59add1ae862ad1cb55103389d07582eb1002be52 , I was able to run calico/node with these arguments:
```
cd rkt
./autogen.sh
./configure --with-stage1-flavors='coreos,kvm,fly'
make

sudo ./build-rkt-0.13.0+git/bin/rkt run --stage1-image=build-rkt-0.13.0+git/bin/stage1-fly.aci docker://calico/node:latest --set-env=HOSTNAME=smc-ubuntu --set-env=IP=172.16.171.5 --set-env=CALICO_NETWORKING=true --set-env=IP6= --set-env=ETCD_AUTHORITY=localhost:4001 --net=host
```
However, the `--set-env` arguments seem to be ignored by the current version of the fly stage1 (which prevents confd from picking up the required variables) and `--net=host` is probably unnecessary with the new stage1.

Once I'd booted the container, I had to find its filesystem on disk (`rkt enter` doesn't work with the new stage1) and modify the PATH for felix in its `/etc/service/felix/run` to include `/usr/sbin`:
```
#!/bin/sh
exec 2>&1
export PATH=$PATH:/usr/sbin
exec calico-felix
```
Without that tweak, Felix couldn't find the ipset command.  I suspect the new stage1 doesn't set up the environment correctly yet.

**Comment by philips** [comment]
@fasaxc This issue should be fixed now in rkt v0.16.0 https://github.com/coreos/rkt/pull/1989

**Comment by tomdee** [comment]
@philips Thanks for the response. I'm pleased to say this is now working for us and I'm currently working on a guide for running rkt+calico on CoreOS - #759

**Comment by fasaxc** [comment]
@philips thanks!
