### ISSUE TITLE
calicoctl can't match on ICMPv6

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#691]
As described in https://github.com/projectcalico/calico/issues/938, inserting an ICMP rule for v6 addresses doesn't work.  

calicoctl/libcalico uses "icmp" for the protocol but felix is expecting "icmpv6".  This passes validation in Felix and the kernel accepts it even for an IPv6 rule, but it doesn't match the right packets.

We could fix in Felix by mapping "icmp" to different kernel protocols depending on whether we're generating an IPv4 or IPv6 rule.  However, since ICMP and ICMPv6 are quite different, the other parameters on the rule might be wrong too so maybe we should fix in the UI and force people to be explicit?

By other parameters, I mean the type and code, which don't line up.  e.g. ping is 7 in ICMP but it's 128 in ICMPv6.

**Comment by fasaxc** [comment]
WDYT?  I expect the work is pretty straightforward in Felix or calicoctl.

**Comment by TrimBiggs** [comment]
I think changing this in `calicoctl` is the right thing to do.  Seems like Felix is doing the right thing, and we should really be explicit about having an ICMPv6 rule option.
