### ISSUE TITLE
With default network model, can we use inspect to fetch the ip addr managed by Calico?

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calico-containers#694]
When using powerstrip, inspect API is hijack by Calico. Now use default network, can we still get the IP Address ?

**Comment by TrimBiggs** [comment]
Rather than using docker inspect to get the IP, you can use `calicoctl container <container> endpoint show` command to see the Calico IP address on the container:
```
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
|  Hostname  | Orchestrator ID |                           Workload ID                            |           Endpoint ID            |   Addresses    |        MAC        | Profiles | State  |
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
| MyHostname |      docker     | bfdd1be8928f8d62687dc8eee96293723d28d1a4afcdcb7eca66762e2d9ca945 | c1609cb2a5e311e582000800270e890c | 192.168.0.0/32 | 56:a1:c9:02:1a:43 |          | active |
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
```

Does that answer your question?

**Comment by frostynova** [comment]
@TrimBiggs I know this way, but swarm we use to manage the containers cannot use it.

**Comment by robbrockbank** [comment]
HI @frostynova - no this won't be possible.  When using docker `--net==none` and `calicoctl` to manage the container interface and IP assignment, Docker is not involved in the networking at all, and so this information will not be output in the `inspect` command.

**Comment by frostynova** [comment]
@robbrockbank Got

We are still use 0.4.9, with the powerstrip. I wonder if there is any special reason for removing the hijack method in the later version? If not, we will re-implement our own version.

**Comment by robbrockbank** [comment]
@frostynova 

The reason we moved away from powerstrip was simply because the libnetwork approach is the preferred approach moving forwards - it has better integration with docker and the full container lifecycle.

Is the only thing preventing you from using calico as a docker network plugin the fact that you cannot specify an IP address for a container?  If so, there was mention of a forked version of docker that has the ip address configurable when creating a container.  I think the API may change when it is added officially into docker, but it might provide you with what you need.

https://github.com/docker/docker/issues/6743#issuecomment-109572902

**Comment by frostynova** [comment]
@robbrockbank Yes, that is a key feature we needed. 

And another is it seems upgrade from v0.4.9 to latest version with libnetwork is difficult. We need to translate the profile in 0.4.9 to libnetwork subnet, without breaking our produciton environment.

We will wait until Feb 2016, to have a look at if the new version libnetwork will provide what we need.

**Comment by robbrockbank** [comment]
I think this has been answered, so closing out the issue.
