### ISSUE TITLE
calicoctl status should return code 1 if errors detected

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-containers#697]
Currently, the return code is 0 even when it detects an error:
```
root@6044a56f5186:/isolator#  calicoctl status
calico-node container not running
root@6044a56f5186:/isolator# echo $?
0
```

There should be a sensible way to tell if calico is healthy via calicoctl. 

Use Case: the Netmodules test framework will fail if it is executed before the `calico-node` container has started on the slave. Currently, we use an arbitrary 20 second delay to give calico-node time to launch. But it would be much more sensible to have it wait until `calicoctl status` gives a return code of 0 to ensure that it is up, running, and healthy, before starting the tests.

**Comment by spikecurtis** [comment]
+1
