### ISSUE TITLE
Re-vamp links from projectcalico.org to calico-containers

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#708]
The links from the projectcalico.org site (http://www.projectcalico.org/getting-started/) could do with a substantial re-work to better reflect the variety of options available in calico-containers.

**Comment by caseydavenport** [comment]
@eepyaich Are you the right assignee for this?

**Comment by djosborne** [comment]
This issue was moved to projectcalico/calico#62
