### ISSUE TITLE
Very confusing if calicoctl connects to wrong etcd

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#710]
Setting up a k8s cluster with skydns results in creating 3 etcd clusters.  Running calicoctl connects to the wrong one by default, so commands like `calicoctl endpoint show` show empty lists (but don't error out).  It'd be great if calicoctl could show a warning if it is connected to the wrong etcd. 

It'd be even better if there was a config file that we could drop in /etc as part of the set-up to ensure that calicoctl connects to the right etcd by default.

**Comment by robbrockbank** [comment]
@fasaxc What about adding something to your .bashrc or similar?

**Comment by robbrockbank** [comment]
I don't think it is possible to know it is connected to the wrong etcd.  The only thing we have to go on is the non-existence of the calico directory structure, of the existence of non-Calico directories.  However, both are perfectly valid - so we can't police against that.
