### ISSUE TITLE
ConfD should resolve hostnames

### ISSUE THREAD

**Issue by Calpicow** [projectcalico/calico-containers#712]
I'm getting a possible SSL verification error due to `calicoctl` resolving the hostname. My etcd is behind an ELB, so adding the IP to the cert itself is not viable.

Related code is below, but I've been notified that the underlying cause is ConfD not able to resolve hostnames.

https://github.com/projectcalico/calico-containers/blob/f76df7ad67296187c3b61129fc6c0eee5faf8371/calicoctl/calico_ctl/node.py#L328

**Comment by robbrockbank** [comment]
@Calpicow There is a suggestion on https://github.com/kelseyhightower/confd/issues/309 that I'd like to try.  I'll give that a go later this week.

**Comment by Calpicow** [comment]
Schema is already being appended to the node flag, so we could probably remove the `gethostbyname`.
https://github.com/projectcalico/calico-containers/blob/f76df7ad67296187c3b61129fc6c0eee5faf8371/calico_node/filesystem/etc/service/confd/run#L6

I'll try to rebuild with the change and see what happens.

**Comment by robbrockbank** [comment]
@Calpicow That's great news!  I'll take a look at the PR.

**Comment by robbrockbank** [comment]
Closing issue.  We now also have SSL tests that use hostname - so everything is looking good.
