### ISSUE TITLE
calico guessed wrong host IP address

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#713]
Following the k8s install instructions for Ubuntu, I started calico via systemd.  It used the wrong IP address for BGP, choosing the IP address on (I think) the `lxcbr0` device instead of the one on `eth0`.  

It's probably best if I make the instructions explicit about the IP anyway but I thought we had heuristics in place that should have done the right thing.

**Comment by TrimBiggs** [comment]
Is `lxcbr0` a kubernetes container bridge?

We have checks that ignore two bridge regexes at the moment if no IP is specified:
https://github.com/projectcalico/calico-containers/blob/master/calicoctl/calico_ctl/node.py#L276
`ips = get_host_ips(exclude=["^docker.*", "^cbr.*"])`

We do not exclude bridges in general at the moment, though we could be fancy here.  If `lxcbr0` is a recurring or common interface that we should ignore, then we should add it here.
