### ISSUE TITLE
How to forward a host port to a local container ip?

### ISSUE THREAD

**Issue by ThomasLohner** [projectcalico/calico-containers#726]
I'm following the [Calico as a Docker network plugin](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md) example with the [install instructions for DigitalOcean](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/DigitalOcean.md).

Container-to-conatiner communication works just fine with ```--ipip --nat-outgoing``` enabled. However i can't figure out how to forward a host port to a local container. i've added this according to the [faq](https://github.com/projectcalico/calico-containers/blob/master/docs/FAQ.md):

```
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j DNAT  --to 192.168.0.68:80

# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 felix-PREROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0
  479 33282 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 DNAT       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:192.168.0.68:80
```

But this doesn't work:

```
# curl <HOSTIP>
curl: (7) Failed to connect to  <HOSTIP> port 80: Connection refused

# curl -I 192.168.0.68
HTTP/1.1 200 OK
Date: Mon, 11 Jan 2016 09:35:09 GMT
Server: Apache/2.4.18 (Ubuntu)
Connection: close
Content-Type: text/html; charset=UTF-8
```

Any help pointing me in the right direction is appreciated.

**Comment by robbrockbank** [comment]
Hi @ThomasLohner.

You'll also need to ensure your profile is updated to allow this traffic.  It's a little trickier with the Docker network plugin example because the security profile is created "under-the-covers".  However it is fairly easy to locate the correct profile to update. The [Advanced Policy](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/AdvancedPolicy.md) for Calico as a Docker network plugin guide describes how to do this.

The [Advance Network Policy](https://github.com/projectcalico/calico-containers/blob/master/docs/AdvancedNetworkPolicy.md) guide contains a worked-example for the actual changes that need to be applied to the security profile.

Let me know how you get on.

Rob

**Comment by ThomasLohner** [comment]
Wohoo, thanks, i've got it almost.

profile is set up
```
# calicoctl profile show
+------------------------------------------------------------------+
|                               Name                               |
+------------------------------------------------------------------+
| 93235a8c34cda72744320efb491b7b1336d6c5993a1108aae6103e0a8dd94512 |
+------------------------------------------------------------------+

# calicoctl profile 93235a8c34cda72744320efb491b7b1336d6c5993a1108aae6103e0a8dd94512 rule show
Inbound rules:
   1 allow tcp to ports 80
   2 allow icmp type 8
Outbound rules:
   1 allow
```

nat rule is still in place:
```
# iptables -t nat -L -n -v
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 felix-PREROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   18   917 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    1    60 DNAT       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:192.168.0.69:80
```

I've double checked that ```<HOSTIP>``` is on eth0:
```
# ip a
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:01:98:cd:bd:01 brd ff:ff:ff:ff:ff:ff
    inet 169.254.226.98/16 brd 169.254.255.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet <HOSTIP>/20 brd <xxx> scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.19.0.43/16 brd 10.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::601:98ff:fecd:bd01/64 scope link
       valid_lft forever preferred_lft forever
```

now i can curl ```<HOSTIP>``` from outside
```
node3 # curl -I <HOSTIP-OF-Node-2>
HTTP/1.1 200 OK
Date: Mon, 11 Jan 2016 19:24:33 GMT
Server: Apache/2.4.18 (Ubuntu)
Connection: close
Content-Type: text/html; charset=UTF-8
```

but i still can't curl the ip from the same host:
```
node2 # curl <HOSTIP>
curl: (7) Failed to connect to <HOSTIP> port 80: Connection refused
```

Anyways, this is only cosmetics, i can do what i wanted to achieve. Thanks.

**Comment by frostynova** [comment]
@ThomasLohner The DNAT rule does not take effect on the same host. 

When you curl node2's ip on node2, Linux think this is a local connection, and will bypass the iptables rules. If you want to access it, you must use container ip directly.

**Comment by frostynova** [comment]
@ThomasLohner I just found another solution.

You can add a DNAT rule in NAT table OUTPUT chain like this:

iptables -t nat -I OUTPUT -p tcp -o lo --dport 80 -j DNAT --to-destination 192.168.0.68:80

**Comment by ThomasLohner** [comment]
@frostynova Adding both nat rules works like a charm! Thanks for your help.

@robbrockbank Should i add this to the docs or just close this issue?

**Comment by robbrockbank** [comment]
@ThomasLohner We always welcome updates to our documentation.  If you'd like to beef up the docs and raise a PR that would be awesome!

**Comment by robbrockbank** [comment]
Hi @ThomasLohner,

Just going through our issues.  Did you happen to make a docs update for this?  If so I can review and merge.

Thanks!
