### ISSUE TITLE
Documentation still refers to calico-docker instead of calico-containers

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-containers#732]
We need to do a search and replace at some point.

**Comment by robbrockbank** [comment]
This is largely done now - see #734.

Remaining issues:
-  The badges on the main README need updating - this will probably require new semaphore/circleCI/coveralls projects to be made (or the existing ones to be renamed).  Simply changing the name to calico-containers in the badge does not work.

**Comment by tomdee** [comment]
Since this relies on features of external CI systems that we can't change, and it doesn't really matter that the names are wrong, I'm just going to close this.
