### ISSUE TITLE
No way to configure MTU, for AWS, for example

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#743]
Our [docs](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/AWS.md) currently say that you need to configure the MTU to make AWS perform but they instructions they give are involved and require `nsenter`ing the container.

That's not acceptable!  We need a better way of configuring the MTU.  

A potential customer just hit this in their initial testing, giving a bad impression.

**Comment by fasaxc** [comment]
@robbrockbank I think this is with you

**Comment by robbrockbank** [comment]
@TrimBiggs Tim - what happened with this one?

**Comment by matthewdupre** [comment]
Closing as duplicate of #488.
