### ISSUE TITLE
Calico-Mesos RPM should install latest docker

### ISSUE THREAD

**Issue by AI-PaaS** [projectcalico/calico-containers#753]
https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/RpmInstallCalicoMesos.md,
I follow the above url to install mesos+calico, but we have to use docker 1.9.0. but the calico-mesos.rpm use docker 1.8, so how i do this?

**Comment by djosborne** [comment]
Hi @AI-PaaS - you should be fine simply upgrading docker to 1.9 after you've installed the RPM.

**Comment by djosborne** [comment]
Going forward, we should improve our install instructions for the Calico-Mesos RPM to add docker's yum repo to receive the latest docker, instead of using Centos' (which is typically out of date).

**Comment by AI-PaaS** [comment]
I followed these steps and wasn't successful:
 1. yum erase docker-engine,yum erase docker-selinux.
 2. install all calico-mesos rpms
 3. yum update, but there is no update for docker. In fact, I added the docker repo and i can installed docker 1.9
 4. then I erase the docker 1.8, some calico-mesos rpm also were erased.

so, the result is same as before according to the djosborne's  comment.
I need updated rpms which use the latest docker.

**Comment by AI-PaaS** [comment]
Hello, does the issue has any going on?

**Comment by djosborne** [comment]
I ran through your steps and found that calico-mesos' docker requirements make it is impossible to change the underlying docker engine to docker 1.9.

To fix this, we're aiming to include a new RPM in a calico-mesos release later this week that resolves calico's dependencies on docker.

**Comment by djosborne** [comment]
@AI-PaaS If you want to get your hands on this before the next release, I've built an RPM that doesn't require Centos' docker package installed. I've uploaded it here for early access: https://transfer.sh/hkwPQ/calico-mesos.rpm

If you are not installing this on a fresh system

1. Run `sudo yum list installed | grep docker`, and uninstall any packages listed with `sudo yum erase <package-name>`
2. Get the official docker 1.9 by following their [centos installation instructions](https://docs.docker.com/engine/installation/centos/)
3. Install the linked calico RPM.

Please do contact me on the mesos channel of our [Slack](https://calicousers-slackin.herokuapp.com/) if you need any assistance
