### ISSUE TITLE
Calicoctl Pool allows overlapping pools to be programmed

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-containers#802]
This currently allows you to program pools such as:
```
+----------------+---------+
|   IPv4 CIDR    | Options |
+----------------+---------+
| 10.10.10.0/24  |         |
| 10.10.10.0/25  |         |
| 10.10.10.0/26  |         |
+----------------+---------+
```

We currently reject all overlapping ranges in the `ip_pool_range_add` function called by `calicoctl pool range add <cidr_start> <cidr_end>`, but not in `ip_pool_add`.

Pools now must start/end at a `/26` prefix, meaning that any cider net smaller than `/26` is not allowed.  So any overlapping pool that is programmed either fully encapsulates the preprogrammed cidr or is fully encapsulated by the preprogrammed cidr.

If a new pool fully encapsulates another pool (such as adding `10.10.0.0/16` when `10.10.10.0/24` exists), we should either
- reject it
- remove old pool and accept new pool (this will require some changes to backend)
- add the not yet programmed remaining cidr(s) as separate pool(s)

If a new pool falls within an existing pool (such as adding `10.10.10.0/24` when `10.10.0.0/16` exists), just reject it.

**Comment by TrimBiggs** [comment]
I think we should simply reject a pool that overlaps. Starting on a fix for this now.

**Comment by tomdee** [comment]
How does this play with us saying 'you can assign public IP addresses to your containers'. Am I right in thinking that all containers need to have an IP that's in a pool?

**Comment by TrimBiggs** [comment]
Yes, you're right that IPs need to come from a pool. I'm not sure the relation between assigning public IPs and overlapping pools, though.  Can you elaborate?

**Comment by tomdee** [comment]
The problem is just with restricting the pool size - which is issue didn't introduce. So no relation. Nothing to see here. Carry on.
