### ISSUE TITLE
Update tests to use Docker 1.10

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#808]
We should be testing with Docker 1.10 now - need to update our STs to use Docker 1.10.  Also would be good to update our vagrant installs to start using Docker 1.10.

#652 covers updating our docs to describe the new Docker 1.10 feature to specify a container IP.

**Comment by TrimBiggs** [comment]
Fixed by https://github.com/projectcalico/libnetwork-plugin/pull/43 and #811
