### ISSUE TITLE
Docs comments for mesos setup

### ISSUE THREAD

**Issue by DaveLangridge** [projectcalico/calico-containers#809]
General:

- docs seem a bit vague - (e.g. confusion about mesos versions. ) This turned out to be OK - I followed the RPM instructions which used 0.26.
- There's some stuff on preparing master, then RPM install instructions for slave, but nothing about install and setup of mesos-master.
- Having set things up - I want to start some containers using mesos + calco. The section on using marathon is light on detail (e.g. if I create a container using the app.json given, does marathon create the network and profile that calico needs, or do I need to do anything with caliococtl). i.e. I could have done with a more detailed example of what to expect.

Detail:

- Section 1 of RPM install wgets a tar file, then tries to unpack a tgz
- Section 2 has MASTER=zk://<ZOOKEEPER_IP>:<ZOOKEEPER_PORT>, but the default config for the master in /etc/mesos/zk is zk://localhost:2181/mesos. I added /mesos to the end of the MASTER url on the slave, and the mesos-slave started (it failed without this).

**Comment by tomdee** [comment]
Dan is working on fixing these issue

**Comment by djosborne** [comment]
I'm going to close this out. We've been through quite a few overhaul's in our mesos docs / installation story, so this is fairly outdated.
