### ISSUE TITLE
Unit Tests produce Error after results output

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-containers#810]
After tests conclude and coverage is printed, this error is printed to screen:

```
Exception TypeError: TypeError("'NoneType' object is not callable",) 
in <bound method Client.__del__ of <etcd.client.Client object at 0x7fd395c26c10>> ignored
```

I narrowed it down to having something to do with importing connectors.client into the calicoctl files that are tested.

**Comment by matthewdupre** [comment]
Closing this since we expect these tests to be retired in the near future (nearer than this issue is old anyway!)
