### ISSUE TITLE
Node stop produces weird output

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#829]
```
core@calico-04 ~ $ calicoctl node stop
Failed to stop calico-node.service: Interactive authentication required.
Node stopped
```

Needs to be run as sudo, but the above output doesn't indicate that.

**Comment by caseydavenport** [comment]
I think this only occurs when running with a `calico-node.service` systemd unit

**Comment by TrimBiggs** [comment]
I think you're right about it being the `calico-node.service` systemd unit.  I believe the error output is from making the `systemctl` call without `sudo`.

**Comment by caseydavenport** [comment]
Yep it would (I tried it), but this issue is mostly about the fact that on one line we say "failed to stop" and the next line says "Node stopped".

Also, calicoctl is leaking output from the underlying systemctl commands.

We should probably: 
- Add an enforce_root() to this command so the above never occurs.
