### ISSUE TITLE
calicoctl node errors do not stop it from being run

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#833]
Two scenarios I spotted,

Running "calicoctl node" without sudo seems to be allowed - I thought we used to check that it was being run as sudo - has this changed?

Trying to start node with libnetwork with Docker 1.8.1 produces an error message about incorrect Docker version, but then still starts up the libnetwork plugin container.  Is this as expected?

**Comment by TrimBiggs** [comment]
I also thought we enforced root on the node start/stop commands, but it appears we haven't.  I added a PR to fix this.

We should `sys.exit(1)` if the docker version is incorrect.  I'm surprised we don't.

**Comment by TrimBiggs** [comment]
Problem here was that node was not checking/erroring out when the check_system output returned docker failures, only etcd failures.
