### ISSUE TITLE
Cannot start node when IPv6 is not enabled on OS.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#844]
When starting calicoctl node, exists complaining that IPv4 forwarding could not be enabled.

Looks like this is actually an IPv6 forwarding issue because IPv6 is not enabled on the customers OS.  We need to only try and enable forwarding if IPv6 is configured, and we need to fix the error message.

**Comment by TrimBiggs** [comment]
@robbrockbank Can this be closed now?

**Comment by robbrockbank** [comment]
Fixed by #846
