### ISSUE TITLE
KubernetesIntegration refer to non-existing file

### ISSUE THREAD

**Issue by niklaswik** [projectcalico/calico-containers#850]
The kubernetesintegration refers to non-existen calicoctl file.

wget http://www.projectcalico.org/builds/calicoctl 
--2016-03-07 12:14:07--  http://www.projectcalico.org/builds/calicoctl
Resolving www.projectcalico.org (www.projectcalico.org)... 64.91.234.195
Connecting to www.projectcalico.org (www.projectcalico.org)|64.91.234.195|:80... connected.                                                                                                  
HTTP request sent, awaiting response... 301 Moved Permanently                                                                                                                                
Location: https://projectcalico.org/builds/calicoctl [following]                                                                                                                             
--2016-03-07 12:14:08--  https://projectcalico.org/builds/calicoctl                                                                                                                          
Resolving projectcalico.org (projectcalico.org)... 64.91.234.195
Connecting to projectcalico.org (projectcalico.org)|64.91.234.195|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://projectcalico.org/builds/calicoctl/ [following]
--2016-03-07 12:14:08--  https://projectcalico.org/builds/calicoctl/
Reusing existing connection to projectcalico.org:443.
HTTP request sent, awaiting response... 404 Not Found
2016-03-07 12:14:09 ERROR 404: Not Found.

**Comment by caseydavenport** [comment]
@robbrockbank - Should we still expect the projectcalico.org download link to be active?  Are you the right person to look into this?

**Comment by tomdee** [comment]
The file is missing if a build fails. Builds are working now so the link works. It's only broken on master. If you look at the docs from the latest release, the link points at the released binary (and that link works).
