### ISSUE TITLE
Docs banner warning displayed incorrectly on 0.16 doc

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico-containers#858]
This page has a banner warning about being HEAD of source tree, but this is no longer true.  Also the banner links to 1.3 as the latest release(!).

https://github.com/projectcalico/calico-containers/blob/v0.16.0/docs/cni/kubernetes/VagrantCoreOS.md

**Comment by tomdee** [comment]
Hi lance, thanks for the bug report. We screwed up the docs banners on the 0.16 release. It's now fixed though and there have been two releases since which are fine. So closing.
