### ISSUE TITLE
Kubernetes CoreOS vagrant instructions failing

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-containers#872]
I just tried the virtualbox vagrant CoreOS kubernetes demo and it didn't work. My calico-02 host couldn't contact kubernetes-master. I'm not sure how it's meant to know what the IP for that host is?

**Comment by caseydavenport** [comment]
Did you find out what was wrong with this?  I will give it a shot and see if I get the same behavior.

**Comment by caseydavenport** [comment]
Looks like this is failing because it is using a special policy node image that is incompatible with the latest calicoctl version.

Will update shortly.
