### ISSUE TITLE
Assignment of IPIP tunnel IP requires IP pool to be created before starting the calico nodes

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#880]
Came across some code in the node startup that assigns an IP address to the IPIP tunnel.  Rough flow is:
-  Check IP Pools for IPIP enabled
-  Check if IP address is assigned to IPIP tunnel:
  -  If not, assign an IP from an IPIP pool
  -  If assigned, check if still in an IPIP pool.
    -  If not, unassign IP and reassign from IPIP pool.

There are a few issues with this processing:
-  It assumes the "IPIP" IP pool has been created before starting the node.  This may not necessarily be the case.  Sounds like we need to be handling IP Pool changes dynamically.
-  The releasing of the IP address is only done when the IP Pool is still valid.  We should actually always unassigns the IP address - the allocation block may still exist even if the pool has been deleted.
-  I'm not sure how this would work with calico libnetwork network plugin with docker default IPAM.  In this case, the IP Pools are created by the network driver in response to a network creation.  Docker actually handles the IP assignment from those pools (i.e. Docker actually owns these pools) and so we cannot assign addresses from those pools.  For libnetwork, it would require the user to create an IPIP IP Pool that is just used for the IPIP tunnel addresses, and importantly that this pool could not clash with a Docker assigned pool.

**Comment by robbrockbank** [comment]
May be another problem to solve alongside #716

**Comment by matthewdupre** [comment]
@robbrockbank Isn't this problem mostly moot (aside from the releasing part), since IPIPEnabled is only set when an IPIP pool is created?

**Comment by caseydavenport** [comment]
I think this has been fixed for a while.
