### ISSUE TITLE
Add new ETCD_ENDPOINTS option to documentation.

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico-containers#889]
We now support a new way to configure etcd's location: ETCD_ENDPOINTS (see #882).

This should be added to the documentation.

**Comment by matthewdupre** [comment]
(Really, we should mostly remove ETCD_AUTHORITY from our docs, replacing with ETCD_ENDPOINTS as needed.)

**Comment by djosborne** [comment]
This issue was moved to projectcalico/calico#64
