### ISSUE TITLE
How to get rid of orphaned endpoints?

### ISSUE THREAD

**Issue by ThomasLohner** [projectcalico/calico-containers#896]
If i understand correctly this was fixed in #507 but i can't figure out how to do it.

```
$ calicoctl endpoint show --detailed
+------------------------------------------------------------------+---------------+
|                           Endpoint ID                            |   Addresses   | 
+------------------------------------------------------------------+---------------+
| 788df8495c7f52c81b097764ee032778f513c74d8b46d6116bb8ec88e4967582 |  10.1.1.1/32  |
| 14e8c5c1b2a683d72eb835b59abfd37f64504603a12a3ec01e61cf7979704bca |  10.1.1.1/32  |
| 906e9f110084131d2bee6126bdbdf75a1b3ba602f2d508369329adc3f0175560 |  10.1.1.1/32  |
| b1fd0c837fda7468e914353a6d95b60ed5f20f66df8f83221bfe6120b0a3216b |  10.1.1.1/32  |
| d0f6c23fe896148eedf2ef13ba98c0254195716b1f5ad653dfb87334502c7a3b |  10.1.1.1/32  |
+----------------------+-----------------+-------------+----------------------------
```

The first endpoint belongs to a running container. All of the others don't even have existing containers anymore. I wonder why they weren't removed in the first place. I always did `docker rm ...`

Anyways, i tried to remove them like this:

```
$ sudo calicoctl container remove 14e8c5c1b2a683d72eb835b59abfd37f64504603a12a3ec01e61cf7979704bca

Container 14e8c5c1b2a683d72eb835b59abfd37f64504603a12a3ec01e61cf7979704bca was not found.
```

Any hints how to fix this?

---

My Setup:

```
$ calicoctl version
0.17.0-dev

$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
5642a44d93e7        calico/node-libnetwork:latest   "./start.sh"             5 days ago          Up 5 days                               calico-libnetwork
228e1ee4a80b        calico/node:latest              "/sbin/start_runit"      5 days ago          Up 5 days                               calico-node
```

**Comment by caseydavenport** [comment]
@ThomasLohner - The "Endpoint ID" isn't the right identifier to use for `calicoctl container remove` - you'll need the "container ID" for that.  If you're using Docker, I believe the workload ID in that output should be the container ID.  Could you give that a try?

**Comment by ThomasLohner** [comment]
Ok, i thought it would be the Container ID, because Workload ID ist always "libnetwork", here's one example:

```
+----------------------+-----------------+-------------+------------------------------------------------------------------+---------------+-------------------+------------------------------------------------------------------+--------+
|       Hostname       | Orchestrator ID | Workload ID |                           Endpoint ID                            |   Addresses   |        MAC        |                             Profiles                             | State  |
+----------------------+-----------------+-------------+------------------------------------------------------------------+---------------+-------------------+------------------------------------------------------------------+--------+
|        node01        |    libnetwork   |  libnetwork | d5d98c6b2263243e713cf0e2fe45eafa47927cb6626ed5a1e5f0f7114f2239f9 |  10.1.1.22/32 | EE:EE:EE:EE:EE:EE | 7b685cd2043b3d31d5b3673912d14a560bfd4cafef5a98bf21b67f280bbf5ec9 | active |

```

Also, the containers don't exist any more so i can't delete them in docker :-/

**Comment by TrimBiggs** [comment]
The `calicoctl container` commands should not be used when running Calico with libnetwork.  The `container add` and `container remove` commands are meant to be used when running docker without docker networking, where `add` and `remove` will add/remove Calico networking on the containers.

You can use the `calicoctl endpoint` commands instead with the endpoint id you found before.  The `calicoctl container endpoint remove` command should do the trick.

**Comment by ThomasLohner** [comment]
Thanks for clarifying `calicoctl container`.

As for removing endpoints, there's no such command:

```
$ ./calicoctl version
0.18.0-dev

$ ./calicoctl endpoint --help
Usage:
  calicoctl endpoint show [--host=<HOSTNAME>] [--orchestrator=<ORCHESTRATOR_ID>]
    [--workload=<WORKLOAD_ID>] [--endpoint=<ENDPOINT_ID>] [--detailed]
  calicoctl endpoint <ENDPOINT_ID> profile (append|remove|set) [--host=<HOSTNAME>]
    [--orchestrator=<ORCHESTRATOR_ID>] [--workload=<WORKLOAD_ID>]  [<PROFILES>...]
  calicoctl endpoint <ENDPOINT_ID> profile show [--host=<HOSTNAME>]
    [--orchestrator=<ORCHESTRATOR_ID>] [--workload=<WORKLOAD_ID>]
```

There's only `calicoctl endpoint <ID> profile remove` but i guess this is not what i'm looking for?

**Comment by fasaxc** [comment]
Another user reached out on the mailing list with this issue, it'd be good to have a solution.

**Comment by robbrockbank** [comment]
Hi @ThomasLohner,

The `calicoctl container remove` is only useful for containers that were networked using the `calicoctl container add` commands, and won't work for endpoints that have been created using Docker libnetwork.

The endpoints should be tidied up by the Calico Docker network plugin where you run `docker rm`, so i can only assume something is going wrong in the plugin and the endpoints are not being correctly tidied up.

Are you using both Calico network driver and Calico IPAM driver, or are you using the default Docker IPAM driver?

Would it be possible to send me the output from the following commands (PM me them if you'd prefer):

```
docker network inspect <network name>
docker logs calico-libnetwork
docker version
docker ps
```

**Comment by ThomasLohner** [comment]
I've upgraded calico so the logs won't be any good. I will try to reproduce and get you logs...

**Comment by frostynova** [comment]
We also met this problem

It occurs when docker daemon restarted, then the old endpoint become a dead one, neither libnetwork or calico can clean it.

I report more details on: https://github.com/projectcalico/libnetwork-plugin/issues/49

**Comment by ThomasLohner** [comment]
I can confirm this happens when docker daemon is restarted. Also Containers with fixed IPs (`docker run ... --ip=xxx`) refuse to restart after docker daemon was restarted:

```
Error response from daemon: Cannot restart container xxx: service endpoint with name xxx already exists
```

Only workaround is to manually kill etcd entries and release the ip from calico ipam:

```
$ calicoctl endpoint show --detailed | grep 10.1.12.10
| xxx |    libnetwork   |  libnetwork | 27d4e97367f2ec1810ada3dbf3ccb6f0127ccde00a51810de4d619f3ec5373fa | 10.1.12.10/32  | EE:EE:EE:EE:EE:EE | 3df319d886f321df3d250c526fb0c03540d8ad19776c800069c8c11ecf89475a | active |

$ etcdctl ls --recursive | grep 27d4e97367f2ec1810ada3dbf3ccb6f0127ccde00a51810de4d619f3ec5373fa
/calico/v1/host/xxx/workload/libnetwork/libnetwork/endpoint/27d4e97367f2ec1810ada3dbf3ccb6f0127ccde00a51810de4d619f3ec5373fa
/docker/network/v1.0/endpoint/3df319d886f321df3d250c526fb0c03540d8ad19776c800069c8c11ecf89475a/27d4e97367f2ec1810ada3dbf3ccb6f0127ccde00a51810de4d619f3ec5373fa

$ etcdctl rm /calico/v1/host/xxx/workload/libnetwork/libnetwork/endpoint/27d4e97367f2ec1810ada3dbf3ccb6f0127ccde00a51810de4d619f3ec5373fa

$ etcdctl rm /docker/network/v1.0/endpoint/3df319d886f321df3d250c526fb0c03540d8ad19776c800069c8c11ecf89475a/27d4e97367f2ec1810ada3dbf3ccb6f0127ccde00a51810de4d619f3ec5373fa

$ calicoctl ipam release 10.1.12.10

$ docker start xxx
```

All of this is also reported in projectcalico/libnetwork-plugin#49 and it totally makes sense that this is related to libnetwork-container being stopped before cleanup of endpoints happens. should we close the issue here?

**Comment by TrimBiggs** [comment]
Hi @ThomasLohner,

I think we should leave the issue open, we still like to keep this on our radar if we choose to fix it in a different way (like running the calico libnetwork plugin as a system service, rather than container). We'll keep an eye on Docker's comments about system containers here as well: https://github.com/docker/docker/issues/22239

**Comment by caseydavenport** [comment]
@robbrockbank - I believe we'll be adding this to the golang version of calicoctl.  Assigning to you for tracking - feel free to close if there is another issue tracking this!

**Comment by gunjan5** [comment]
@heschlie assigning this to you since you're already looking into removing endpoints

**Comment by heschlie** [comment]
This should now work in the go version of calicoctl, fixed in this PR for libcalico-go:

https://github.com/projectcalico/libcalico-go/pull/305
