### ISSUE TITLE
Very out-of-date Kubernetes + Fedora guide

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#911]
Not sure where it came from, but Kubernetes have a very out-of-date guide (using calicoctl v0.5.5) for setting up Calico with Kubernetes:

http://kubernetes.io/docs/getting-started-guides/fedora/fedora-calico/#install-calico 

Tripped up a user on IRC.

**Comment by caseydavenport** [comment]
Odd... I deleted that guide from the docs a month or so ago.

Kubernetes recently moved all of their docs to a new repo, so perhaps that deletion got lost in the process.

**Comment by pigmej** [comment]
Anyway, using cni way works on that fedora too (just tested, it was me who spoke with @fasaxc ). Just updated calico to 0.18.0 removed `--kubernetes` option and switched to `cni` instead.

**Comment by matthewdupre** [comment]
Guide has now disappeared: closing.
