### ISSUE TITLE
Ship a darwin `calicoctl`

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-containers#914]
Seen with the v0.18.0 version of calicoctl for mac.

```
illium:kube-cluster cd4$ calicoctl endpoint show
Traceback (most recent call last):
  File "<string>", line 68, in <module>
  File "/private/var/folders/5h/jyb4zy7n1wb6b2hvmc4px76r0000gp/T/pip-build-VuQPsV/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/bgp.py", line 36, in <module>
ImportError: cannot import name validate_asn
calicoctl returned -1
```

**Comment by TrimBiggs** [comment]
@caseydavenport, do you remember if this was a locally built `calicoctl` that you copied from your dev machine? I used an old machine recently and hit this error because my local repos were not in sync. Could this have been happening here?

**Comment by caseydavenport** [comment]
Nope, this was v0.18.0: https://github.com/projectcalico/calico-containers/releases/tag/v0.18.0

**Comment by caseydavenport** [comment]
Needs re-test with v0.21.0

**Comment by caseydavenport** [comment]
Looks like we haven't shipped a mac binary for the last couple of releases :(

**Comment by caseydavenport** [comment]
Repurposing this issue to cover shipping a mac version of calicoctl.
