### ISSUE TITLE
How should I config profile to let it get ip from a certain pool ? 

### ISSUE THREAD

**Issue by dongmx** [projectcalico/calico-containers#927]
I have several pools : 10.10.1.0/24; 10.10.2.0/24; 10.10.3.0/24.  And I want  profile A use  10.10.1.0/24, profile B use 10.10.2.0/24, others use 10.10.3.0/24. 

What should I do? I can't find any information from the documents. Thanks for your help!

**Comment by dongmx** [comment]
calicoctl version is v0.19.0

**Comment by TrimBiggs** [comment]
Are you using Calico as a Docker network plugin? As in, did you create networks with the `docker network` command with Calico as the driver?

**Comment by dongmx** [comment]
I am using Calico as a Docker network plugin. Thank you very much!

**Comment by dongmx** [comment]
This issue can be closed.

**Comment by TrimBiggs** [comment]
Happy to help! :)
