### ISSUE TITLE
Exceptions logged to stderr when felix tries to log to syslog

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#937]
Seen while scale testing k8s on coreOS.  I suspect these are benign because (from code reading) the logging framework catches the exception, logs it out and then continues.

```
@40000000571e0d450b28d1b4.s:Traceback (most recent call last):
@40000000571e0d450b28d1b4.s-  File "/usr/lib/python2.7/logging/handlers.py", line 864, in emit
@40000000571e0d450b28d1b4.s-    self.socket.sendto(msg, self.address)
@40000000571e0d450b28d1b4.s-  File "/usr/lib/python2.7/site-packages/gevent/_socket2.py", line 418, in sendto
@40000000571e0d450b28d1b4.s-    return sock.sendto(*args)
@40000000571e0d450b28d1b4.s-gaierror: [Errno -2] Name does not resolve
@40000000571e0d450b28d1b4.s-Logged from file frules.py, line 216
```

I think the default config for felix has it logging errors to syslog but I think coreOS doesn't run a syslog server by default (and maybe it's failing to resolve, say, "localhost") so whenever we log an error we'll hit the above traceback.  Perhaps we should just disable syslog logging by default in container-land?

**Comment by caseydavenport** [comment]
I think we do disable by default.  I don't ever see this unless I've explicitly enabled syslog.
