### ISSUE TITLE
calico-cni plugin leaks `/tmp/_MEIxxx` directories after failure

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#942]
We use `pyinstaller` to pack calico CNI; when the `calico` command is run, pyinstaller unpacks a copy of the code and libraries to `/tmp/_MEIxxx`.  If the `calico` command dies or is killed, those temporary files are left in place leaking 10-20MB.

**Comment by lxpollitt** [comment]
cc/ @tomdee: Time for a golang version of the our CNI plugin?  ;-)

**Comment by fasaxc** [comment]
That sounds sensible to me, it seems to be a bit of pain to package python for coreOS.  Either that, or ship the CNI plugin inside calico-node (or its own container) and exec it inside there.

I also had a crack at running the CNI plugin as a one-dir pyinstaller build to see if it reduced its CPU load/startup time vs the one-file option.  It does seem to (load average is 15 rather than 20 in my test) and ping times are 20-30% better.  (Caveat: these are numbers captured in GCE so there's quite a big variation between runs anyway.)

**Comment by caseydavenport** [comment]
v1.4.0 CNI plugin is written in Golang so this issue can be closed :)
