### ISSUE TITLE
After rebooting kubernetes host, routes don't use IPIP tunnel

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#947]
Running Casey's scale test with only a couple of hosts, one NGINX pod and 199 getter pods.  I rebooted the k8s host that had the NGINX pod on it.  Kubernetes recovered, recreated the pods etc but the getters on the non-rebooted host started logging timeouts even after the NGINX pod was restarted.

Investigating, I found

- iptables rules all looked OK
- on the getter's host, the outgoing packets were exiting the tunl0 device, as expected but I didn't see any responses
- on the NGINX's host, packets were arriving over the tunl0 device
- checking `ip route get <getters IP>`, I get
```
$ ip route get 192.168.218.66
192.168.218.66 via 10.240.0.1 dev ens4v1  src 10.240.0.10 
    cache 
```

which is wrong.  The route should look like the following, to send the traffic down the tunnel (this is what I see on the getter's host when I query the route to the NGINX pod):

```
$ ip route get 192.168.7.25  
192.168.7.25 via 10.240.0.10 dev tunl0  src 192.168.216.128 
    cache  expires 599sec mtu 1440
```

I saw this yesterday after one of my hosts rebooted due to kernel panic then managed to repro today.

CC @caseydavenport

**Comment by fasaxc** [comment]
Restarting bird didn't insert the correct routes but if I manually delete one of the routes then bird inserts the correct route in its place.

Perhaps bird is being started before the tunnel device is configured properly so it does the wrong thing; then it doesn't have appropriate code to diff the route and correct it?

**Comment by fasaxc** [comment]
May be related to #716?

**Comment by aleks-v-k** [comment]
Here I have tried to fix the isuue: https://github.com/projectcalico/calico-bird/pull/21
Please, look at the patch. I hope it is acceptable.

**Comment by fasaxc** [comment]
Thanks @aleks-v-k, I'll get that reviewed.
