### ISSUE TITLE
How to set a static ip for docker container by used calico?

### ISSUE THREAD

**Issue by flyer5200** [projectcalico/calico-containers#953]
How to set a static ip for docker container by used calico?

In Multi-Host environment, how to keep a static ip for docker container?

**Comment by fasaxc** [comment]
@flyer5200 That depends; are you using docker with or without libnetwork?

**Comment by tweakmy** [comment]
I have use case using static ip using kubernetes. How can static allocation be done via cni?

**Comment by caseydavenport** [comment]
@tweakmy - The Calico CNI plugin supports assigning a static IP by passing in the `IP` CNI_ARG - see here: https://github.com/projectcalico/calico-cni/blob/master/configuration.md#ipam

However, you can't do this in Kubernetes.  Kubernetes doesn't provide a way to do this (it goes against core Kubernetes principles).  

The [PetSet](https://github.com/kubernetes/kubernetes/pull/18016) object (to be introduced in v1.3) will add some support for "nominal services" - this might be what you're looking for.  

Could you give a bit more detail about your use-case?
