### ISSUE TITLE
k8s scale: pods fail to start at high scale

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#957]
Running 670 GCE compute hosts (tried to run 1000 but the startup failed) with a 5-node etcd cluster (16-core instances).  Tried scaling the getter RC to 30k pods but virtually no pods came up (about 6 of 10k by the time I stopped the test).

Digging into the logs, felix and the CNI plugin were both failing to access etcd with `Raft Internal Error : etcdserver: request timed out`.  This was causing resyncs in felix and IPAM failures in the plugin.

Load on the hosts seemed normal (<1 or 4 cores active).  All etcd hosts were heavily loaded, with 8 (of 16) cores active.

I suspect we reached a tipping point where the load on etcd makes it unlikely that any CNI invocation will succeed.  Since k8s response to CNI failures is to retry, while also increasing the number of pods it's trying to start, we have a problem.

**Comment by fasaxc** [comment]
Felix sees a very variable event rate.  Mostly low 10-30/s but towards the end of the test, it looked like it peaked at 160/s.  With the timeouts, felix was resyncing so I compared the difference between etcd indexes at the different resync times.  Much of the etcd traffic could have been outside the tree that felix is monitoring.

**Comment by caseydavenport** [comment]
@fasaxc we've since done numerous tests of k8s above the scale mentioned in this issue.  Can this be closed?

**Comment by fasaxc** [comment]
I think so, didn't we track it down to IPAM contention, which we've now resolved?
