### ISSUE TITLE
How calico recycle ip

### ISSUE THREAD

**Issue by nashasha1** [projectcalico/calico-containers#959]
If I remove a container which calico has allocated an IP( Let's asume it is 192.168.0.1)，how can I recycle this Ip? I find this ip will never allocate to other containers. 

Or if one of the nodes in cluster die and never recover back. How recycle it's ips?

**Comment by fasaxc** [comment]
@nashasha1 We do recycle IPs as long as the container is correctly removed from Calico.  What orchestrator/calico plugin are you using, or are you using `calicoctl container add` to network containers manually?

**Comment by nashasha1** [comment]
Yes I'm using `calicoctl container add`, I'm wondering if I `docker rm -f container-id` manually not from Calico. How this ip recycle?

**Comment by fasaxc** [comment]
If you use the manual `calicoctl container add` then you also have to manually remove the container from calico before you delete it with `calicoctl container remove`.

We provide plugins for docker and other orchestrators to make that automatic.

**Comment by nashasha1** [comment]
Thank you again! @fasaxc . I will close this issue.
