### ISSUE TITLE
Create docker network fail!

### ISSUE THREAD

**Issue by nashasha1** [projectcalico/calico-containers#961]
Hi guys:

Working with [This link](https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/UsageGuideDockerContainerizer.md).

Can't create network databases success.

I have run `calico/node-libnetwork:latest` and `calico/node:latest` and `etcd` 

```
root@10-9-40-246:~# docker  ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
ea5d1aa0df84        calico/node-libnetwork:latest         "./start.sh"             18 minutes ago      Up 18 minutes                                                                            calico-libnetwork
7f4944de704c        calico/node:latest                    "/sbin/start_runit"      18 minutes ago      Up 18 minutes                                                                            calico-node
49166b8e6c02        index.alauda.cn/xdzhang/etcd:latest   "/etcd -name etcd0 -a"   30 minutes ago      Up 30 minutes       0.0.0.0:2379-2380->2379-2380/tcp, 0.0.0.0:4001->4001/tcp, 7001/tcp   etcd
```

after I run `docker network create --driver=calico --ipam-driver=calico databases`

get nothing

```
root@10-9-40-246:~# docker network create --driver=calico --ipam-driver=calico databases
7a54bcc7f88d8184d7599f5c240d17c1f73764a42dc2d715a42b0a4926554837
root@10-9-40-246:~# docker network ls
NETWORK ID          NAME                DRIVER
bb414f8646df        none                null
f7b847c49748        host                host
2ac657422781        bridge              bridge
```

Did I miss sth?

Thank you!~

**Comment by TrimBiggs** [comment]
Hi @nashasha1,

It looks like you may have missed the step to set Docker's `--cluster-store` parameter (this is a docker requirement to use Docker libnetwork).  This is covered in our [Calico as a Docker Networking Plugin guide](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/ManualSetup.md#docker). We link to this setup from within the Calico with the Docker Containerizer Manual Install guide, which is where you likely followed instructions for getting `calicoctl` onto your machine.

Let me know if this helps!

**Comment by nashasha1** [comment]
@TrimBiggs  Thank you for your reply. 

After I set Docker's `--cluster-store` parameter, network can create as expect.

But another issue occurred.

When I run `docker  run -d --name=c1 --net=databases tutum/ubuntu:latest`

response:

```
root@10-9-59-120:~# docker  run -d --name=c1 --net=databases tutum/ubuntu:latest
4ce9ffbdc3432a233c0f9f159594bc379c7bb7b58001511a499b9ef1c7c7af4f
Error response from daemon: Cannot start container 4ce9ffbdc3432a233c0f9f159594bc379c7bb7b58001511a499b9ef1c7c7af4f: failed to create endpoint c1 on network databases: Plugin Error: NetworkDriver.CreateEndpoint, {
  "Err": "'LibnetworkDatastoreClient' object has no attribute 'get_default_next_hops'"
}
root@10-9-59-120:~#
```

My calicoctl version

```
root@10-9-59-120:~# ./calicoctl version
0.19.0-dev
```

My Docker info:

```
root@10-9-59-120:~# docker  info
Containers: 3
Images: 30
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: 10-9-59-120
ID: T3IG:4TLW:YAZA:UYHV:MLE2:NC3R:7LBI:PN2W:WPOI:QQBZ:QCFD:5ESW
WARNING: No swap limit support
Cluster store: etcd://10.9.40.246:2379
```

Any idea about this.

Thanks!~

**Comment by djosborne** [comment]
Sounds like you hit a bug in our latest ibnetwork image: #966 

You're using the 0.19.0-dev calicoctl, which is built from master and pulls master images for libnetwork and calico-node. In projectcalico, master images are not guaranteed to be bug free. Releases are!

Try downloading calicoctl from the 19 release: https://github.com/projectcalico/calico-containers/releases/tag/v0.19.0
If you rerun `calicoctl node --libnetwork`, it will pull stable images.

**Comment by nashasha1** [comment]
@djosborne  Thank you very much.Release version work well.
