### ISSUE TITLE
calico cannot work on host without ipv6 support

### ISSUE THREAD

**Issue by saiwl** [projectcalico/calico-containers#968]
i did the steps as the calico-without-docker-net.
the host doesn't have ipv6 support, i think it doesn't matter.
ip a command shows:

508: calia0163956134@if507: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 2e:7f:8f:94:ee:d7 brd ff:ff:ff:ff:ff:ff

ip ro command shows no route to the cali interface.
but i tried on another host with ipv6, all is ok.

**Comment by fasaxc** [comment]
@saiwl what version of calico and calicoctl are you using?  We added support for running without IPv6 support in v0.18.0.

**Comment by saiwl** [comment]
@fasaxc Thanks for your reply.
calicoctl version
0.19.0

calico/node:v0.19.0

I just check the log of felix, there is error about net.ipv4.conf.all.rp_filter config. Original value is 2, maybe it's caused by this? I am going to change it to 1 and try again.

**Comment by fasaxc** [comment]
@saiwl yes, Calico requires strict RP filtering to maintain security (otherwise containers can spoof each other).

Closing for now, please re-open if you're still hitting issues.
