### ISSUE TITLE
calicoctl doesn't tell me the allowed syntax for a port range 

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico-containers#969]
Here are what I think are 3 reasonable attempts to discover or guess this:

```
ubuntu@calico-vm10:~$ ./calicoctl profile IPERF rule add inbound
Usage:
  calicoctl profile show [--detailed]
  calicoctl profile add <PROFILE>
  calicoctl profile remove <PROFILE> [--no-check]
  calicoctl profile <PROFILE> tag show
  calicoctl profile <PROFILE> tag (add|remove) <TAG>
  calicoctl profile <PROFILE> rule add (inbound|outbound) [--at=<POSITION>]
    (allow|deny) [(
      (tcp|udp) [(from [(ports <SRCPORTS>)] [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
                [(to   [(ports <DSTPORTS>)] [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])] |
      icmp [(type <ICMPTYPE> [(code <ICMPCODE>)])]
           [(from [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
           [(to   [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])] |
      icmpv6 [(type <ICMPTYPE> [(code <ICMPCODE>)])]
             [(from [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
             [(to   [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])] |
      [(from [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
      [(to   [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])]
    )]
  calicoctl profile <PROFILE> rule remove (inbound|outbound) (--at=<POSITION>|
    (allow|deny) [(
      (tcp|udp) [(from [(ports <SRCPORTS>)] [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
                [(to   [(ports <DSTPORTS>)] [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])] |
      icmp [(type <ICMPTYPE> [(code <ICMPCODE>)])]
           [(from [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
           [(to   [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])] |
      icmpv6 [(type <ICMPTYPE> [(code <ICMPCODE>)])]
             [(from [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
             [(to   [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])] |
      [(from [(tag <SRCTAG>)] [(cidr <SRCCIDR>)])]
      [(to   [(tag <DSTTAG>)] [(cidr <DSTCIDR>)])]
    )])
  calicoctl profile <PROFILE> rule show
  calicoctl profile <PROFILE> rule json
  calicoctl profile <PROFILE> rule update
ubuntu@calico-vm10:~$ ./calicoctl profile IPERF rule add inbound allow tcp to ports 39040:39080
ValueError: invalid literal for int() with base 10: ''

Traceback (most recent call last):
  File "<string>", line 145, in <module>
  File "calico_ctl/profile.py", line 180, in profile
  File "calico_ctl/profile.py", line 134, in validate_arguments
  File "site-packages/pycalico/util.py", line 123, in validate_ports
ValueError: invalid literal for int() with base 10: ''
ubuntu@calico-vm10:~$ ./calicoctl profile IPERF rule add inbound allow tcp to ports 39040-39080
Invalid SRCPORTS or DSTPORTS specified.
ubuntu@calico-vm10:~$ 
```

In all three cases, the output that I get does not tell me what the correct syntax is (or whether a port range is allowed at all).

**Comment by neiljerram** [comment]
From code reading it appears that the correct syntax is <lower>:<higher>, and the code for handling that looks correct to me.  I can't work out why I'm getting the traceback and ValueError as shown above.

**Comment by caseydavenport** [comment]
Hmm, I think that code is bugged.  Look here: https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/util.py#L120

It's iterating the given `port_list`, but in your case the port list is actually a `string` "39040:39080", so it's going to go through that string one character at a time.  When it gets to the `:` character, it does this:

```python
>>> ":".split(":")
['', '']
>>>
```

and then:
```
>>> int(":".split(":")[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: ''
```

**Comment by neiljerram** [comment]
Thanks @caseydavenport .  I thought that port_list would be passed as a list with a single item, i.e.:

    ["39040:39080"]

and for that case I believe the code is correct.  I also tried adding a case

        (['39040:39080'], True),

to the parameters for test_validate_ports in test_util.py, and that passed.

**Comment by neiljerram** [comment]
But if I change that test case to

        ('39040:39080', True),

I get the same traceback as I reported above, so confirming your theory I think.  So then perhaps the problem is in the code that calls validate_port.

**Comment by neiljerram** [comment]
Well no, not really, the caller always calls it with a single arg, being the word from the command line.

    for arg in ["<SRCPORTS>", "<DSTPORTS>"]:
        if arguments.get(arg) is not None:
            ports_ok = validate_ports(arguments[arg])
            if not ports_ok:
                break

So validate_ports is bugged as you say.  I'll look at a fix.

**Comment by neiljerram** [comment]
Addressed by https://github.com/projectcalico/libcalico/pull/111 and https://github.com/projectcalico/calico-containers/pull/972.

**Comment by neiljerram** [comment]
(It appears that there are other contexts that use validate_ports to validate port values from etcd; and the validate_ports is correct for that case.  Therefore I believe the right fix is to introduce and use a different validation function for the port specs that can be specified on the calicoctl command line.)
