### ISSUE TITLE
Network created from agent  nodes does not  show profile created

### ISSUE THREAD

**Issue by ajaybhatnagar** [projectcalico/calico-containers#971]
When I create a network from agent node, it does not create the network and profile is not displayed. When same command executed on node running ETCD, it displays correctly on the node but not on other agent nodes running docker/mesos-slaves. See the output below. Am I missing any step ?  Following the instructions on page: 

https://github.com/projectcalico/calico-containers/blob/master/docs/mesos/UsageGuideDockerContainerizer.md

Calicoctl version 0.19. OS Ubuntu 14.04. Docker version 1.11.1, build 5604cbe

On Agent node:
```
root@mesos-s1:~# docker network create --driver calico --ipam-driver calico databases
842df4c0d7d95c88b3168e208bf3d7982da2a5fda0a6f851b23fef279ec5d798
root@mesos-s1:~# calicoctl profile databases rule show
Profile databases not found.
```
When created on ETCD node:
```
docker network create --driver calico --ipam-driver calico databases
0f0423092cf80a522b10dafa36d6993ca1a72e07dbfa3030305f7155243cbf54
root@calico-00:~# docker network ls
NETWORK ID          NAME                DRIVER
a8cc24170511        bridge              bridge
0f0423092cf8        databases           calico
368028c114c9        host                host
157a128667fe        net1                calico
60902bc22727        net2                calico
2b53833726d7        net3                calico
994655944bc6        none                null
root@calico-00:~# calicoctl profile databases rule show
Inbound rules:
   1 allow from tag databases
Outbound rules:
   1 allow
```
Try to see the profile from agent node:
```
root@mesos-s1:~# calicoctl profile databases rule show
Profile databases not found.
root@mesos-s1:~# env|grep ETCD
ETCD_AUTHORITY=10.236.133.87:2379
```

On ETCD node:
```
root@calico-00:~# calicoctl status
calico-node container is running. Status: Up 24 hours
Running felix version 1.4.0rc1

IPv4 BGP status
IP: 172.18.0.1    AS Number: 64511 (inherited)
+----------------+-------------------+-------+------------+------------------------------------------------+
|  Peer address  |     Peer type     | State |   Since    |                      Info                      |
+----------------+-------------------+-------+------------+------------------------------------------------+
| 10.236.133.88  | node-to-node mesh | start | 2016-05-05 | Active        Socket: Connection reset by peer |
| 10.236.133.89  | node-to-node mesh | start | 2016-05-05 | Active        Socket: Connection reset by peer |
| 10.236.133.90  | node-to-node mesh | start | 2016-05-05 | Active        Socket: Connection reset by peer |
| 10.236.133.168 | node-to-node mesh | start | 2016-05-05 | Active        Socket: Connection reset by peer |
| 10.236.133.169 | node-to-node mesh | start | 2016-05-05 | Active        Socket: Connection reset by peer |
| 10.236.133.170 | node-to-node mesh | start | 2016-05-05 | Active        Socket: Connection reset by peer |
+----------------+-------------------+-------+------------+------------------------------------------------+

IPv6 BGP status
No IPv6 address configured.
```

On agent Node:
```
oot@mesos-s1:~# calicoctl status
calico-node container is running. Status: Up 45 hours
Running felix version 1.4.0rc1

IPv4 BGP status
IP: 10.236.133.168    AS Number: 64511 (inherited)
+----------------+-------------------+-------+------------+-------------------------------------------+
|  Peer address  |     Peer type     | State |   Since    |                    Info                   |
+----------------+-------------------+-------+------------+-------------------------------------------+
| 10.236.133.88  | node-to-node mesh |   up  | 2016-05-04 |                Established                |
| 10.236.133.89  | node-to-node mesh |   up  | 2016-05-04 |                Established                |
| 10.236.133.90  | node-to-node mesh |   up  | 2016-05-04 |                Established                |
| 10.236.133.169 | node-to-node mesh |   up  | 2016-05-04 |                Established                |
| 10.236.133.170 | node-to-node mesh |   up  | 2016-05-04 |                Established                |
|   172.18.0.1   | node-to-node mesh | start | 2016-05-05 | Connect       Socket: Operation timed out |
+----------------+-------------------+-------+------------+-------------------------------------------+

IPv6 BGP status
No IPv6 address configured.
```

**Comment by TrimBiggs** [comment]
Hi @ajaybhatnagar,

I've got a few questions for you to get a better understanding.
Can you tell me a bit more about your cluster configuration? Are you using calico with DCOS? Are you using a cloud service?

**Comment by ajaybhatnagar** [comment]
Hi Trim
I am not using DCOS. It is private cloud KVM setup with no firewall between nodes.
On further investigation I found network is not up on docker0 interface on both etcd and agent nodes. See below:
On ETCD node:

root@calico-00:~# ping 172.17.0.1
PING 172.17.0.1 (172.17.0.1) 56(84) bytes of data.
64 bytes from 172.17.0.1: icmp_seq=1 ttl=64 time=0.035 ms

root@calico-00:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
,..
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c9:54:0a:dd brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: br-0d50a3712632: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 02:42:f5:d4:12:b4 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global br-0d50a3712632
       valid_lft forever preferred_lft forever


On agent node:

root@mesos-s1:~# ping 172.17.0.1
PING 172.17.0.1 (172.17.0.1) 56(84) bytes of data.
64 bytes from 172.17.0.1: icmp_seq=1 ttl=64 time=0.040 ms

root@mesos-s1:~# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.236.132.1    0.0.0.0         UG        0 0          0 eth0
10.236.132.0    0.0.0.0         255.255.252.0   U         0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.0.2     10.236.133.88   255.255.255.255 UGH       0 0          0 eth0
192.168.0.3     10.236.133.90   255.255.255.255 UGH       0 0          0 eth0
192.168.0.4     10.236.133.89   255.255.255.255 UGH       0 0          0 eth0
root@mesos-s1:~#  ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
... 
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:80:45:1b:a2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever

**Comment by TrimBiggs** [comment]
The `docker0` interface does not need to be up for it to work.

I'm not sure what's going on here. It seems like you are not longer connected to etcd, but if you have your etcd_authority set correctly then that shouldn't be the case.

Are you still seeing this behavior?

One configuration issue I'm seeing is that you have a peer node in your `calicoctl status output` on the agent that claims that a node was started with `172.18.0.1`, which would fail because that is the IP address of of your bridge, rather than the machine's IP. This shouldn't affect the agent being unable to reach ETCD though.

Can you try running on the agent a simple curl of etcd (`curl -L http://$ETCD_AUTHORITY/version`) or an `etcdctl ls`?

**Comment by ajaybhatnagar** [comment]
Thanks Trim. Issue was caused by additional Docker options that need to be specified in environment.

**Comment by SlevinBE** [comment]
Hi @ajaybhatnagar, can you clarify which options you had to specify to make this work? I think I'm running into the same issue.

**Comment by ajaybhatnagar** [comment]
Need to set DOCKER_OPTS="--cluster-store=etcd://<ETCD_SERVER_IP_ADDRESS>:<ETCD_PORT>"

and also export environment variable ETCD_AUTHORITY=<ETCD_SERVER_IP_ADDRESS>:<ETCD_PORT>

**Comment by ajaybhatnagar** [comment]
Missed info in previous update.
Need to set DOCKER_OPTS="--cluster-store=etcd://ETCD_SERVER_IP_ADDRESS:ETCD_PORT

and also export environment variable ETCD_AUTHORITY=ETCD_SERVER_IP_ADDRESS:ETCD_PORT
