### ISSUE TITLE
zombie ip occur when stop calico container

### ISSUE THREAD

**Issue by nashasha1** [projectcalico/calico-containers#973]
I'm doing some test about [Calico as a Docker network plugin](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md)

Some edge test result:

1、shut down one of nodes. calico work well.
before
```
root@10-9-36-153:~# ./calicoctl endpoint show --detailed
+-------------+-----------------+-------------+------------------------------------------------------------------+----------------+-------------------+------------------------------------------------------------------+--------+
|   Hostname  | Orchestrator ID | Workload ID |                           Endpoint ID                            |   Addresses    |        MAC        |                             Profiles                             | State  |
+-------------+-----------------+-------------+------------------------------------------------------------------+----------------+-------------------+------------------------------------------------------------------+--------+
| 10-9-36-153 |    libnetwork   |  libnetwork | 44d7202c50b0dbfcbe7e69f92d48a4ea1ceab9061642f6e6412080078d722dfb | 192.168.0.4/32 | EE:EE:EE:EE:EE:EE | e4e09df8b5517f82b67cbe5564912cfbb135adfe7e0a74006abf242797d1977e | active |
| 10-9-36-153 |    libnetwork   |  libnetwork | c1ba450544bb069ad53fd94d78e7bd62c7a8db67aee3a22ef0d1294fa5760025 | 192.168.0.2/32 | EE:EE:EE:EE:EE:EE | e4e09df8b5517f82b67cbe5564912cfbb135adfe7e0a74006abf242797d1977e | active |
| 10-9-42-141 |    libnetwork   |  libnetwork | e341d6d1321ac5485564e756cd480914e59f2002bfac1005345425a36a1d93f2 | 192.168.0.3/32 | EE:EE:EE:EE:EE:EE | e4e09df8b5517f82b67cbe5564912cfbb135adfe7e0a74006abf242797d1977e | active |
+-------------+-----------------+-------------+------------------------------------------------------------------+----------------+-------------------+------------------------------------------------------------------+--------+
```

after
```
root@10-9-36-153:~# ./calicoctl endpoint show --detailed
+-------------+-----------------+-------------+------------------------------------------------------------------+----------------+-------------------+------------------------------------------------------------------+--------+
|   Hostname  | Orchestrator ID | Workload ID |                           Endpoint ID                            |   Addresses    |        MAC        |                             Profiles                             | State  |
+-------------+-----------------+-------------+------------------------------------------------------------------+----------------+-------------------+------------------------------------------------------------------+--------+
| 10-9-36-153 |    libnetwork   |  libnetwork | 44d7202c50b0dbfcbe7e69f92d48a4ea1ceab9061642f6e6412080078d722dfb | 192.168.0.4/32 | EE:EE:EE:EE:EE:EE | e4e09df8b5517f82b67cbe5564912cfbb135adfe7e0a74006abf242797d1977e | active |
| 10-9-36-153 |    libnetwork   |  libnetwork | c1ba450544bb069ad53fd94d78e7bd62c7a8db67aee3a22ef0d1294fa5760025 | 192.168.0.2/32 | EE:EE:EE:EE:EE:EE | e4e09df8b5517f82b67cbe5564912cfbb135adfe7e0a74006abf242797d1977e | active |
+-------------+-----------------+-------------+------------------------------------------------------------------+----------------+-------------------+------------------------------------------------------------------+--------+
```

2、stop calico container `calico-libnetwork` `calico-node` then start them work well. Ip will not release.

3、stop calico container then stop other container(let's name it A it's ip is 192.168.0.6/32) then start calico container then start A, zombie ip occur

calico will not remove old ip (192.168.0.6/32) and will give A a new ip. So 192.168.0.6/32 will never be recycled. Right?

**## How can I recycle this ip from calico cluster?**

calico version

```
root@10-9-36-153:~# ./calicoctl version
0.19.0
```

docker version

```
root@10-9-36-153:~# docker info
Containers: 5
Images: 50
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: 10-9-36-153
ID: DAAM:DZWR:J45Q:SRIL:E5W5:HKHU:M76L:HQ46:FRG5:24FO:B7NE:XB3P
WARNING: No swap limit support
Cluster store: etcd://10.9.56.73:2379
```
Thanks.

**Comment by TrimBiggs** [comment]
Hi @nashasha1 

There are a couple of things going on here.  I think the behavior you're seeing is correct, but it works slightly differently than what you've mentioned.

Calico will assign the *least*-recently used IP address to a container, so if you just stopped or removed a container with IP 192.168.0.6, that IP address will not be used next since it is now the *most*-recently used IP address.

Since you are using Calico as a Docker network plugin, you do have the option of specifying a static IP address when you start a container.  Take a look at the [Assign Static IP when Starting a Container section](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md#assign-static-ip-when-starting-a-container) of the Calico as a Docker Network Plugin guide that you mentioned to learn how to do this.

There is also a known bug due to a limitation with Docker's network plugin options where [stopping the docker daemon does not correctly remove calico-networked containers' config](https://github.com/projectcalico/libnetwork-plugin/issues/49). I *don't think* this is what you're seeing, but it may be helpful to have a look.

Does that help solve your issue?

**Comment by nashasha1** [comment]
Thanks @TrimBiggs . That is helpful.

**Comment by nashasha1** [comment]
I have an another question.
When I  use Calico as a Docker network plugin, what should I do if I want add multi-pool and multi-profile.  When I create a docker network(With calico IPAM), It seems I can't specify which pool and profile for this network. 

Thank you!~

**Comment by TrimBiggs** [comment]
You ***can*** specify the pool for a Docker network.

The link that I posted for the [Assign Static IP when Starting a Container section](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md#assign-static-ip-when-starting-a-container) shows how to create a new pool with `calicoctl`, set the pool to be used by a new Docker network, then assign a static IP address using that pool (which isn't required, but is a nice feature).  This allows you to set a pool to only be used by a specific Docker network.

**Comment by nashasha1** [comment]
That's great. Thank you very much! @TrimBiggs  I will try this later.

**Comment by nashasha1** [comment]
hi @TrimBiggs . I test this with `docker version 1.11.1`. It works well. Thank you very much.
