### ISSUE TITLE
Can't ping container in vm

### ISSUE THREAD

**Issue by nashasha1** [projectcalico/calico-containers#974]
When I login in VM-A ,I can only ping successfully the containers in VM-A. I can't ping other VMs' container. Is this a correct behavior?

Any container can ping any VM successfully.

This can reproduce either `Calico as a Docker network plugin` or `Calico without Docker networking` 

How can I make the containers and vms can communicate each other?
calico version

```
root@10-9-36-153:~# ./calicoctl version
0.19.0
``` 

Did I miss sth?

**Comment by natostanco** [comment]
felix iptables ultimately drop all the traffic that does not match `felix-to-*`rules and apparently calico nodes ips are not included in the whitelist? I can add something like:
`iptables -I FORWARD -s 10.2.0.139 -j ACCEPT` where the ip is the ip of a calico node but these rules get cleaned up on each container run so how do you whitelist nodes with calico?

**Comment by frostynova** [comment]
By default, Containers managed by Calico with the same Profile can communicate with each other , So first check if their are in the same Profile.

Another point is be sure  Iptables `FORWARD` chain default policy is not `DROP` or `REJECT` (or there is a rule doing the same thing).

**Comment by nashasha1** [comment]
@frostynova  Thank you for your reply.
I mean I can't Ping other VMs' container when I'm in VM-A(Not VM-A's containers). Any idea about this?

eg: VM-A(10.9.51.159) run container C1(192.168.0.0) VM-B(10.9.54.162) run container C2(192.168.0.64)

VM-A can ping C1
```
root@10-9-51-159:~# ping 192.168.0.0
PING 192.168.0.0 (192.168.0.0) 56(84) bytes of data.
64 bytes from 192.168.0.0: icmp_seq=1 ttl=64 time=0.042 ms
64 bytes from 192.168.0.0: icmp_seq=2 ttl=64 time=0.031 ms
64 bytes from 192.168.0.0: icmp_seq=3 ttl=64 time=0.026 ms
```

VM-B can ping C2

```
root@10-9-54-162:~# ping 192.168.0.64
PING 192.168.0.64 (192.168.0.64) 56(84) bytes of data.
64 bytes from 192.168.0.64: icmp_seq=1 ttl=64 time=0.048 ms
64 bytes from 192.168.0.64: icmp_seq=2 ttl=64 time=0.031 ms
64 bytes from 192.168.0.64: icmp_seq=3 ttl=64 time=0.032 ms
```

**BUT**

VM-A **CAN NOT** ping C2

```
root@10-9-54-162:~# ping 192.168.0.0
PING 192.168.0.0 (192.168.0.0) 56(84) bytes of data.
```

VM-B **CAN NOT** ping C1

```
root@10-9-51-159:~# ping 192.168.0.64
PING 192.168.0.64 (192.168.0.64) 56(84) bytes of data.
```

No response

**Comment by frostynova** [comment]
@nashasha1 That is the correct behavior. If you want to do that, like what @natostanco said, you can modify your profile rule, add a new rule like that:

`calico profile {{ profile_name }} rule add inbound allow from cidr 10.9.0.0/16`

**Comment by nashasha1** [comment]
Hi @frostynova . Thank you for your help. But  still not work. Did I miss sth? I am using Calico as a Docker network plugin.

```
root@10-9-51-159:~# ./calicoctl profile show
+------------------------------------------------------------------+
|                               Name                               |
+------------------------------------------------------------------+
| c0c4675f88c50cfffe178e3122e61d16c148c460d83c8ad96e6384c5acb6fea3 |
+------------------------------------------------------------------+

root@10-9-51-159:~# ./calicoctl profile c0c4675f88c50cfffe178e3122e61d16c148c460d83c8ad96e6384c5acb6fea3 rule show
Inbound rules:
   1 allow from cidr 10.9.0.0/16
   2 allow from tag c0c4675f88c50cfffe178e3122e61d16c148c460d83c8ad96e6384c5acb6fea3
Outbound rules:
   1 allow
```

ping result:

```
root@10-9-54-162:~# ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1) 56(84) bytes of data.

```

No response.

Thank you for your help.

**Comment by frostynova** [comment]
@nashasha1 That's strange.

Can you paste the output of `calicoctl status` in both VMs?

**Comment by nashasha1** [comment]
@frostynova  Sorry, meeting time. I will stay on line this afternoon.

```
root@10-9-54-162:~# ./calicoctl status
calico-node container is running. Status: Up About an hour
Running felix version 1.4.0rc1

IPv4 BGP status
IP: 10.9.54.162    AS Number: 64511 (inherited)
+--------------+-------------------+-------+----------+-------------+
| Peer address |     Peer type     | State |  Since   |     Info    |
+--------------+-------------------+-------+----------+-------------+
| 10.9.51.159  | node-to-node mesh |   up  | 04:42:44 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 address configured.
```

```
root@10-9-51-159:~# ./calicoctl status
calico-node container is running. Status: Up About an hour
Running felix version 1.4.0rc1

IPv4 BGP status
IP: 10.9.51.159    AS Number: 64511 (inherited)
+--------------+-------------------+-------+----------+-------------+
| Peer address |     Peer type     | State |  Since   |     Info    |
+--------------+-------------------+-------+----------+-------------+
| 10.9.54.162  | node-to-node mesh |   up  | 04:42:44 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 address configured.
```

ip route result:

```
root@10-9-51-159:~# ip route
default via 10.9.0.1 dev eth0
10.9.0.0/16 dev eth0  proto kernel  scope link  src 10.9.51.159
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
blackhole 192.168.0.0/26  proto bird
192.168.0.1 dev calif91b9a24820  scope link
192.168.0.64/26 via 10.9.54.162 dev tunl0  proto bird onlink
root@10-9-51-159:~#
```

```
root@10-9-54-162:~# ip route
default via 10.9.0.1 dev eth0
10.9.0.0/16 dev eth0  proto kernel  scope link  src 10.9.54.162
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
192.168.0.0/26 via 10.9.51.159 dev tunl0  proto bird onlink
blackhole 192.168.0.64/26  proto bird
192.168.0.66 dev calic2af33c5cf2  scope link
root@10-9-54-162:~#
```

**Comment by frostynova** [comment]
@nashasha1 I noticed that you use ip tunnel mode between VMs from this line:
```
192.168.0.64/26 via 10.9.54.162 dev tunl0  proto bird onlink
```

I test this mode, also cannot ping from a VM to containers in another VM.

I am afraid i cannot give you more help since I have little experience with ip tunnel,

**Comment by nashasha1** [comment]
Thank you @frostynova  That's very helpful.

I am not familiar with it too. What mode do you use?  I want to try that!

**Comment by frostynova** [comment]
@nashasha1 i use the direct mode, this specified during calico pool creation 

```
calicoctl pool add 192.168.0.0/16
```

do not add the `--ipip` option

**Comment by nashasha1** [comment]
@frostynova  Thank you. I will try this!~

**Comment by nashasha1** [comment]
@frostynova  Thank you very much. direct mode without `--ipip` work well!

**Comment by TrimBiggs** [comment]
@frostynova thanks for pitching in here, you've been a great help in handling several issues recently :smiley:

**Comment by frostynova** [comment]
@TrimBiggs You are welcome

Our project benefit a lot from Project Calico, so I want to contribute to the community as much as possible.

**Comment by fanux** [comment]
I install calico on openstack VMs, and not use IPIP, but still can't ping pod on other node.
```
[root@fanux-test-5 out]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.1.1        0.0.0.0         UG    0      0        0 eth0
10.0.1.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
168.63.129.16   10.0.1.1        255.255.255.255 UGH   0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
169.254.169.254 10.0.1.1        255.255.255.255 UGH   0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.138.0   10.0.1.30       255.255.255.192 UG    0      0        0 eth0     # here
192.168.184.64  0.0.0.0         255.255.255.255 UH    0      0        0 calica330e2ab70
192.168.184.64  0.0.0.0         255.255.255.192 U     0      0        0 *
```

**Comment by tmjd** [comment]
@fanux My gut feel is that the openstack networking is dropping the traffic because the src/dst of the pod traffic does not match the what is expected from the VM.  I'd probably take a look with tcpdump to see if the traffic is leaving the source host (VM) and arriving on the destination host.

**Comment by fanux** [comment]
@tmjd I checked that, traffic is leaving the source host, but not arriving at the destination host. This issue is not caused by calico, but I don't know how to solve it. On aws has this issue too, some docs say disable the src/dst check can solve it. On openstack how to fix it?

**Comment by tmjd** [comment]
The simplest solution is to just enable IPIP.

If you can't do that then you might need some deep OpenStack networking knowledge and internal configuration changes/updates.  I'm only aware of that being a possible option because of a previous experience with traffic on an OpenStack network that was sent without the source/destination of the host.  Not something I would recommend and I don't have the faintest recollection of how to do.
