### ISSUE TITLE
Anycast/ECMP with Docker libnetwork?

### ISSUE THREAD

**Issue by wrouesnel** [projectcalico/calico-containers#982]
I know ECMP/anycast is possible with Calico (just the same route being advertised by felix) but at the moment it looks like it's not possible to set it up using the libnetwork plugins directly?

Specifically on 2 nodes I can't do this:
```/bin/bash
node1 $ docker run -it --name testwork1 --net=bedrock --ip=192.168.1.10 ubuntu:wily /bin/bash
node2 $ docker run -it --name testwork2 --net=bedrock --ip=192.168.1.10 ubuntu:wily /bin/bash
```

I need to step through the possible manual setup of this arrangement, but for our use-case (and the general "node suddenly dies, something like Marathon reschedules it" failure case) it seems pretty important to be able to okay - somehow - ECMP for a given network.

Am I missing something, or is this something which needs to be added to the plugin (I'm guessing maybe tag a metadata flag into network name to say "ecmp okay").

EDIT: Though looking at my calico version, 0.17 is definitely way too old...

**Comment by fasaxc** [comment]
I expect docker forbids you from using the same IP for two containers in a network.  If docker polices against it, Calico won't be able to offer that.

Note: our anycast support is limited.  It only works if the containers with the same IPs are on different hosts.  If your same-IP containers are on one host, I think only one of them will get traffic.

**Comment by wrouesnel** [comment]
With the Calico IPAM driver surely it could just lie?

In the short term the different hosts issue is fine - the problem is when an IP isn't deassigned due to a host crash, it still looks assigned so something like marathon rescheduling it fails.

I'll look into it some more.

**Comment by fasaxc** [comment]
I think an anycast address would always have to be a secondary address to any IPAM-assigned address.  Otherwise, a container can't connect out into the network because the response may go to the other container with the same IP.  Our IPAM plugin guards against that (it's purpose it to assign unique IPs to different containers).

**Comment by wrouesnel** [comment]
Could a specific IP request from docker be considered "give me an anycast address" though? That's a situation where the user is deliberately giving an intention. Currently it doesn't seem to useful because a hard docker crash / machine failure locks out the IP - even bug fixed you'd still be waiting for it to come back up and clean up.

Basically in a situation where you launch a container from an orchestrator it would be very really great to be able to either get an anycast address on addition to a regular one, or treat a manually specified IP as intentionally asking for one.

**Comment by fasaxc** [comment]
@wrouesnel Anything we do in our datamodel will live for a long time.  I'd rather not pollute the datamodel with special cases like this.

Note, you don't have to use libnetwork to use Calico with Docker.  You can start a container with `--net=none` and then use Calico to network it after-the-fact.  That has the advantage of giving you Calico's full flexibility in policy etc.  However, I expect we'd still police the uniqueness of IPs until we fully support multicast.  If you'd like to discuss further, I suggest joining our calico-users slack so we can discuss your requirements in more detail and see where it might come on our roadmap.

**Comment by matthewdupre** [comment]
Closing this for now, since it's not supported and won't be added immediately.

Having said that, if anyone reading is interested in this, please do talk to us on Slack, email, or leave a message here.  It's really helpful to get people's input so we can make sure development focuses on adding the right features.
