### ISSUE TITLE
kubelet can't started with the --config=/etc/kubernetes/manifests option

### ISSUE THREAD

**Issue by flyer5200** [projectcalico/calico-containers#984]
calico-policy-agent.yaml write hostNetwork: true
But kubelet can't start docker containers, how can I rule out this problem?

**Comment by fasaxc** [comment]
@flyer5200 Please can you give a bit more information about what you're trying to achieve and what error messages or other symptoms you see?

**Comment by flyer5200** [comment]
Thanks for your reply !  I think I've solved the problem. 
I am using the latest version of calico, but my kubernetes version is 1.2.0, I upgraded to 1.2.4 kubernetes after policy-agent seems to work.

But I found a new problem, I have set up kubernetes of networkpolicys for my application.
calico does not seem to apply firewall rules.

http://api.xxxx.cn/apis/net.alpha.kubernetes.io/v1alpha1/namespaces/xiaodai/networkpolicys
`{
  "kind": "NetworkPolicy",
  "apiVersion": "net.alpha.kubernetes.io/v1alpha1",
  "metadata":{
    "namespace":"xiaodai",
    "name": "nginx2-policy"
   },
   "spec":{
      "podSelector":{
        "name": "nginx2"
      },
      "ingress":[{
        "from":[{"pods":{"name":"nginx1"}}],
        "ports":[{"port":80,"protocol":"ICMP"}]
      }]
  }
}`

the ETCD Key is 
> /calico/v1/policy/profile/k8s_ns.xiaodai/rules
value is 
> {"id": "k8s_ns.xiaodai", "inbound_rules": [{"action": "deny"}], "outbound_rules": [{"action": "allow"}]}

Now, nginx1 can't ping nginx2, inbound_rule action still deny, why?

**Comment by fasaxc** [comment]
It's normal for `/calico/v1/policy/profile/k8s_ns.xiaodai/rules` to contain deny rules.  That's the "default deny" rule at the end of the rules applied to each endpoint.  The network policy should be in `/calico/v1/policy/policy/`

A few things to check:

- Have you enabled namespace isolation?
- Are you sure that your pods have labels `name=nginx1` and `name=nginx2`?
- Is this correct syntax: `"ports":[{"port":80,"protocol":"ICMP"}]`?  ICMP doesn't have a port so perhaps this rule is invalid.  (I don't have the k8s policy spec to hand.)
- Are there any errors in the Calico logs: on the compute hosts, these would be in `/var/log/calico/{cni|felix}/*`.

**Comment by caseydavenport** [comment]
> "ports":[{"port":80,"protocol":"ICMP"}]

ICMP isn't supported by the k8s policy API yet.  The only valid protocols are "TCP" and "UDP".

**Comment by flyer5200** [comment]
@fasaxc @caseydavenport 
I solved the problem, cause of the error is networkpolicy set incorrectly, after protocol to TCP, to give the desired results.
Thank you again! :+1:
