### ISSUE TITLE
cannot run felix on kernel 2.6.32

### ISSUE THREAD

**Issue by saiwl** [projectcalico/calico-containers#986]
For some reason, we need to run calico on kernel 2.6.32 without docker. But there is an error with felix about "ip6tables --table nat". I guess the kernel doesn't support ipv6 nat, and I cannot find the related kernel modules on the host. However, felix used this. I disabled ipv6 in sysctl.conf. But the error still exists.

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.all.forwarding = 0

I read the felix source file. Felix uses the "/proc/sys/net/ipv6" to decide whether to use ipv6. The ipv6 module is needed, so I cannot remove it. How can I run felix without using ipv6 even the host has ipv6 support?

**Comment by fasaxc** [comment]
@saiwl it's a large burden to support such an old kernel (2.6.32 is now 7 years old!).  What distribution are you using?

**Comment by saiwl** [comment]
centos6.7
For some reason we have to use this kernel... Here are the errors reported in felix's log:

2016-05-16 16:23:26,669 [ERROR][5622/5] calico.felix.actor 320: Exception processing M607b65941114a38a (_load_chain_names_from_iptables)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/calico/felix/actor.py", line 318, in _step
    result = msg.method()
  File "/usr/local/lib/python2.7/site-packages/calico/felix/fiptables.py", line 189, in _load_chain_names_from_iptables
    self.table])
  File "/usr/local/lib/python2.7/site-packages/gevent/subprocess.py", line 327, in check_output
    raise ex
CalledProcessError: Command '['ip6tables-save', '--table', 'nat']' returned non-zero exit status 1
2016-05-16 16:23:26,681 [INFO][5622/5] calico.felix.fiptables 485: IptablesUpdater<v6-nat,queue_len=0,live=True,msg=None> no updates in this batch.
TrackedAsyncResult ('<disabled>', '<disabled>', 'IptablesUpdater(v6-nat)', '_load_chain_names_from_iptables') was leaked with exception CalledProcessError().  Dying.
[root@docker2 felix]# iptables-save v1.4.7: Cannot initialize: Table does not exist (do you need to insmod?)

**Comment by saiwl** [comment]
@fasaxc

**Comment by fasaxc** [comment]
Hmm, we don't have an option to disable IPv6 right now.  It looks like IPv6 NAT was added in 2011 so it's likely missing from your kernel.

**Comment by saiwl** [comment]
Thanks for your help! I will try other methods to solve this.

**Comment by fasaxc** [comment]
@saiwl it might be worth editing the calico code in the container just to check if this is the only issue.  You could replace the check for the ipv6 `/proc/` entry with `False`.
