### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by HuKeping** [projectcalico/calico-containers#996]
Hi, all: 
I'm new to Calico and will really appreciate that if someone can tell me whether Calico supports the multi-tenant in the DC or not, for example, userA might want to set 12:34:56:78:9a:bc and 10.0.0.1 to his VM and userB want that also, will they overlay each other if using Calico?

**Comment by fasaxc** [comment]
@HuKeping Calico does not currently support overlapping IPs (i.e. multiple tenants using the same IP address). Our rich security model does allow for isolating tenants from each other but they do not get to choose their IP addresses.  Making that simplification allows us to have a much more efficient and easy-to-debug datapath.

**Comment by HuKeping** [comment]
Thanks @fasaxc
