### ISSUE TITLE
Document --runtime option

### ISSUE THREAD

**Issue by sgrimee** [projectcalico/calico-containers#997]
When using calico node under rkt instead of docker, the status command will fail:

```
   sudo ./calicoctl status
   calico-node container not running
```

Instead one needs to use

```
  sudo ./calicoctl status --runtime=rkt
```

The error message could be improved to suggest this option, and the option should be documented

**Comment by matthewdupre** [comment]
Maybe the best solution here is to check the status of both docker and rkt calico-nodes together; and 

The most obvious downside is that the rkt version needs root.  Do people think that's acceptable?

**Comment by sgrimee** [comment]
There isn't a big difference between a user with docker access and root, is there?

**Comment by caseydavenport** [comment]
@gunjan5 what is the status of this in the v1.0.0-beta release? Do we still have a `--runtime` option?

**Comment by gunjan5** [comment]
@caseydavenport we don't have `--runtime` option in v1.0.0-beta release anymore

**Comment by caseydavenport** [comment]
This is staying in the v2.0 release.  No --runtime any more, but we should document clearly how to run in rkt.


See: https://github.com/projectcalico/calico/pull/344
